
SQL*Plus: Release 11.2.0.3.0 Production on Tue Jun 25 17:32:45 2013

Copyright (c) 1982, 2011, Oracle.  All rights reserved.


Connected to:
Oracle Database 10g Release 10.2.0.4.0 - Production

SQL> SQL> PROCEDURE FUSENVBONIS
 Argument Name			Type			In/Out Default?
 ------------------------------ ----------------------- ------ --------
 SRV_MESSAGE			VARCHAR2		IN/OUT
 IN_EXTCODFINANCIADOR		NUMBER			IN
 IN_EXTHOMNUMEROCONVENIO	VARCHAR2		IN
 IN_EXTHOMLUGARCONVENIO 	VARCHAR2		IN
 IN_EXTSUCVENTA 		VARCHAR2		IN
 IN_EXTRUTCONVENIO		VARCHAR2		IN
 IN_EXTRUTASOCIADO		VARCHAR2		IN
 IN_EXTNOMPRESTADOR		VARCHAR2		IN
 IN_EXTRUTTRATANTE		VARCHAR2		IN
 IN_EXTESPECIALIDAD		VARCHAR2		IN
 IN_EXTRUTBENEFICIARIO		VARCHAR2		IN
 IN_EXTRUTCOTIZANTE		VARCHAR2		IN
 IN_EXTRUTACOMPANANTE		VARCHAR2		IN
 IN_EXTRUTEMISOR		VARCHAR2		IN
 IN_EXTRUTCAJERO		VARCHAR2		IN
 IN_EXTCODIGODIAGNOSTICO	VARCHAR2		IN
 IN_EXTDESCUENTOXPLANILLA	VARCHAR2		IN
 IN_EXTMONTOEXCEDENTE		NUMBER			IN
 IN_EXTFECHAEMISION		VARCHAR2		IN
 IN_EXTNIVELCONVENIO		NUMBER			IN
 IN_EXTFOLIOFINANCIADOR 	NUMBER			IN
 IN_EXTMONTOVALORTOTAL		NUMBER			IN
 IN_EXTMONTOAPORTETOTAL 	NUMBER			IN
 IN_EXTMONTOCOPAGOTOTAL 	NUMBER			IN
 IN_EXTNUMOPERACION		NUMBER			IN
 IN_EXTCORRPRESTACION		NUMBER			IN
 IN_EXTTIPOSOLICITUD		NUMBER			IN
 IN_EXTFECHAINICIO		VARCHAR2		IN
 IN_EXTURGENCIA 		VARCHAR2		IN
 IN_EXTPLAN			VARCHAR2		IN
 IN_EXTLISTA1			VARCHAR2		IN
 IN_EXTLISTA2			VARCHAR2		IN
 IN_EXTLISTA3			VARCHAR2		IN
 OUT_EXTCODERROR		VARCHAR2		OUT
 OUT_EXTMENSAJEERROR		VARCHAR2		OUT
PROCEDURE RBLENVBONIS
 Argument Name			Type			In/Out Default?
 ------------------------------ ----------------------- ------ --------
 SRV_MESSAGE			VARCHAR2		IN/OUT
 IN_EXTCODFINANCIADOR		NUMBER			IN
 IN_EXTHOMNUMEROCONVENIO	VARCHAR2		IN
 IN_EXTHOMLUGARCONVENIO 	VARCHAR2		IN
 IN_EXTSUCVENTA 		VARCHAR2		IN
 IN_EXTRUTCONVENIO		VARCHAR2		IN
 IN_EXTRUTASOCIADO		VARCHAR2		IN
 IN_EXTNOMPRESTADOR		VARCHAR2		IN
 IN_EXTRUTTRATANTE		VARCHAR2		IN
 IN_EXTESPECIALIDAD		VARCHAR2		IN
 IN_EXTRUTBENEFICIARIO		VARCHAR2		IN
 IN_EXTRUTCOTIZANTE		VARCHAR2		IN
 IN_EXTRUTACOMPANANTE		VARCHAR2		IN
 IN_EXTRUTEMISOR		VARCHAR2		IN
 IN_EXTRUTCAJERO		VARCHAR2		IN
 IN_EXTCODIGODIAGNOSTICO	VARCHAR2		IN
 IN_EXTDESCUENTOXPLANILLA	VARCHAR2		IN
 IN_EXTMONTOEXCEDENTE		NUMBER			IN
 IN_EXTFECHAEMISION		VARCHAR2		IN
 IN_EXTNIVELCONVENIO		NUMBER			IN
 IN_EXTFOLIOFINANCIADOR 	NUMBER			IN
 IN_EXTMONTOVALORTOTAL		NUMBER			IN
 IN_EXTMONTOAPORTETOTAL 	NUMBER			IN
 IN_EXTMONTOCOPAGOTOTAL 	NUMBER			IN
 IN_EXTNUMOPERACION		NUMBER			IN
 IN_EXTCORRPRESTACION		NUMBER			IN
 IN_EXTTIPOSOLICITUD		NUMBER			IN
 IN_EXTFECHAINICIO		VARCHAR2		IN
 IN_EXTURGENCIA 		VARCHAR2		IN
 IN_EXTPLAN			VARCHAR2		IN
 IN_EXTLISTA1			VARCHAR2		IN
 IN_EXTLISTA2			VARCHAR2		IN
 IN_EXTLISTA3			VARCHAR2		IN
 OUT_EXTCODERROR		VARCHAR2		OUT
 OUT_EXTMENSAJEERROR		VARCHAR2		OUT
PROCEDURE SNLENVBONIS
 Argument Name			Type			In/Out Default?
 ------------------------------ ----------------------- ------ --------
 SRV_MESSAGE			VARCHAR2		IN/OUT
 IN_EXTCODFINANCIADOR		NUMBER			IN
 IN_EXTHOMNUMEROCONVENIO	VARCHAR2		IN
 IN_EXTHOMLUGARCONVENIO 	VARCHAR2		IN
 IN_EXTSUCVENTA 		VARCHAR2		IN
 IN_EXTRUTCONVENIO		VARCHAR2		IN
 IN_EXTRUTASOCIADO		VARCHAR2		IN
 IN_EXTNOMPRESTADOR		VARCHAR2		IN
 IN_EXTRUTTRATANTE		VARCHAR2		IN
 IN_EXTESPECIALIDAD		VARCHAR2		IN
 IN_EXTRUTBENEFICIARIO		VARCHAR2		IN
 IN_EXTRUTCOTIZANTE		VARCHAR2		IN
 IN_EXTRUTACOMPANANTE		VARCHAR2		IN
 IN_EXTRUTEMISOR		VARCHAR2		IN
 IN_EXTRUTCAJERO		VARCHAR2		IN
 IN_EXTCODIGODIAGNOSTICO	VARCHAR2		IN
 IN_EXTDESCUENTOXPLANILLA	VARCHAR2		IN
 IN_EXTMONTOEXCEDENTE		NUMBER			IN
 IN_EXTFECHAEMISION		VARCHAR2		IN
 IN_EXTNIVELCONVENIO		NUMBER			IN
 IN_EXTFOLIOFINANCIADOR 	NUMBER			IN
 IN_EXTMONTOVALORTOTAL		NUMBER			IN
 IN_EXTMONTOAPORTETOTAL 	NUMBER			IN
 IN_EXTMONTOCOPAGOTOTAL 	NUMBER			IN
 IN_EXTNUMOPERACION		NUMBER			IN
 IN_EXTCORRPRESTACION		NUMBER			IN
 IN_EXTTIPOSOLICITUD		NUMBER			IN
 IN_EXTFECHAINICIO		VARCHAR2		IN
 IN_EXTURGENCIA 		VARCHAR2		IN
 IN_EXTPLAN			VARCHAR2		IN
 IN_EXTLISTA1			VARCHAR2		IN
 IN_EXTLISTA2			VARCHAR2		IN
 IN_EXTLISTA3			VARCHAR2		IN
 OUT_EXTCODERROR		VARCHAR2		OUT
 OUT_EXTMENSAJEERROR		VARCHAR2		OUT

SQL> Disconnected from Oracle Database 10g Release 10.2.0.4.0 - Production
