#/home/isys/instantclient_11_2/sqlplus ADMIMED/ADMIMED@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.220.13)(PORT=1521))(CONNECT_DATA=(SID=IFUSAT)))"

DIR='/home/isys/base/bono3/CHUQUICAMATA/sp_oracle/'
SQLPLUS='/home/isys/instantclient_11_2/sqlplus'
HOST='192.168.220.13'
PORT='1521'
USR='ADMIMED'
USR1='ADMIMED_CONV'
PWD='ADMIMED'
SID='IFUSAT'

#/home/isys/instantclient_11_2/sqlplus ADMIMED/ADMIMED@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.220.13)(PORT=1521))(CONNECT_DATA=(SID=IFUSAT)))"
#/home/isys/instantclient_11_2/sqlplus $USR/$PWD"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))"
#SELECT OBJECT_NAME,OBJECT_TYPE,OWNER FROM ALL_OBJECTS ORDER BY OBJECT_TYPE asc;

#cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/modelo_db.txt
#SET PAGESIZE 999 LINESIZE 999;
#SELECT OBJECT_NAME,OBJECT_TYPE,OWNER FROM ALL_OBJECTS ORDER BY OBJECT_NAME asc;
#EOT
cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/all_all_table.txt
SET PAGESIZE 999 LINESIZE 999;
select * from ALL_ALL_TABLES order by TABLE_NAME asc;
EOT
cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/procedure.txt
SET PAGESIZE 999 LINESIZE 999;
select OBJECT_NAME,PROCEDURE_NAME,OBJECT_TYPE,OWNER from ALL_PROCEDURES order by PROCEDURE_NAME;
EOT

#####################################################################################################################################
cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/CHUANULABONOU_PKG.sql
SET PAGESIZE 999 LINESIZE 999;
desc CHUANULABONOU_PKG
EOT
cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/CHUANULABONOU_PKG_BODY.sql
SET PAGESIZE 999 LINESIZE 999;
SELECT text from all_source where name ='CHUANULABONOU_PKG' and type in('PACKAGE BODY') and OWNER='ADMIMED_CONV' order by line asc;
EOT

cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/CHUBENCERTIF_PKG.sql
SET PAGESIZE 999 LINESIZE 999;
desc CHUBENCERTIF_PKG
EOT
cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/CHUBENCERTIF_PKG_BODY.sql
SET PAGESIZE 999 LINESIZE 999;
SELECT text from all_source where name ='CHUBENCERTIF_PKG' and type in('PACKAGE BODY') and OWNER='ADMIMED_CONV' order by line asc;
EOT

cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/CHUENROLA_PKG.sql
SET PAGESIZE 999 LINESIZE 999;
desc CHUENROLA_PKG
EOT
cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/CHUENROLA_PKG_BODY.sql
SET PAGESIZE 999 LINESIZE 999;
SELECT text from all_source where name ='CHUENROLA_PKG' and type in('PACKAGE BODY') and OWNER='ADMIMED_CONV' order by line asc;
EOT

#select text from all_source where name = 'CHUENVBONIS_PKG' and type in('PACKAGE','SYNONYM') order by line asc;
cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/CHUENVBONIS_PKG.sql
SET PAGESIZE 999 LINESIZE 999;
desc CHUENVBONIS_PKG
EOT
cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/CHUENVBONIS_PKG_BODY.sql
SET PAGESIZE 999 LINESIZE 999;
SELECT text from all_source where name = 'CHUENVBONIS_PKG' and type in('PACKAGE BODY') and OWNER='ADMIMED_CONV' order by line asc;
EOT

cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/CHULEERUTCOTIZ_PKG.sql
SET PAGESIZE 999 LINESIZE 999;
select text from all_source where name = 'CHULEERUTCOTIZ_PKG' and type in('PACKAGE','SYNONYM') order by line asc;
EOT
cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/CHULEERUTCOTIZ_PKG_BODY.sql
SET PAGESIZE 999 LINESIZE 999;
SELECT text from all_source where name ='CHULEERUTCOTIZ_PKG' and type in('PACKAGE BODY') and OWNER='ADMIMED_CONV' order by line asc;
EOT

cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/CHUPRESTPAQUETE_PKG.sql
SET PAGESIZE 999 LINESIZE 999;
select text from all_source where name = 'CHUPRESTPAQUETE_PKG' and type in('PACKAGE','SYNONYM') order by line asc;
EOT

cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/CHUSOLICFOLIOS_PKG.sql
SET PAGESIZE 999 LINESIZE 999;
select text from all_source where name = 'CHUSOLICFOLIOS_PKG' and type in('PACKAGE','SYNONYM') order by line asc;
EOT
cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/CHUSOLICFOLIOS_PKG_BODY.sql
SET PAGESIZE 999 LINESIZE 999;
SELECT text from all_source where name ='CHUSOLICFOLIOS_PKG' and type in('PACKAGE BODY') and OWNER='ADMIMED_CONV' order by line asc;
EOT

cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/CHUVALORVARI_PKG.sql
SET PAGESIZE 999 LINESIZE 999;
select text from all_source where name = 'CHUVALORVARI_PKG' and type in('PACKAGE','SYNONYM') order by line asc;
EOT
cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/CHUVALORVARI_PKG_BODY.sql
SET PAGESIZE 999 LINESIZE 999;
SELECT text from all_source where name ='CHUVALORVARI_PKG' and type in('PACKAGE BODY') and OWNER='ADMIMED_CONV' order by line asc;
EOT

cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/CHUVALTRANS_PKG.sql
SET PAGESIZE 999 LINESIZE 999;
select text from all_source where name = 'CHUVALTRANS_PKG' and type in('PACKAGE','SYNONYM') order by line asc;
EOT
cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/CHUVALTRANS_PKG_BODY.sql
SET PAGESIZE 999 LINESIZE 999;
SELECT text from all_source where name ='CHUVALTRANS_PKG' and type in('PACKAGE BODY') and OWNER='ADMIMED_CONV' order by line asc;
EOT
