#/home/isys/instantclient_11_2/sqlplus ADMIMED/ADMIMED@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.220.13)(PORT=1521))(CONNECT_DATA=(SID=IFUSAT)))"

DIR='/home/isys/base/bono3/RIOBLANCO/sp_oracle/'
SQLPLUS='/home/isys/instantclient_11_2/sqlplus'
HOST='192.168.220.13'
PORT='1521'
USR='ADMIMED'
USR1='IRB_ADMIMED'
PWD='ADMIMED'
SID='IFUSAT'

#/home/isys/instantclient_11_2/sqlplus ADMIMED/ADMIMED@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.220.13)(PORT=1521))(CONNECT_DATA=(SID=IFUSAT)))"
#/home/isys/instantclient_11_2/sqlplus $USR/$PWD"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))"
#SELECT OBJECT_NAME,OBJECT_TYPE,OWNER FROM ALL_OBJECTS ORDER BY OBJECT_TYPE asc;

cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/modelo_db.txt
#SET PAGESIZE 999 LINESIZE 999;
SELECT OBJECT_NAME,OBJECT_TYPE,OWNER FROM ALL_OBJECTS ORDER BY OBJECT_NAME asc;
EOT
cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/all_all_table.txt
SET PAGESIZE 999 LINESIZE 999;
select * from ALL_ALL_TABLES order by TABLE_NAME asc;
EOT
cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/procedure.txt
SET PAGESIZE 999 LINESIZE 999;
select OBJECT_NAME,PROCEDURE_NAME,OBJECT_TYPE,OWNER from ALL_PROCEDURES order by PROCEDURE_NAME;
EOT

#####################################################################################################################################
cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/RBLANULABONOU_PKG.sql
SET PAGESIZE 999 LINESIZE 999;
SELECT text from all_source where name ='RBLANULABONOU_PKG' and type in('PACKAGE','SYNONYM') order by line asc;
SELECT text from all_source where name ='RBLANULABONOU_PKG' and type in('PACKAGE BODY') and OWNER='IRB_ADMIMED' order by line asc;
EOT

cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/RBLBENCERTIF_PKG.sql
SET PAGESIZE 999 LINESIZE 999;
SELECT text from all_source where name ='RBLBENCERTIF_PKG' and type in('PACKAGE','SYNONYM') order by line asc;
SELECT text from all_source where name ='RBLBENCERTIF_PKG' and type in('PACKAGE BODY') and OWNER='IRB_ADMIMED' order by line asc;
EOT

cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/RBLENROLA_PKG.sql
SET PAGESIZE 999 LINESIZE 999;:
SELECT text from all_source where name ='RBLENROLA_PKG' and type in('PACKAGE','SYNONYM') order by line asc;
SELECT text from all_source where name ='RBLENROLA_PKG' and type in('PACKAGE BODY') and OWNER='IRB_ADMIMED' order by line asc;
EOT

cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/RBLENVBONIS_PKG.sql
SET PAGESIZE 999 LINESIZE 999;
SELECT text from all_source where name ='RBLENVBONIS_PKG' and type in('PACKAGE','SYNONYM') order by line asc;
SELECT text from all_source where name ='RBLENVBONIS_PKG' and type in('PACKAGE BODY') and OWNER='IRB_ADMIMED' order by line asc;
EOT

cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/RBLLEERUTCOTIZ_PKG.sql
SET PAGESIZE 999 LINESIZE 999;
SELECT text from all_source where name ='RBLLEERUTCOTIZ_PKG' and type in('PACKAGE','SYNONYM') order by line asc;
SELECT text from all_source where name ='RBLLEERUTCOTIZ_PKG' and type in('PACKAGE BODY') and OWNER='IRB_ADMIMED' order by line asc;
EOT

cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/RBLSOLICFOLIOS_PKG.sql
SET PAGESIZE 999 LINESIZE 999;
SELECT text from all_source where name ='RBLSOLICFOLIOS_PKG' and type in('PACKAGE','SYNONYM') order by line asc;
SELECT text from all_source where name ='RBLSOLICFOLIOS_PKG' and type in('PACKAGE BODY') and OWNER='IRB_ADMIMED' order by line asc;
EOT

cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/RBLVALORVARI_PKG.sql
SET PAGESIZE 999 LINESIZE 999;
SELECT text from all_source where name ='RBLVALORVARI_PKG' and type in('PACKAGE','SYNONYM') order by line asc;
SELECT text from all_source where name ='RBLVALORVARI_PKG' and type in('PACKAGE BODY') and OWNER='IRB_ADMIMED' order by line asc;
EOT

cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/RBLVALTRANS_PKG.sql
SET PAGESIZE 999 LINESIZE 999;
SELECT text from all_source where name ='RBLVALTRANS_PKG' and type in('PACKAGE','SYNONYM') order by line asc;
SELECT text from all_source where name ='RBLVALTRANS_PKG' and type in('PACKAGE BODY') and OWNER='IRB_ADMIMED' order by line asc;
EOT
