
ql -d motor -f proc_parser_ceranthab.sql
psql -d motor -f proc_parser_cerantqui.sql
psql -d motor -f proc_parser_cerantmor.sql
psql -d motor -f proc_parser_cerconciliacioncme.sql
psql -d motor -f proc_parser_cerdetevo.sql
psql -d motor -f proc_parser_cerdetanam.sql
psql -d motor -f proc_parser_cerdetprot.sql
psql -d motor -f proc_parser_cerdiaegr.sql
psql -d motor -f proc_parser_cerdiagpreop.sql
psql -d motor -f proc_parser_cerdiagposop.sql
psql -d motor -f proc_parser_ceremibonopam.sql
psql -d motor -f proc_parser_cerencanam.sql
psql -d motor -f proc_parser_cerencprot.sql
psql -d motor -f proc_parser_cerencepi.sql
psql -d motor -f proc_parser_cerenvcta.sql
psql -d motor -f proc_parser_cerenvdetequipo.sql
psql -d motor -f proc_parser_cerenvdethotele.sql
psql -d motor -f proc_parser_cerenvinfpac.sql
psql -d motor -f proc_parser_cerenvdetinsumo.sql
psql -d motor -f proc_parser_cerenvpaquete.sql
psql -d motor -f proc_parser_cerepiind.sql
psql -d motor -f proc_parser_cerenvtipant.sql
psql -d motor -f proc_parser_cerequmed.sql
psql -d motor -f proc_parser_cergrpfam.sql
psql -d motor -f proc_parser_cerexafis.sql
psql -d motor -f proc_parser_cerobtbonhotele.sql
psql -d motor -f proc_parser_cerobtbonequipo.sql
psql -d motor -f proc_parser_cerobtboninsumo.sql
psql -d motor -f proc_parser_cerobtfecpag.sql
psql -d motor -f proc_parser_cerobtbonospam.sql
psql -d motor -f proc_parser_cerobtpaquete.sql
psql -d motor -f proc_parser_cerotrcir.sql
psql -d motor -f proc_parser_cerobtsaldospag.sql
psql -d motor -f proc_parser_cerrelhmqprot.sql
psql -d motor -f proc_parser_certrapro.sqlone
