drop table convert_octal_ascii;
create table convert_octal_ascii (
	octal varchar, 
	symbol varchar,
	ascii integer,
	descripcion varchar
);

insert into convert_octal_ascii values ('\000','',0,'<control>');
insert into convert_octal_ascii values ('\001',null,1,'<control>');
insert into convert_octal_ascii values ('\002',null,2,'<control>');
insert into convert_octal_ascii values ('\003',null,3,'<control>');
insert into convert_octal_ascii values ('\004',null,4,'<control>');
insert into convert_octal_ascii values ('\005',null,5,'<control>');
insert into convert_octal_ascii values ('\006',null,6,'<control>');
insert into convert_octal_ascii values ('\007',null,7,'<control>');
insert into convert_octal_ascii values ('\010',null,8,'<control>');
insert into convert_octal_ascii values ('\011',null,9,'<control>');
insert into convert_octal_ascii values ('\012',null,10,'<control>');
insert into convert_octal_ascii values ('\013',null,11,'<control>');
insert into convert_octal_ascii values ('\014',null,12,'<control>');
insert into convert_octal_ascii values ('\015',null,13,'<control>');
insert into convert_octal_ascii values ('\016',null,14,'<control>');
insert into convert_octal_ascii values ('\017',null,15,'<control>');
insert into convert_octal_ascii values ('\020',null,16,'<control>');
insert into convert_octal_ascii values ('\021',null,17,'<control>');
insert into convert_octal_ascii values ('\022',null,18,'<control>');
insert into convert_octal_ascii values ('\023',null,19,'<control>');
insert into convert_octal_ascii values ('\024',null,20,'<control>');
insert into convert_octal_ascii values ('\025',null,21,'<control>');
insert into convert_octal_ascii values ('\026',null,22,'<control>');
insert into convert_octal_ascii values ('\027',null,23,'<control>');
insert into convert_octal_ascii values ('\030',null,24,'<control>');
insert into convert_octal_ascii values ('\031',null,25,'<control>');
insert into convert_octal_ascii values ('\032',null,26,'<control>');
insert into convert_octal_ascii values ('\033',null,27,'<control>');
insert into convert_octal_ascii values ('\034',null,28,'<control>');
insert into convert_octal_ascii values ('\035',null,29,'<control>');
insert into convert_octal_ascii values ('\036',null,30,'<control>');
insert into convert_octal_ascii values ('\037',null,31,'<control>');
insert into convert_octal_ascii values ('\040',null,32,'SPACE');
insert into convert_octal_ascii values ('\041','!',33,'EXCLAMATION MARK');
insert into convert_octal_ascii values ('\042','"',34,'QUOTATION MARK');
insert into convert_octal_ascii values ('\043','#',35,'NUMBER SIGN');
insert into convert_octal_ascii values ('\044','$',36,'DOLLAR SIGN');
insert into convert_octal_ascii values ('\045','%',37,'PERCENT SIGN');
insert into convert_octal_ascii values ('\046','&',38,'AMPERSAND');
insert into convert_octal_ascii values ('\047',null,39,'APOSTROPHE');
insert into convert_octal_ascii values ('\050','(',40,'LEFT PARENTHESIS');
insert into convert_octal_ascii values ('\051',')',41,'RIGHT PARENTHESIS');
insert into convert_octal_ascii values ('\052','*',42,'ASTERISK');
insert into convert_octal_ascii values ('\053','+',43,'PLUS SIGN');
insert into convert_octal_ascii values ('\054',',',44,'COMMA');
insert into convert_octal_ascii values ('\055','-',45,'HYPHEN-MINUS');
insert into convert_octal_ascii values ('\056','.',46,'FULL STOP');
insert into convert_octal_ascii values ('\057','/',47,'SOLIDUS');
insert into convert_octal_ascii values ('\060','0',48,'DIGIT ZERO');
insert into convert_octal_ascii values ('\061','1',49,'DIGIT ONE');
insert into convert_octal_ascii values ('\062','2',50,'DIGIT TWO');
insert into convert_octal_ascii values ('\063','3',51,'DIGIT THREE');
insert into convert_octal_ascii values ('\064','4',52,'DIGIT FOUR');
insert into convert_octal_ascii values ('\065','5',53,'DIGIT FIVE');
insert into convert_octal_ascii values ('\066','6',54,'DIGIT SIX');
insert into convert_octal_ascii values ('\067','7',55,'DIGIT SEVEN');
insert into convert_octal_ascii values ('\070','8',56,'DIGIT EIGHT');
insert into convert_octal_ascii values ('\071','9',57,'DIGIT NINE');
insert into convert_octal_ascii values ('\072',':',58,'COLON');
insert into convert_octal_ascii values ('\073',';',59,'SEMICOLON');
insert into convert_octal_ascii values ('\074','<',60,'LESS-THAN SIGN');
insert into convert_octal_ascii values ('\075','=',61,'EQUALS SIGN');
insert into convert_octal_ascii values ('\076','>',62,'GREATER-THAN SIGN');
insert into convert_octal_ascii values ('\077','?',63,'QUESTION MARK');
insert into convert_octal_ascii values ('\100','@',64,'COMMERCIAL AT');
insert into convert_octal_ascii values ('\101','A',65,'LATIN CAPITAL LETTER A');
insert into convert_octal_ascii values ('\102','B',66,'LATIN CAPITAL LETTER B');
insert into convert_octal_ascii values ('\103','C',67,'LATIN CAPITAL LETTER C');
insert into convert_octal_ascii values ('\104','D',68,'LATIN CAPITAL LETTER D');
insert into convert_octal_ascii values ('\105','E',69,'LATIN CAPITAL LETTER E');
insert into convert_octal_ascii values ('\106','F',70,'LATIN CAPITAL LETTER F');
insert into convert_octal_ascii values ('\107','G',71,'LATIN CAPITAL LETTER G');
insert into convert_octal_ascii values ('\110','H',72,'LATIN CAPITAL LETTER H');
insert into convert_octal_ascii values ('\111','I',73,'LATIN CAPITAL LETTER I');
insert into convert_octal_ascii values ('\112','J',74,'LATIN CAPITAL LETTER J');
insert into convert_octal_ascii values ('\113','K',75,'LATIN CAPITAL LETTER K');
insert into convert_octal_ascii values ('\114','L',76,'LATIN CAPITAL LETTER L');
insert into convert_octal_ascii values ('\115','M',77,'LATIN CAPITAL LETTER M');
insert into convert_octal_ascii values ('\116','N',78,'LATIN CAPITAL LETTER N');
insert into convert_octal_ascii values ('\117','O',79,'LATIN CAPITAL LETTER O');
insert into convert_octal_ascii values ('\120','P',80,'LATIN CAPITAL LETTER P');
insert into convert_octal_ascii values ('\121','Q',81,'LATIN CAPITAL LETTER Q');
insert into convert_octal_ascii values ('\122','R',82,'LATIN CAPITAL LETTER R');
insert into convert_octal_ascii values ('\123','S',83,'LATIN CAPITAL LETTER S');
insert into convert_octal_ascii values ('\124','T',84,'LATIN CAPITAL LETTER T');
insert into convert_octal_ascii values ('\125','U',85,'LATIN CAPITAL LETTER U');
insert into convert_octal_ascii values ('\126','V',86,'LATIN CAPITAL LETTER V');
insert into convert_octal_ascii values ('\127','W',87,'LATIN CAPITAL LETTER W');
insert into convert_octal_ascii values ('\130','X',88,'LATIN CAPITAL LETTER X');
insert into convert_octal_ascii values ('\131','Y',89,'LATIN CAPITAL LETTER Y');
insert into convert_octal_ascii values ('\132','Z',90,'LATIN CAPITAL LETTER Z');
insert into convert_octal_ascii values ('\133','[',91,'LEFT SQUARE BRACKET');
insert into convert_octal_ascii values ('\134','\',92,'REVERSE SOLIDUS');
insert into convert_octal_ascii values ('\135',']',93,'RIGHT SQUARE BRACKET');
insert into convert_octal_ascii values ('\136','^',94,'CIRCUMFLEX ACCENT');
insert into convert_octal_ascii values ('\137','_',95,'LOW LINE');
insert into convert_octal_ascii values ('\140','`',96,'GRAVE ACCENT');
insert into convert_octal_ascii values ('\141','a',97,'LATIN SMALL LETTER A');
insert into convert_octal_ascii values ('\142','b',98,'LATIN SMALL LETTER B');
insert into convert_octal_ascii values ('\143','c',99,'LATIN SMALL LETTER C');
insert into convert_octal_ascii values ('\144','d',100,'LATIN SMALL LETTER D');
insert into convert_octal_ascii values ('\145','e',101,'LATIN SMALL LETTER E');
insert into convert_octal_ascii values ('\146','f',102,'LATIN SMALL LETTER F');
insert into convert_octal_ascii values ('\147','g',103,'LATIN SMALL LETTER G');
insert into convert_octal_ascii values ('\150','h',104,'LATIN SMALL LETTER H');
insert into convert_octal_ascii values ('\151','i',105,'LATIN SMALL LETTER I');
insert into convert_octal_ascii values ('\152','j',106,'LATIN SMALL LETTER J');
insert into convert_octal_ascii values ('\153','k',107,'LATIN SMALL LETTER K');
insert into convert_octal_ascii values ('\154','l',108,'LATIN SMALL LETTER L');
insert into convert_octal_ascii values ('\155','m',109,'LATIN SMALL LETTER M');
insert into convert_octal_ascii values ('\156','n',110,'LATIN SMALL LETTER N');
insert into convert_octal_ascii values ('\157','o',111,'LATIN SMALL LETTER O');
insert into convert_octal_ascii values ('\160','p',112,'LATIN SMALL LETTER P');
insert into convert_octal_ascii values ('\161','q',113,'LATIN SMALL LETTER Q');
insert into convert_octal_ascii values ('\162','r',114,'LATIN SMALL LETTER R');
insert into convert_octal_ascii values ('\163','s',115,'LATIN SMALL LETTER S');
insert into convert_octal_ascii values ('\164','t',116,'LATIN SMALL LETTER T');
insert into convert_octal_ascii values ('\165','u',117,'LATIN SMALL LETTER U');
insert into convert_octal_ascii values ('\166','v',118,'LATIN SMALL LETTER V');
insert into convert_octal_ascii values ('\167','w',119,'LATIN SMALL LETTER W');
insert into convert_octal_ascii values ('\170','x',120,'LATIN SMALL LETTER X');
insert into convert_octal_ascii values ('\171','y',121,'LATIN SMALL LETTER Y');
insert into convert_octal_ascii values ('\172','z',122,'LATIN SMALL LETTER Z');
insert into convert_octal_ascii values ('\173','{',123,'LEFT CURLY BRACKET');
insert into convert_octal_ascii values ('\174','|',124,'VERTICAL LINE');
insert into convert_octal_ascii values ('\175','}',125,'RIGHT CURLY BRACKET');
insert into convert_octal_ascii values ('\176','~',126,'TILDE');
insert into convert_octal_ascii values ('\177',null,127,'<control>');
insert into convert_octal_ascii values ('\302\200',null,128,'<control>');
insert into convert_octal_ascii values ('\302\201',null,129,'<control>');
insert into convert_octal_ascii values ('\302\202',null,130,'<control>');
insert into convert_octal_ascii values ('\302\203',null,131,'<control>');
insert into convert_octal_ascii values ('\302\204',null,132,'<control>');
insert into convert_octal_ascii values ('\302\205',null,133,'<control>');
insert into convert_octal_ascii values ('\302\206',null,134,'<control>');
insert into convert_octal_ascii values ('\302\207',null,135,'<control>');
insert into convert_octal_ascii values ('\302\210',null,136,'<control>');
insert into convert_octal_ascii values ('\302\211',null,137,'<control>');
insert into convert_octal_ascii values ('\302\212',null,138,'<control>');
insert into convert_octal_ascii values ('\302\213',null,139,'<control>');
insert into convert_octal_ascii values ('\302\214',null,140,'<control>');
insert into convert_octal_ascii values ('\302\215',null,141,'<control>');
insert into convert_octal_ascii values ('\302\216',null,142,'<control>');
insert into convert_octal_ascii values ('\302\217',null,143,'<control>');
insert into convert_octal_ascii values ('\302\220',null,144,'<control>');
insert into convert_octal_ascii values ('\302\221',null,145,'<control>');
insert into convert_octal_ascii values ('\302\222',null,146,'<control>');
insert into convert_octal_ascii values ('\302\223',null,147,'<control>');
insert into convert_octal_ascii values ('\302\224',null,148,'<control>');
insert into convert_octal_ascii values ('\302\225',null,149,'<control>');
insert into convert_octal_ascii values ('\302\226',null,150,'<control>');
insert into convert_octal_ascii values ('\302\227',null,151,'<control>');
insert into convert_octal_ascii values ('\302\230',null,152,'<control>');
insert into convert_octal_ascii values ('\302\231',null,153,'<control>');
insert into convert_octal_ascii values ('\302\232',null,154,'<control>');
insert into convert_octal_ascii values ('\302\233',null,155,'<control>');
insert into convert_octal_ascii values ('\302\234',null,156,'<control>');
insert into convert_octal_ascii values ('\302\235',null,157,'<control>');
insert into convert_octal_ascii values ('\302\236',null,158,'<control>');
insert into convert_octal_ascii values ('\302\237',null,159,'<control>');
insert into convert_octal_ascii values ('\302\240',null,160,'NO-BREAK SPACE');
insert into convert_octal_ascii values ('\302\241','¡',161,'INVERTED EXCLAMATION MARK');
insert into convert_octal_ascii values ('\302\242',null,162,'CENT SIGN');
insert into convert_octal_ascii values ('\302\243',null,163,'POUND SIGN');
insert into convert_octal_ascii values ('\302\244',null,164,'CURRENCY SIGN');
insert into convert_octal_ascii values ('\302\245',null,165,'YEN SIGN');
insert into convert_octal_ascii values ('\302\246',null,166,'BROKEN BAR');
insert into convert_octal_ascii values ('\302\247',null,167,'SECTION SIGN');
insert into convert_octal_ascii values ('\302\250',null,168,'DIAERESIS');
insert into convert_octal_ascii values ('\302\251',null,169,'COPYRIGHT SIGN');
insert into convert_octal_ascii values ('\302\252',null,170,'FEMININE ORDINAL INDICATOR');
insert into convert_octal_ascii values ('\302\253',null,171,'LEFT-POINTING DOUBLE ANGLE QUOTATION MARK');
insert into convert_octal_ascii values ('\302\254',null,172,'NOT SIGN');
insert into convert_octal_ascii values ('\302\255',null,173,'SOFT HYPHEN');
insert into convert_octal_ascii values ('\302\256',null,174,'REGISTERED SIGN');
insert into convert_octal_ascii values ('\302\257',null,175,'MACRON');
insert into convert_octal_ascii values ('\302\260',null,176,'DEGREE SIGN');
insert into convert_octal_ascii values ('\302\261',null,177,'PLUS-MINUS SIGN');
insert into convert_octal_ascii values ('\302\262',null,178,'SUPERSCRIPT TWO');
insert into convert_octal_ascii values ('\302\263',null,179,'SUPERSCRIPT THREE');
insert into convert_octal_ascii values ('\302\264',null,180,'ACUTE ACCENT');
insert into convert_octal_ascii values ('\302\265',null,181,'MICRO SIGN');
insert into convert_octal_ascii values ('\302\266',null,182,'PILCROW SIGN');
insert into convert_octal_ascii values ('\302\267',null,183,'MIDDLE DOT');
insert into convert_octal_ascii values ('\302\270',null,184,'CEDILLA');
insert into convert_octal_ascii values ('\302\271',null,185,'SUPERSCRIPT ONE');
insert into convert_octal_ascii values ('\302\272',null,186,'MASCULINE ORDINAL INDICATOR');
insert into convert_octal_ascii values ('\302\273',null,187,'RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK');
insert into convert_octal_ascii values ('\302\274',null,188,'VULGAR FRACTION ONE QUARTER');
insert into convert_octal_ascii values ('\302\275',null,189,'VULGAR FRACTION ONE HALF');
insert into convert_octal_ascii values ('\302\276',null,190,'VULGAR FRACTION THREE QUARTERS');
insert into convert_octal_ascii values ('\302\277','¿',191,'INVERTED QUESTION MARK');
insert into convert_octal_ascii values ('\303\200','A',192,'LATIN CAPITAL LETTER A WITH GRAVE');
insert into convert_octal_ascii values ('\303\201','A',193,'LATIN CAPITAL LETTER A WITH ACUTE');
insert into convert_octal_ascii values ('\303\202','A',194,'LATIN CAPITAL LETTER A WITH CIRCUMFLEX');
insert into convert_octal_ascii values ('\303\203','A',195,'LATIN CAPITAL LETTER A WITH TILDE');
insert into convert_octal_ascii values ('\303\204','A',196,'LATIN CAPITAL LETTER A WITH DIAERESIS');
insert into convert_octal_ascii values ('\303\205','A',197,'LATIN CAPITAL LETTER A WITH RING ABOVE');
insert into convert_octal_ascii values ('\303\206',null,198,'LATIN CAPITAL LETTER AE');
insert into convert_octal_ascii values ('\303\207',null,199,'LATIN CAPITAL LETTER C WITH CEDILLA');
insert into convert_octal_ascii values ('\303\210','E',200,'LATIN CAPITAL LETTER E WITH GRAVE');
insert into convert_octal_ascii values ('\303\211','E',201,'LATIN CAPITAL LETTER E WITH ACUTE');
insert into convert_octal_ascii values ('\303\212','E',202,'LATIN CAPITAL LETTER E WITH CIRCUMFLEX');
insert into convert_octal_ascii values ('\303\213','E',203,'LATIN CAPITAL LETTER E WITH DIAERESIS');
insert into convert_octal_ascii values ('\303\214','I',204,'LATIN CAPITAL LETTER I WITH GRAVE');
insert into convert_octal_ascii values ('\303\215','I',205,'LATIN CAPITAL LETTER I WITH ACUTE');
insert into convert_octal_ascii values ('\303\216','I',206,'LATIN CAPITAL LETTER I WITH CIRCUMFLEX');
insert into convert_octal_ascii values ('\303\217','I',207,'LATIN CAPITAL LETTER I WITH DIAERESIS');
insert into convert_octal_ascii values ('\303\220',null,208,'LATIN CAPITAL LETTER ETH');
insert into convert_octal_ascii values ('\303\221','N',209,'LATIN CAPITAL LETTER N WITH TILDE');
insert into convert_octal_ascii values ('\303\222','O',210,'LATIN CAPITAL LETTER O WITH GRAVE');
insert into convert_octal_ascii values ('\303\223','O',211,'LATIN CAPITAL LETTER O WITH ACUTE');
insert into convert_octal_ascii values ('\303\224','O',212,'LATIN CAPITAL LETTER O WITH CIRCUMFLEX');
insert into convert_octal_ascii values ('\303\225','O',213,'LATIN CAPITAL LETTER O WITH TILDE');
insert into convert_octal_ascii values ('\303\226','O',214,'LATIN CAPITAL LETTER O WITH DIAERESIS');
insert into convert_octal_ascii values ('\303\227',null,215,'MULTIPLICATION SIGN');
insert into convert_octal_ascii values ('\303\230',null,216,'LATIN CAPITAL LETTER O WITH STROKE');
insert into convert_octal_ascii values ('\303\231','U',217,'LATIN CAPITAL LETTER U WITH GRAVE');
insert into convert_octal_ascii values ('\303\232','U',218,'LATIN CAPITAL LETTER U WITH ACUTE');
insert into convert_octal_ascii values ('\303\233','U',219,'LATIN CAPITAL LETTER U WITH CIRCUMFLEX');
insert into convert_octal_ascii values ('\303\234','U',220,'LATIN CAPITAL LETTER U WITH DIAERESIS');
insert into convert_octal_ascii values ('\303\235',null,221,'LATIN CAPITAL LETTER Y WITH ACUTE');
insert into convert_octal_ascii values ('\303\236',null,222,'LATIN CAPITAL LETTER THORN');
insert into convert_octal_ascii values ('\303\237',null,223,'LATIN SMALL LETTER SHARP S');
insert into convert_octal_ascii values ('\303\240','a',224,'LATIN SMALL LETTER A WITH GRAVE');
insert into convert_octal_ascii values ('\303\241','a',225,'LATIN SMALL LETTER A WITH ACUTE');
insert into convert_octal_ascii values ('\303\242','a',226,'LATIN SMALL LETTER A WITH CIRCUMFLEX');
insert into convert_octal_ascii values ('\303\243','a',227,'LATIN SMALL LETTER A WITH TILDE');
insert into convert_octal_ascii values ('\303\244','a',228,'LATIN SMALL LETTER A WITH DIAERESIS');
insert into convert_octal_ascii values ('\303\245','a',229,'LATIN SMALL LETTER A WITH RING ABOVE');
insert into convert_octal_ascii values ('\303\246',null,230,'LATIN SMALL LETTER AE');
insert into convert_octal_ascii values ('\303\247',null,231,'LATIN SMALL LETTER C WITH CEDILLA');
insert into convert_octal_ascii values ('\303\250','e',232,'LATIN SMALL LETTER E WITH GRAVE');
insert into convert_octal_ascii values ('\303\251','e',233,'LATIN SMALL LETTER E WITH ACUTE');
insert into convert_octal_ascii values ('\303\252','e',234,'LATIN SMALL LETTER E WITH CIRCUMFLEX');
insert into convert_octal_ascii values ('\303\253','e',235,'LATIN SMALL LETTER E WITH DIAERESIS');
insert into convert_octal_ascii values ('\303\254','i',236,'LATIN SMALL LETTER I WITH GRAVE');
insert into convert_octal_ascii values ('\303\255','i',237,'LATIN SMALL LETTER I WITH ACUTE');
insert into convert_octal_ascii values ('\303\256','i',238,'LATIN SMALL LETTER I WITH CIRCUMFLEX');
insert into convert_octal_ascii values ('\303\257','i',239,'LATIN SMALL LETTER I WITH DIAERESIS');
insert into convert_octal_ascii values ('\303\260',null,240,'LATIN SMALL LETTER ETH');
insert into convert_octal_ascii values ('\303\261','ñ',241,'LATIN SMALL LETTER N WITH TILDE');
insert into convert_octal_ascii values ('\303\262','o',242,'LATIN SMALL LETTER O WITH GRAVE');
insert into convert_octal_ascii values ('\303\263','o',243,'LATIN SMALL LETTER O WITH ACUTE');
insert into convert_octal_ascii values ('\303\264','o',244,'LATIN SMALL LETTER O WITH CIRCUMFLEX');
insert into convert_octal_ascii values ('\303\265','o',245,'LATIN SMALL LETTER O WITH TILDE');
insert into convert_octal_ascii values ('\303\266','o',246,'LATIN SMALL LETTER O WITH DIAERESIS');
insert into convert_octal_ascii values ('\303\267','÷',247,'DIVISION SIGN');
insert into convert_octal_ascii values ('\303\270',null,248,'LATIN SMALL LETTER O WITH STROKE');
insert into convert_octal_ascii values ('\303\271','u',249,'LATIN SMALL LETTER U WITH GRAVE');
insert into convert_octal_ascii values ('\303\272','u',250,'LATIN SMALL LETTER U WITH ACUTE');
insert into convert_octal_ascii values ('\303\273','u',251,'LATIN SMALL LETTER U WITH CIRCUMFLEX');
insert into convert_octal_ascii values ('\303\274','u',252,'LATIN SMALL LETTER U WITH DIAERESIS');
insert into convert_octal_ascii values ('\303\275','y',253,'LATIN SMALL LETTER Y WITH ACUTE');
insert into convert_octal_ascii values ('\303\276',null,254,'LATIN SMALL LETTER THORN');
insert into convert_octal_ascii values ('\303\277','y',255,'LATIN SMALL LETTER Y WITH DIAERESIS');	
