--
-- PostgreSQL database dump
--
DROP table respuestas_soap;

CREATE TABLE respuestas_soap (
    tipo_tx character varying(50),
    respuesta character varying,
    file_wsdl character varying(50),
    file_xsd character varying(50),
    xml_error character varying,
    servicio character varying(5)
);
CREATE INDEX respuestas_soap_01 ON respuestas_soap USING btree (tipo_tx);

/********** BONO 3 **********/
INSERT INTO respuestas_soap VALUES ('cermensajeben', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:cermensajebenResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>   <extTipoAccion></extTipoAccion><CR>    <extMsgError1></extMsgError1><CR>    <extMsgError2></extMsgError2><CR>    </return><CR>  </ns1:cermensajebenResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>', 'cermensajeben.wsdl', 'cermensajeben_schema1.xsd', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:cermensajebenResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    </return><CR></ns1:cermensajebenResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>','BNO');

INSERT INTO respuestas_soap VALUES ('anulabonou', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:anulabonouResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    <extCodError></extCodError><CR>    <extMensajeError></extMensajeError><CR>   </return><CR>  </ns1:anulabonouResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>', 'anulabonou.wsdl', 'anulabonou_schema1.xsd', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:anulabonouResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    </return><CR></ns1:anulabonouResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>','BNO');

INSERT INTO respuestas_soap VALUES ('benrec', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:benrecResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    <extCodResBen></extCodResBen><CR>    <extMensajeError></extMensajeError><CR>   </return><CR>  </ns1:benrecResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>', 'benrec.wsdl', 'benrec_schema1.xsd', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:benrecResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    </return><CR></ns1:benrecResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>','BNO');

INSERT INTO respuestas_soap VALUES ('coptran', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:coptranResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    <extCodError></extCodError><CR>    <extMensajeError></extMensajeError><CR>    <extPlan></extPlan><CR>    <lstValores></lstValores><CR>   </return><CR>  </ns1:coptranResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>', 'coptran.wsdl', 'coptran_schema1.xsd', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:coptranResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    </return><CR></ns1:coptranResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>','BNO');
--INSERT INTO respuestas_soap VALUES ('coptran', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:coptranResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    <extCodError></extCodError><CR>    <extMensajeError></extMensajeError><CR>    <extPlan></extPlan><CR>    <extValorPrestacion></extValorPrestacion><CR>    <extAporteFinanciador></extAporteFinanciador><CR>    <extCopago></extCopago><CR>    <extInternoIsa></extInternoIsa><CR>   </return><CR>  </ns1:coptranResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>', 'coptran.wsdl', 'coptran_schema1.xsd', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:coptranResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    </return><CR></ns1:coptranResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>','BNO');

INSERT INTO respuestas_soap VALUES ('datosprest', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:datosprestResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    <extEstConvenio></extEstConvenio><CR>    <extNivel>0</extNivel><CR>    <extTipoPrestador></extTipoPrestador><CR>    <extCodEspecialidades></extCodEspecialidades><CR>    <extCodProfesiones></extCodProfesiones><CR>    <extAnosAntiguedad></extAnosAntiguedad><CR>   </return><CR>  </ns1:datosprestResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>', 'datosprest.wsdl', 'datosprest_schema1.xsd', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:datosprestResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    </return><CR></ns1:datosprestResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>','BNO');

INSERT INTO respuestas_soap VALUES ('infenrola', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:infenrolaResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    <extCodError></extCodError><CR>    <extMensajeError></extMensajeError><CR>   </return><CR>  </ns1:infenrolaResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>', 'infenrola.wsdl', 'infenrola_schema1.xsd', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:infenrolaResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    </return><CR></ns1:infenrolaResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>','BNO');

INSERT INTO respuestas_soap VALUES ('enrola', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:enrolaResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    <extValido></extValido><CR>    <extNombreComp></extNombreComp><CR>   </return><CR>  </ns1:enrolaResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>', 'enrola.wsdl', 'enrola_schema1.xsd', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:enrolaResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    </return><CR></ns1:enrolaResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>','BNO');

INSERT INTO respuestas_soap VALUES ('envbonis', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:envbonisResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    <extCodError></extCodError><CR>    <extMensajeError></extMensajeError><CR>   </return><CR>  </ns1:envbonisResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>', 'envbonis.wsdl', 'envbonis_schema1.xsd', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:envbonisResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    </return><CR></ns1:envbonisResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>','BNO');

INSERT INTO respuestas_soap VALUES ('envbono', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:envbonoResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    <extCodError></extCodError><CR>    <extMensajeError></extMensajeError><CR>   </return><CR>  </ns1:envbonoResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>', 'envbono.wsdl', 'envbono_schema1.xsd', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:envbonoResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    </return><CR></ns1:envbonoResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>','BNO');

INSERT INTO respuestas_soap VALUES ('leerutcotiz', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:leerutcotizResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    <extNomCotizante></extNomCotizante><CR>    <extCodError></extCodError><CR>    <extMensajeError></extMensajeError><CR>    <ExtCorrBenef></ExtCorrBenef><CR>    <extRutBeneficiario></extRutBeneficiario><CR>    <extApellidoPat></extApellidoPat><CR>    <extApellidoMat></extApellidoMat><CR>    <extNombres></extNombres><CR>    <extCodEstBen></extCodEstBen><CR>    <extDescEstado></extDescEstado><CR>   </return><CR>  </ns1:leerutcotizResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>', 'leerutcotiz.wsdl', 'leerutcotiz_schema1.xsd', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:leerutcotizResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    </return><CR></ns1:leerutcotizResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>','BNO');

INSERT INTO respuestas_soap VALUES ('prestpaquete', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:prestpaqueteResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    <extCodError></extCodError><CR>    <extMensajeError></extMensajeError><CR>    <extCodHomologo></extCodHomologo><CR>    <extItemHomologo></extItemHomologo><CR>    <extCantidad></extCantidad><CR>   </return><CR>  </ns1:prestpaqueteResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>', 'prestpaquete.wsdl', 'prestpaquete_schema1.xsd', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:prestpaqueteResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    </return><CR></ns1:prestpaqueteResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>','BNO');

INSERT INTO respuestas_soap VALUES ('valorvari', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:valorvariResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    <extCodError></extCodError><CR>    <extMensajeError></extMensajeError><CR>    <extPlan></extPlan><CR>    <ExtGlosa1></ExtGlosa1><CR>    <ExtGlosa2></ExtGlosa2><CR>    <ExtGlosa3></ExtGlosa3><CR>    <ExtGlosa4></ExtGlosa4><CR>    <ExtGlosa5></ExtGlosa5><CR>    <extValorPrestacion></extValorPrestacion><CR>    <extAporteFinanciador></extAporteFinanciador><CR>    <extCopago></extCopago><CR>    <extInternoIsa></extInternoIsa><CR>    <ExtTipoBonif1></ExtTipoBonif1><CR>    <ExtCopago1></ExtCopago1><CR>    <ExtTipoBonif2></ExtTipoBonif2><CR>    <ExtCopago2></ExtCopago2><CR>    <ExtTipoBonif3></ExtTipoBonif3><CR>    <ExtCopago3></ExtCopago3><CR>    <ExtTipoBonif4></ExtTipoBonif4><CR>    <ExtCopago4></ExtCopago4><CR>    <ExtTipoBonif5></ExtTipoBonif5><CR>    <ExtCopago5></ExtCopago5><CR>   </return><CR>  </ns1:valorvariResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>', 'valorvari.wsdl', 'valorvari_schema1.xsd', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:valorvariResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    </return><CR></ns1:valorvariResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>','BNO');

INSERT INTO respuestas_soap VALUES ('valtrans', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:valtransResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>   <extRespuesta></extRespuesta><CR>    <extCodError></extCodError><CR>    <extMensajeError></extMensajeError><CR>    </return><CR>  </ns1:valtransResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>', 'valtrans.wsdl', 'valtrans_schema1.xsd', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:valtransResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    </return><CR></ns1:valtransResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>','BNO');

INSERT INTO respuestas_soap VALUES ('validacat', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:validacatResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    <extRespuestaCAT></extRespuestaCAT><CR>    <extMensajeCAT></extMensajeCAT><CR>   </return><CR>  </ns1:validacatResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>', 'validacat.wsdl', 'validacat_schema1.xsd', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:validacatResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    </return><CR></ns1:validacatResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>','BNO');

INSERT INTO respuestas_soap VALUES ('solicfolios', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:solicfoliosResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    <extCodError></extCodError><CR>    <extMensajeError></extMensajeError><CR>    <exFoliosDevueltos></exFoliosDevueltos><CR>   </return><CR>  </ns1:solicfoliosResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>', 'solicfolios.wsdl', 'solicfolios_schema1.xsd', '<?xml version="2.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:solicfoliosResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    </return><CR></ns1:solicfoliosResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>','BNO');

INSERT INTO respuestas_soap VALUES ('bencertif', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:bencertifResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    <extApellidoPat></extApellidoPat><CR>    <extApellidoMat></extApellidoMat><CR>    <extNombres></extNombres><CR>    <extSexo></extSexo><CR>    <extFechaNacimi></extFechaNacimi><CR>    <extCodEstBen></extCodEstBen><CR>    <extDescEstado></extDescEstado><CR>    <extRutCotizante></extRutCotizante><CR>    <extNomCotizante></extNomCotizante><CR>    <extDirPaciente></extDirPaciente><CR>    <extGlosaComuna></extGlosaComuna><CR>    <extGlosaCiudad></extGlosaCiudad><CR>    <extPrevision></extPrevision><CR>    <extGlosa></extGlosa><CR>    <extPlan></extPlan><CR>    <extDescuentoxPlanilla></extDescuentoxPlanilla><CR>    <extMontoExcedente>0</extMontoExcedente><CR>    <extRutAcompanante></extRutAcompanante><CR>    <extNombreAcompanante></extNombreAcompanante><CR>   </return><CR>  </ns1:bencertifResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>', 'bencertif.wsdl', 'bencertif_schema1.xsd', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:bencertifResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    </return><CR></ns1:bencertifResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>','BNO');

INSERT INTO respuestas_soap VALUES ('valorizi', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:valoriziResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    <extCodError></extCodError><CR>    <extMensajeError></extMensajeError><CR>    <extPlan></extPlan><CR>    <ExtGlosa1></ExtGlosa1><CR>    <ExtGlosa2></ExtGlosa2><CR>    <ExtGlosa3></ExtGlosa3><CR>    <ExtGlosa4></ExtGlosa4><CR>    <ExtGlosa5></ExtGlosa5><CR>    <extValorPrestacion></extValorPrestacion><CR>    <extAporteFinanciador></extAporteFinanciador><CR>    <extCopago></extCopago><CR>    <extInternoIsa></extInternoIsa><CR>    <ExtTipoBonif1></ExtTipoBonif1><CR>    <ExtCopago1></ExtCopago1><CR>    <ExtTipoBonif2></ExtTipoBonif2><CR>    <ExtCopago2></ExtCopago2><CR>    <ExtTipoBonif3></ExtTipoBonif3><CR>    <ExtCopago3></ExtCopago3><CR>    <ExtTipoBonif4></ExtTipoBonif4><CR>    <ExtCopago4></ExtCopago4><CR>    <ExtTipoBonif5></ExtTipoBonif5><CR>    <ExtCopago5></ExtCopago5><CR>   </return><CR>  </ns1:valoriziResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>', 'valorizi.wsdl', 'valorizi_schema1.xsd', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:valoriziResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    </return><CR></ns1:valoriziResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>','BNO');

INSERT INTO respuestas_soap VALUES ('envbonis_real', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:envbonisResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    <extCodError></extCodError><CR>    <extMensajeError></extMensajeError><CR>   </return><CR>  </ns1:envbonisResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>', 'envbonis.wsdl', 'envbonis_schema1.xsd', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:envbonisResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    </return><CR></ns1:envbonisResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>', 'BNO');

INSERT INTO respuestas_soap VALUES ('envbono_real', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:envbonoResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    <extCodError></extCodError><CR>    <extMensajeError></extMensajeError><CR>   </return><CR>  </ns1:envbonoResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>', 'envbono.wsdl', 'envbono_schema1.xsd', '<?xml version="1.0" encoding="UTF-8"?><CR><SOAP-ENV:Envelope<CR> xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"<CR> xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"<CR> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"<CR> xmlns:xsd="http://www.w3.org/2001/XMLSchema"<CR> xmlns:ns1="http://ws.imed.bono3.motor.com/"><CR> <SOAP-ENV:Body><CR>  <ns1:envbonoResponse><CR>   <return><CR>    <errorCod></errorCod><CR>    <errorMsg></errorMsg><CR>    </return><CR></ns1:envbonoResponse><CR> </SOAP-ENV:Body><CR></SOAP-ENV:Envelope>', 'BNO');


--Respuesta para la confirmacion de las cias_seguros
INSERT INTO respuestas_soap VALUES ('CONFIRMACION_CIA_SEGURO', '<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://tempuri.org/"><SOAP-ENV:Body><ns1:wmImed_SrvConfirmacionResponse><ns1:wmImed_SrvConfirmacionResult>&-&DATA&-&</ns1:wmImed_SrvConfirmacionResult></ns1:wmImed_SrvConfirmacionResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>', NULL, NULL, NULL, NULL);
INSERT INTO respuestas_soap VALUES ('CONFIRMACIONBONO3_CIA_SEGURO', '<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://tempuri.org/"><SOAP-ENV:Body><ns1:wmImed_SrvConfirmacionResponse><ns1:wmImed_SrvConfirmacionResult>&-&DATA&-&</ns1:wmImed_SrvConfirmacionResult></ns1:wmImed_SrvConfirmacionResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>', NULL, NULL, NULL, NULL);
INSERT INTO respuestas_soap VALUES ('CONFIRMACIONBONOEXT_CIA_SEGURO', '<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://tempuri.org/"><SOAP-ENV:Body><ns1:wmImed_SrvConfirmacionResponse><ns1:wmImed_SrvConfirmacionResult>&-&DATA&-&</ns1:wmImed_SrvConfirmacionResult></ns1:wmImed_SrvConfirmacionResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>', NULL, NULL, NULL, NULL);
INSERT INTO respuestas_soap VALUES ('ANULACION_CIA_SEGURO', '<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://tempuri.org/"><SOAP-ENV:Body><ns1:wmImed_SrvAnulacionResponse><ns1:wmImed_SrvAnulacionResult>&-&DATA&-&</ns1:wmImed_SrvAnulacionResult></ns1:wmImed_SrvAnulacionResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>', NULL, NULL, NULL, NULL);

INSERT INTO respuestas_soap VALUES ('ANULACIONBONO3_CIA_SEGURO', '<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://tempuri.org/"><SOAP-ENV:Body><ns1:wmImed_SrvAnulacionResponse><ns1:wmImed_SrvAnulacionResult>&-&DATA&-&</ns1:wmImed_SrvAnulacionResult></ns1:wmImed_SrvAnulacionResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>', NULL, NULL, NULL, NULL);
INSERT INTO respuestas_soap VALUES ('ANULACIONBONOEXT_CIA_SEGURO', '<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://tempuri.org/"><SOAP-ENV:Body><ns1:wmImed_SrvAnulacionResponse><ns1:wmImed_SrvAnulacionResult>&-&DATA&-&</ns1:wmImed_SrvAnulacionResult></ns1:wmImed_SrvAnulacionResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>', NULL, NULL, NULL, NULL);

INSERT INTO respuestas_soap VALUES ('CONCILIACION_CIA_SEGURO', '<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://tempuri.org/"><SOAP-ENV:Body><ns1:wmImed_SrvConciliacionResponse><ns1:wmImed_SrvConciliacionResult>&-&DATA&-&</ns1:wmImed_SrvConciliacionResult></ns1:wmImed_SrvConciliacionResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>', NULL, NULL, NULL, NULL);
INSERT INTO respuestas_soap VALUES ('CERTIFICACION_CIA_SEGURO', '<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://tempuri.org/"><SOAP-ENV:Body><ns1:wmImed_SrvCertificacionResponse><ns1:wmImed_SrvCertificacionResult>&-&DATA&-&</ns1:wmImed_SrvCertificacionResult></ns1:wmImed_SrvCertificacionResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>', NULL, NULL, NULL, NULL);

INSERT INTO respuestas_soap VALUES ('CONFIRMACIONBONOEXT_CIA_SEGURO', '<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://tempuri.org/"><SOAP-ENV:Body><ns1:wmImed_SrvConfirmacionResponse><ns1:wmImed_SrvConfirmacionResult>&-&DATA&-&</ns1:wmImed_SrvConfirmacionResult></ns1:wmImed_SrvConfirmacionResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>', NULL, NULL, NULL, NULL);
INSERT INTO respuestas_soap VALUES ('ANULACIONBONOEXT_CIA_SEGURO', '<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://tempuri.org/"><SOAP-ENV:Body><ns1:wmImed_SrvAnulacionResponse><ns1:wmImed_SrvAnulacionResult>&-&DATA&-&</ns1:wmImed_SrvAnulacionResult></ns1:wmImed_SrvAnulacionResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>', NULL, NULL, NULL, NULL);

--Respuestas Liquidador Imed
INSERT INTO respuestas_soap VALUES ('WsLiquidador', '<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://tempuri.org/"><SOAP-ENV:Body><ns1:wmImed_SrvCertificacionResponse><ns1:wmImed_SrvCertificacionResult>&-&DATA&-&</ns1:wmImed_SrvCertificacionResult></ns1:wmImed_SrvCertificacionResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>', NULL, NULL, NULL, NULL);

--
-- PostgreSQL database dump complete
--

