<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions name="CERMENSAJEBENService" targetNamespace="http://ws.imed.bono3.motor.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ws.imed.bono3.motor.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ws.imed.bono3.motor.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<import namespace="http://ws.imed.bono3.motor.com/" schemaLocation="http://$$LOCATION$$/WSIMedBono/services/CERMENSAJEBENPort?xsd=cermensajeben_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="cermensajeben">
    <wsdl:part element="tns:cermensajeben" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="cermensajebenResponse">
    <wsdl:part element="tns:cermensajebenResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="CERMENSAJEBENSEI">
    <wsdl:operation name="cermensajeben">
      <wsdl:input message="tns:cermensajeben" name="cermensajeben">
    </wsdl:input>
      <wsdl:output message="tns:cermensajebenResponse" name="cermensajebenResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="CERMENSAJEBENServiceSoapBinding" type="tns:CERMENSAJEBENSEI">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="cermensajeben">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="cermensajeben">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="cermensajebenResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CERMENSAJEBENService">
    <wsdl:port binding="tns:CERMENSAJEBENServiceSoapBinding" name="CERMENSAJEBENPort">
      <soap:address location="http://$$LOCATION$$/WSIMedBono/services/CERMENSAJEBENPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
