<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions name="INFENROLAService" targetNamespace="http://ws.imed.bono3.motor.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ws.imed.bono3.motor.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ws.imed.bono3.motor.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<import namespace="http://ws.imed.bono3.motor.com/" schemaLocation="http://$$LOCATION$$/WSIMedBono/services/INFENROLAPort?xsd=infenrola_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="infenrolaResponse">
    <wsdl:part element="tns:infenrolaResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="infenrola">
    <wsdl:part element="tns:infenrola" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="INFENROLASEI">
    <wsdl:operation name="infenrola">
      <wsdl:input message="tns:infenrola" name="infenrola">
    </wsdl:input>
      <wsdl:output message="tns:infenrolaResponse" name="infenrolaResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="INFENROLAServiceSoapBinding" type="tns:INFENROLASEI">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="infenrola">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="infenrola">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="infenrolaResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="INFENROLAService">
    <wsdl:port binding="tns:INFENROLAServiceSoapBinding" name="INFENROLAPort">
      <soap:address location="http://$$LOCATION$$/WSIMedBono/services/INFENROLAPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
