<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="WsLogsMotor" targetNamespace="http://ws.imed.bono3.motor.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ws.imed.bono3.motor.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ws.imed.bono3.motor.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<import namespace="http://ws.imed.bono3.motor.com/" schemaLocation="http://$$LOCATION$$/WsLogsMotor/LogAnulaBonoU?xsd=log_motor_anulabonou_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="loganulabonouResponse">
    <wsdl:part element="tns:loganulabonouResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="loganulabonou">
    <wsdl:part element="tns:loganulabonou" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="LOGANULABONOUSEI">
    <wsdl:operation name="loganulabonou">
      <wsdl:input message="tns:loganulabonou" name="loganulabonou">
    </wsdl:input>
      <wsdl:output message="tns:loganulabonouResponse" name="loganulabonouResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="LOGANULABONOUServiceSoapBinding" type="tns:LOGANULABONOUSEI">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="loganulabonou">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="loganulabonou">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="loganulabonouResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="LOGANULABONOUService">
    <wsdl:port binding="tns:LOGANULABONOUServiceSoapBinding" name="LOGANULABONOU">
      <soap:address location="http://$$LOCATION$$/WsLogsMotor/LogAnulaBonoU"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
