<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="WsMultiCaja" targetNamespace="http://ws.imed.bono3.motor.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ws.imed.bono3.motor.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ws.imed.bono3.motor.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<import namespace="http://ws.imed.bono3.motor.com/" schemaLocation="http://$$LOCATION$$/WsMultiCaja/ImedReimpresion?xsd=multicaja_reimpresion_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="imedreimpresion">
    <wsdl:part element="tns:imedreimpresion" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="imedreimpresionResponse">
    <wsdl:part element="tns:imedreimpresionResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="IMEDREIMPRESIONSEI">
    <wsdl:operation name="imedreimpresion">
      <wsdl:input message="tns:imedreimpresion" name="imedreimpresion">
    </wsdl:input>
      <wsdl:output message="tns:imedreimpresionResponse" name="imedreimpresionResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="IMEDREIMPRESIONServiceSoapBinding" type="tns:IMEDREIMPRESIONSEI">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="imedreimpresion">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="imedreimpresion">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="imedreimpresionResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="IMEDREIMPRESIONService">
    <wsdl:port binding="tns:IMEDREIMPRESIONServiceSoapBinding" name="IMEDREIMPRESION">
      <soap:address location="http://$$LOCATION$$/WsMultiCaja/ImedReimpresion"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
