<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions name="VALORVARIService" targetNamespace="http://ws.imed.bono3.motor.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ws.imed.bono3.motor.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ws.imed.bono3.motor.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<import namespace="http://ws.imed.bono3.motor.com/" schemaLocation="http://$$LOCATION$$/WSIMedBono/services/VALORVARIPort?xsd=valorvari_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="valorvariResponse">
    <wsdl:part element="tns:valorvariResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="valorvari">
    <wsdl:part element="tns:valorvari" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="VALORVARISEI">
    <wsdl:operation name="valorvari">
      <wsdl:input message="tns:valorvari" name="valorvari">
    </wsdl:input>
      <wsdl:output message="tns:valorvariResponse" name="valorvariResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="VALORVARIServiceSoapBinding" type="tns:VALORVARISEI">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="valorvari">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="valorvari">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="valorvariResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="VALORVARIService">
    <wsdl:port binding="tns:VALORVARIServiceSoapBinding" name="VALORVARIPort">
      <soap:address location="http://$$LOCATION$$/WSIMedBono/services/VALORVARIPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
