
DIR='/home/isys/base/bono3/SANLORENZO/sp_oracle/'
SQLPLUS='/home/isys/instantclient_11_2/sqlplus'
HOST='192.168.220.13'
PORT='1521'
USR='ADMIMED'
USR1='ADMIMED_CONV'
PWD='ADMIMED'
SID='IFUSAT'

#/home/isys/instantclient_11_2/sqlplus ADMIMED/ADMIMED@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.220.13)(PORT=1521))(CONNECT_DATA=(SID=ISNLAT)))"
#/home/isys/instantclient_11_2/sqlplus $USR/$PWD"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))"
#SELECT OBJECT_NAME,OBJECT_TYPE,OWNER FROM ALL_OBJECTS ORDER BY OBJECT_TYPE asc;

#cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/modelo_db.txt
#SET PAGESIZE 999 LINESIZE 999;
#SELECT OBJECT_NAME,OBJECT_TYPE,OWNER FROM ALL_OBJECTS ORDER BY OBJECT_NAME asc;
#EOT
#cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/all_all_table.txt
#SET PAGESIZE 999 LINESIZE 999;
#select * from ALL_ALL_TABLES order by TABLE_NAME asc;
#EOT
#cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/procedure.txt
#SET PAGESIZE 999 LINESIZE 999;
#select OBJECT_NAME,PROCEDURE_NAME,OBJECT_TYPE,OWNER from ALL_PROCEDURES order by PROCEDURE_NAME;
#EOT
########################################################################################################################################################

cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/SNLANULABONOU_PKG.sql
SET PAGESIZE 999 LINESIZE 999;
desc SNLANULABONOU_PKG
EOT
cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/SNLANULABONOU_PKG_BODY.sql
SET PAGESIZE 999 LINESIZE 999;
SELECT text from all_source where name ='SNLANULABONOU_PKG' and type in('PACKAGE BODY') and OWNER='ADMIMED_CONV' order by line asc;
EOT

cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/SNLBENCERTIF_PKG.sql
SET PAGESIZE 999 LINESIZE 999;
desc SNLBENCERTIF_PKG
EOT
cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/SNLBENCERTIF_PKG_BODY.sql
SET PAGESIZE 999 LINESIZE 999;
SELECT text from all_source where name ='SNLBENCERTIF_PKG' and type in('PACKAGE BODY') and OWNER='ADMIMED_CONV' order by line asc;
EOT

##cat <<EOT | tsql -H $HOST -p $PORT -U $USR -P $PWD > $DIR/CGCBenRec.sql
##desc CGCBenRec
#EOT
##cat <<EOT | tsql -H $HOST -p $PORT -U $USR -P $PWD > $DIR/CGCDatosPrest.sql
##desc CGCDatosPrest
#EOT

cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/SNLENROLA_PKG.sql
SET PAGESIZE 999 LINESIZE 999;
desc SNLENROLA_PKG
EOT
cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/SNLENROLA_PKG_BODY.sql
SET PAGESIZE 999 LINESIZE 999;
SELECT text from all_source where name ='SNLENROLA_PKG' and type in('PACKAGE BODY') and OWNER='ADMIMED_CONV' order by line asc;
EOT

#select text from all_source where name = 'SNLENVBONIS_PKG' and type in('PACKAGE','SYNONYM') order by line asc;
cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/SNLENVBONIS_PKG.sql
SET PAGESIZE 999 LINESIZE 999;
desc SNLENVBONIS_PKG
EOT
cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/SNLENVBONIS_PKG_BODY.sql
SET PAGESIZE 999 LINESIZE 999;
SELECT text from all_source where name = 'SNLENVBONIS_PKG' and type in('PACKAGE BODY') and OWNER='ADMIMED_CONV' order by line asc;
EOT

#cat <<EOT | tsql -H $HOST -p $PORT -U $USR -P $PWD > $DIR/MASenvBono.sql
#desc MASenvBono
#EOT

cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/SNLLEERUTCOTIZ_PKG.sql
SET PAGESIZE 999 LINESIZE 999;
DESC SNLLEERUTCOTIZ_PKG
EOT
cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/SNLLEERUTCOTIZ_PKG_BODY.sql
SET PAGESIZE 999 LINESIZE 999;
SELECT text from all_source where name ='SNLLEERUTCOTIZ_PKG' and type in('PACKAGE BODY') and OWNER='ADMIMED_CONV' order by line asc;
EOT

#cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/SNLPRESTPAQUETE_PKG.sql
#SET PAGESIZE 999 LINESIZE 999;
#select text from all_source where name = 'SNLPRESTPAQUETE_PKG' and type in('PACKAGE','SYNONYM') order by line asc;
#EOT

cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/SNLSOLICFOLIOS_PKG.sql
SET PAGESIZE 999 LINESIZE 999;
desc SNLSOLICFOLIOS_PKG
EOT
cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/SNLSOLICFOLIOS_PKG_BODY.sql
SET PAGESIZE 999 LINESIZE 999;
SELECT text from all_source where name ='SNLSOLICFOLIOS_PKG' and type in('PACKAGE BODY') and OWNER='ADMIMED_CONV' order by line asc;
EOT

cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/SNLVALORVARI_PKG.sql
SET PAGESIZE 999 LINESIZE 999;
desc SNLVALORVARI_PKG
EOT
cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/SNLVALORVARI_PKG_BODY.sql
SET PAGESIZE 999 LINESIZE 999;
SELECT text from all_source where name ='SNLVALORVARI_PKG' and type in('PACKAGE BODY') and OWNER='ADMIMED_CONV' order by line asc;
EOT

#cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/SNLVALIDACAT_PKG.sql
#SET PAGESIZE 999 LINESIZE 999;
#select text from all_source where name = 'SNLVALIDACAT_PKG' and type in('PACKAGE','SYNONYM') order by line asc;
#EOT

#cat <<EOT | tsql -H $HOST -p $PORT -U $USR -P $PWD > $DIR/MASValidaCAt.sql
#desc MASValidaCAt
#EOT
#cat <<EOT | tsql -H $HOST -p $PORT -U $USR -P $PWD > $DIR/MASValorizI.sql
#desc MASValorizI
#EOT

cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/SNLVALTRANS_PKG.sql
SET PAGESIZE 999 LINESIZE 999;
desc SNLVALTRANS_PKG
EOT

cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/SNLVALTRANS_PKG_BODY.sql
SET PAGESIZE 999 LINESIZE 999;
SELECT text from all_source where name ='SNLVALTRANS_PKG' and type in('PACKAGE BODY') and OWNER='ADMIMED_CONV' order by line asc;
EOT
#cat <<EOT | $SQLPLUS $USR/$PWD@"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=$HOST)(PORT=$PORT))(CONNECT_DATA=(SID=$SID)))" > $DIR/SNLMENSAJEBEN_PKG.sql
#SET PAGESIZE 999 LINESIZE 999;
#select text from all_source where name = 'SNLMENSAJEBEN_PKG' and type in('PACKAGE','SYNONYM') order by line asc;
#EOT

