FECHA=$(date +%Y%m%d%H)
FECHA_ORACLE=$(date +%Y%m%d)
echo $FECHA

touch /home/motor/BNO_FONASA/$FECHA"_API.LOG" /home/motor/BNO_CCHC/$FECHA"_API.LOG" /home/motor/BNO_VIDACAMARA/$FECHA"_API.LOG" /home/motor/BNO_FUSAT/$FECHA_ORACLE"_PYT.LOG" /home/motor/BNO_COLMENA/$FECHA"_API.LOG" /home/motor/BNO_CONSALUD/$FECHA_ORACLE"_PYT.LOG" /home/motor/BNO_FUNDACION/$FECHA_ORACLE"_PYT.LOG" /home/motor/BNO_CRUZBLANCA/$FECHA"_API.LOG" /home/motor/BNO_FERROSALUD/$FECHA"_API.LOG" /home/motor/BNO_MASVIDA/$FECHA"_API.LOG" /home/motor/BNO_CRUZDELNORTE/$FECHA_ORACLE"_PYT.LOG" /home/motor/BNO_BANMEDICA/$FECHA_ORACLE"_PYT.LOG" 

tail -f /home/motor/BNO_FONASA/$FECHA"_API.LOG" /home/motor/BNO_CCHC/$FECHA"_API.LOG" /home/motor/BNO_VIDACAMARA/$FECHA"_API.LOG" /home/motor/BNO_FUSAT/$FECHA_ORACLE"_PYT.LOG" /home/motor/BNO_COLMENA/$FECHA"_API.LOG" /home/motor/BNO_CONSALUD/$FECHA_ORACLE"_PYT.LOG" /home/motor/BNO_FUNDACION/$FECHA_ORACLE"_PYT.LOG" /home/motor/BNO_CRUZBLANCA/$FECHA"_API.LOG" /home/motor/BNO_FERROSALUD/$FECHA"_API.LOG" /home/motor/BNO_MASVIDA/$FECHA"_API.LOG" /home/motor/BNO_CRUZDELNORTE/$FECHA_ORACLE"_PYT.LOG" /home/motor/BNO_BANMEDICA/$FECHA_ORACLE"_PYT.LOG" 

#exit 1;
