
SQL*Plus: Release 11.2.0.3.0 Production on Wed Sep 25 11:58:27 2013

Copyright (c) 1982, 2011, Oracle.  All rights reserved.


Connected to:
Oracle Database 10g Enterprise Edition Release 10.2.0.5.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options

SQL> SQL> PROCEDURE CONBENCERTIF
 Argument Name			Type			In/Out Default?
 ------------------------------ ----------------------- ------ --------
 SRV_MESSAGE			VARCHAR2		IN/OUT
 IN_NEXTCODFINANCIADOR		NUMBER			IN
 IN_NEXTRUTBENEFICIARIO 	VARCHAR2		IN
 IN_VEXTFECHAACTUAL		VARCHAR2		IN
 OUT_VEXTAPELLIDOPAT		VARCHAR2		OUT
 OUT_VEXTAPELLIDOMAT		VARCHAR2		OUT
 OUT_VEXTNOMBRES		VARCHAR2		OUT
 OUT_VEXTSEXO			VARCHAR2		OUT
 OUT_DEXTFECHANACIMI		VARCHAR2		OUT
 OUT_VEXTCODESTBEN		VARCHAR2		OUT
 OUT_VEXTDESCESTADO		VARCHAR2		OUT
 OUT_VEXTRUTCOTIZANTE		VARCHAR2		OUT
 OUT_VEXTNOMCOTIZANTE		VARCHAR2		OUT
 OUT_VEXTDIRPACIENTE		VARCHAR2		OUT
 OUT_VEXTGLOSACOMUNA		VARCHAR2		OUT
 OUT_VEXTGLOSACIUDAD		VARCHAR2		OUT
 OUT_VEXTPREVISION		VARCHAR2		OUT
 OUT_VEXTGLOSA			VARCHAR2		OUT
 OUT_VEXTPLAN			VARCHAR2		OUT
 OUT_VEXTDESCUENTOXPLANILLA	VARCHAR2		OUT
 OUT_NEXTMONTOEXCEDENTE 	NUMBER			OUT
 COL_VEXTRUTACOMPANANTE 	TABLE OF VARCHAR2(12)	OUT
 COL_VEXTNOMBREACOMPANANTE	TABLE OF VARCHAR2(40)	OUT

SQL> Disconnected from Oracle Database 10g Enterprise Edition Release 10.2.0.5.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options
