
SQL*Plus: Release 11.2.0.3.0 Production on Wed Sep 25 11:58:28 2013

Copyright (c) 1982, 2011, Oracle.  All rights reserved.


Connected to:
Oracle Database 10g Enterprise Edition Release 10.2.0.5.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options

SQL> SQL> PROCEDURE CONVALORIZI
 Argument Name			Type			In/Out Default?
 ------------------------------ ----------------------- ------ --------
 SRV_MESSAGE			VARCHAR2		IN/OUT
 IN_NEXTCODFINANCIADOR		NUMBER			IN
 IN_VEXTHOMNUMEROCONVENIO	VARCHAR2		IN
 IN_VEXTHOMLUGARCONVENIO	VARCHAR2		IN
 IN_VEXTSUCVENTA		VARCHAR2		IN
 IN_VEXTRUTCONVENIO		VARCHAR2		IN
 IN_VEXTRUTTRATANTE		VARCHAR2		IN
 IN_VEXTESPECIALIDAD		VARCHAR2		IN
 IN_VEXTRUTSOLICITANTE		VARCHAR2		IN
 IN_VEXTRUTBENEFICIARIO 	VARCHAR2		IN
 IN_VEXTTRATAMIENTO		VARCHAR2		IN
 IN_VEXTCODIGODIAGNOSTICO	VARCHAR2		IN
 IN_NEXTNIVELCONVENIO		NUMBER			IN
 IN_VEXTURGENCIA		VARCHAR2		IN
 IN_VEXTLISTA1			VARCHAR2		IN
 IN_VEXTLISTA2			VARCHAR2		IN
 IN_VEXTLISTA3			VARCHAR2		IN
 IN_VEXTLISTA4			VARCHAR2		IN
 IN_VEXTLISTA5			VARCHAR2		IN
 IN_VEXTLISTA6			VARCHAR2		IN
 IN_NEXTNUMPRESTACIONES 	NUMBER			IN
 OUT_VEXTCODERROR		VARCHAR2		OUT
 OUT_VEXTMENSAJEERROR		VARCHAR2		OUT
 OUT_VEXTPLAN			VARCHAR2		OUT
 OUT_VEXTGLOSA1 		VARCHAR2		OUT
 OUT_VEXTGLOSA2 		VARCHAR2		OUT
 OUT_VEXTGLOSA3 		VARCHAR2		OUT
 OUT_VEXTGLOSA4 		VARCHAR2		OUT
 OUT_VEXTGLOSA5 		VARCHAR2		OUT
 COL_NEXTVALORPRESTACION	TABLE OF NUMBER(12)	OUT
 COL_NEXTAPORTEFINANCIADOR	TABLE OF NUMBER(12)	OUT
 COL_NEXTCOPAGO 		TABLE OF NUMBER(12)	OUT
 COL_VEXTINTERNOLSA		TABLE OF VARCHAR2(15)	OUT
 COL_NEXTTIPOBONIF1		TABLE OF NUMBER(1)	OUT
 COL_NEXTCOPAGO1		TABLE OF NUMBER(12)	OUT
 COL_NEXTTIPOBONIF2		TABLE OF NUMBER(1)	OUT
 COL_NEXTCOPAGO2		TABLE OF NUMBER(12)	OUT
 COL_NEXTTIPOBONIF3		TABLE OF NUMBER(1)	OUT
 COL_NEXTCOPAGO3		TABLE OF NUMBER(12)	OUT
 COL_NEXTTIPOBONIF4		TABLE OF NUMBER(1)	OUT
 COL_NEXTCOPAGO4		TABLE OF NUMBER(12)	OUT
 COL_NEXTTIPOBONIF5		TABLE OF NUMBER(1)	OUT
 COL_NEXTCOPAGO5		TABLE OF NUMBER(12)	OUT
FUNCTION EMBE_REDONDEO RETURNS NUMBER
 Argument Name			Type			In/Out Default?
 ------------------------------ ----------------------- ------ --------
 N_VALOR_I			NUMBER			IN

SQL> Disconnected from Oracle Database 10g Enterprise Edition Release 10.2.0.5.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options
