/* soapServer.cpp
   Generated by gSOAP 2.8.14 from cruzblanca.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.cpp ver 2.8.14 2015-02-18 20:47:17 GMT")


extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:Certificacion"))
		return soap_serve___ns1__Certificacion(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:Confirmacion"))
		return soap_serve___ns1__Confirmacion(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:Anulacion"))
		return soap_serve___ns1__Anulacion(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:Conciliacion"))
		return soap_serve___ns1__Conciliacion(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:Certificacion"))
		return soap_serve___ns1__Certificacion_(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:Confirmacion"))
		return soap_serve___ns1__Confirmacion_(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:Anulacion"))
		return soap_serve___ns1__Anulacion_(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:Conciliacion"))
		return soap_serve___ns1__Conciliacion_(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__Certificacion(struct soap *soap)
{	struct __ns1__Certificacion soap_tmp___ns1__Certificacion;
	_ns1__CertificacionResponse ns1__CertificacionResponse;
	ns1__CertificacionResponse.soap_default(soap);
	soap_default___ns1__Certificacion(soap, &soap_tmp___ns1__Certificacion);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__Certificacion(soap, &soap_tmp___ns1__Certificacion, "-ns1:Certificacion", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__Certificacion(soap, soap_tmp___ns1__Certificacion.ns1__Certificacion, &ns1__CertificacionResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__CertificacionResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__CertificacionResponse.soap_put(soap, "ns1:CertificacionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__CertificacionResponse.soap_put(soap, "ns1:CertificacionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__Confirmacion(struct soap *soap)
{	struct __ns1__Confirmacion soap_tmp___ns1__Confirmacion;
	_ns1__ConfirmacionResponse ns1__ConfirmacionResponse;
	ns1__ConfirmacionResponse.soap_default(soap);
	soap_default___ns1__Confirmacion(soap, &soap_tmp___ns1__Confirmacion);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__Confirmacion(soap, &soap_tmp___ns1__Confirmacion, "-ns1:Confirmacion", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__Confirmacion(soap, soap_tmp___ns1__Confirmacion.ns1__Confirmacion, &ns1__ConfirmacionResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ConfirmacionResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ConfirmacionResponse.soap_put(soap, "ns1:ConfirmacionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ConfirmacionResponse.soap_put(soap, "ns1:ConfirmacionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__Anulacion(struct soap *soap)
{	struct __ns1__Anulacion soap_tmp___ns1__Anulacion;
	_ns1__AnulacionResponse ns1__AnulacionResponse;
	ns1__AnulacionResponse.soap_default(soap);
	soap_default___ns1__Anulacion(soap, &soap_tmp___ns1__Anulacion);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__Anulacion(soap, &soap_tmp___ns1__Anulacion, "-ns1:Anulacion", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__Anulacion(soap, soap_tmp___ns1__Anulacion.ns1__Anulacion, &ns1__AnulacionResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__AnulacionResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__AnulacionResponse.soap_put(soap, "ns1:AnulacionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__AnulacionResponse.soap_put(soap, "ns1:AnulacionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__Conciliacion(struct soap *soap)
{	struct __ns1__Conciliacion soap_tmp___ns1__Conciliacion;
	_ns1__ConciliacionResponse ns1__ConciliacionResponse;
	ns1__ConciliacionResponse.soap_default(soap);
	soap_default___ns1__Conciliacion(soap, &soap_tmp___ns1__Conciliacion);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__Conciliacion(soap, &soap_tmp___ns1__Conciliacion, "-ns1:Conciliacion", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__Conciliacion(soap, soap_tmp___ns1__Conciliacion.ns1__Conciliacion, &ns1__ConciliacionResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ConciliacionResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ConciliacionResponse.soap_put(soap, "ns1:ConciliacionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ConciliacionResponse.soap_put(soap, "ns1:ConciliacionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__Certificacion_(struct soap *soap)
{	struct __ns1__Certificacion_ soap_tmp___ns1__Certificacion_;
	_ns1__CertificacionResponse ns1__CertificacionResponse;
	ns1__CertificacionResponse.soap_default(soap);
	soap_default___ns1__Certificacion_(soap, &soap_tmp___ns1__Certificacion_);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__Certificacion_(soap, &soap_tmp___ns1__Certificacion_, "-ns1:Certificacion", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__Certificacion_(soap, soap_tmp___ns1__Certificacion_.ns1__Certificacion, &ns1__CertificacionResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__CertificacionResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__CertificacionResponse.soap_put(soap, "ns1:CertificacionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__CertificacionResponse.soap_put(soap, "ns1:CertificacionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__Confirmacion_(struct soap *soap)
{	struct __ns1__Confirmacion_ soap_tmp___ns1__Confirmacion_;
	_ns1__ConfirmacionResponse ns1__ConfirmacionResponse;
	ns1__ConfirmacionResponse.soap_default(soap);
	soap_default___ns1__Confirmacion_(soap, &soap_tmp___ns1__Confirmacion_);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__Confirmacion_(soap, &soap_tmp___ns1__Confirmacion_, "-ns1:Confirmacion", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__Confirmacion_(soap, soap_tmp___ns1__Confirmacion_.ns1__Confirmacion, &ns1__ConfirmacionResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ConfirmacionResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ConfirmacionResponse.soap_put(soap, "ns1:ConfirmacionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ConfirmacionResponse.soap_put(soap, "ns1:ConfirmacionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__Anulacion_(struct soap *soap)
{	struct __ns1__Anulacion_ soap_tmp___ns1__Anulacion_;
	_ns1__AnulacionResponse ns1__AnulacionResponse;
	ns1__AnulacionResponse.soap_default(soap);
	soap_default___ns1__Anulacion_(soap, &soap_tmp___ns1__Anulacion_);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__Anulacion_(soap, &soap_tmp___ns1__Anulacion_, "-ns1:Anulacion", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__Anulacion_(soap, soap_tmp___ns1__Anulacion_.ns1__Anulacion, &ns1__AnulacionResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__AnulacionResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__AnulacionResponse.soap_put(soap, "ns1:AnulacionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__AnulacionResponse.soap_put(soap, "ns1:AnulacionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__Conciliacion_(struct soap *soap)
{	struct __ns1__Conciliacion_ soap_tmp___ns1__Conciliacion_;
	_ns1__ConciliacionResponse ns1__ConciliacionResponse;
	ns1__ConciliacionResponse.soap_default(soap);
	soap_default___ns1__Conciliacion_(soap, &soap_tmp___ns1__Conciliacion_);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__Conciliacion_(soap, &soap_tmp___ns1__Conciliacion_, "-ns1:Conciliacion", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__Conciliacion_(soap, soap_tmp___ns1__Conciliacion_.ns1__Conciliacion, &ns1__ConciliacionResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ConciliacionResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ConciliacionResponse.soap_put(soap, "ns1:ConciliacionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ConciliacionResponse.soap_put(soap, "ns1:ConciliacionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.cpp */
