/* Anulacion_sermecoop.h
   Generated by wsdl2h 2.8.7 from http://10.0.0.114/~imed/nusoap/Sermecoop/wsAnulacion.php?wsdl and typemap.dat
   2014-06-30 16:08:21 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2001-2012 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Usage Notes

NOTE:

 - Run soapcpp2 on Anulacion_sermecoop.h to generate the SOAP/XML processing logic.
   Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 option -i to generate improved proxy and server classes.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h options -nname and -Nname to globally rename the prefix 'ns'.
 - Use wsdl2h option -d to enable DOM support for xsd:anyType.
 - Use wsdl2h option -g to auto-generate readers and writers for root elements.
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

WARNING:

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS.
   USE THE SOURCE CODE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT BUILDS:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

LICENSE:

@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following two licenses:
1) GPL or 2) Genivia's license for commercial use.
--------------------------------------------------------------------------------
1) GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
2) A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt cw

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://10.0.0.114/~imed/nusoap/Sermecoop                                 *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "http://10.0.0.114/~imed/nusoap/Sermecoop"

*/

#define SOAP_NAMESPACE_OF_ns1	"http://10.0.0.114/~imed/nusoap/Sermecoop"
//gsoap ns1   schema namespace:	http://10.0.0.114/~imed/nusoap/Sermecoop
//gsoap ns1   schema form:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/



/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://10.0.0.114/~imed/nusoap/Sermecoop                                 *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://10.0.0.114/~imed/nusoap/Sermecoop                                 *
 *                                                                            *
\******************************************************************************/


/// "http://10.0.0.114/~imed/nusoap/Sermecoop":wmImed_SrvAnulacion is a complexType.
struct ns1__wmImed_USCORESrvAnulacion
{
/// Element XML_INPUT of type xs:string.
    char*                                XML_USCOREINPUT                1;	///< Required element.
};

/// "http://10.0.0.114/~imed/nusoap/Sermecoop":wmImed_SrvAnulacionResponse is a complexType.
struct ns1__wmImed_USCORESrvAnulacionResponse
{
/// Element wmImed_SrvAnulacionResult of type xs:string.
    char*                                wmImed_USCORESrvAnulacionResult 1;	///< Required element.
};

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://10.0.0.114/~imed/nusoap/Sermecoop                                 *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://10.0.0.114/~imed/nusoap/Sermecoop                                 *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns1  service name:	wsAnulacionBinding 
//gsoap ns1  service type:	wsAnulacionPortType 
//gsoap ns1  service port:	http://10.0.0.114/~imed/nusoap/Sermecoop/wsAnulacion.php 
//gsoap ns1  service namespace:	http://10.0.0.114/~imed/nusoap/Sermecoop 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_bindings Service Bindings

  - @ref wsAnulacionBinding

@section Service_more More Information

  - @ref page_notes "Usage Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page wsAnulacionBinding Binding "wsAnulacionBinding"

@section wsAnulacionBinding_operations Operations of Binding  "wsAnulacionBinding"

  - @ref ns1__wmImed_USCORESrvAnulacion_

@section wsAnulacionBinding_ports Endpoints of Binding  "wsAnulacionBinding"

  - http://10.0.0.114/~imed/nusoap/Sermecoop/wsAnulacion.php

Note: use wsdl2h option -N to change the service binding prefix name

*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   wsAnulacionBinding                                                       *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns1__wmImed_USCORESrvAnulacion_                                          *
 *                                                                            *
\******************************************************************************/


/// Operation "ns1__wmImed_USCORESrvAnulacion_" of service binding "wsAnulacionBinding"

/**

Operation details:

Anulacion Imed

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

  - SOAP action: "http://10.0.0.114/~imed/nusoap/Sermecoop/wsAnulacion.php/wmImed_SrvAnulacion"

  - Addressing action: "http://10.0.0.114/~imed/nusoap/Sermecoop/wsAnulacionPortType/wmImed_USCORESrvAnulacion"

  - Addressing response action: "http://10.0.0.114/~imed/nusoap/Sermecoop/wsAnulacionPortType/wmImed_USCORESrvAnulacionResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns1__wmImed_USCORESrvAnulacion_(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct ns1__wmImed_USCORESrvAnulacion* XML_USCOREINPUT,
    // response parameters:
    char*                              *wmImed_USCORESrvAnulacionResult
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns1__wmImed_USCORESrvAnulacion_(
    struct soap *soap,
    // request parameters:
    struct ns1__wmImed_USCORESrvAnulacion* XML_USCOREINPUT,
    // response parameters:
    char*                              *wmImed_USCORESrvAnulacionResult
  );
@endcode

*/

//gsoap ns1  service method-style:	wmImed_USCORESrvAnulacion_ rpc
//gsoap ns1  service method-encoding:	wmImed_USCORESrvAnulacion_ http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns1  service method-action:	wmImed_USCORESrvAnulacion_ http://10.0.0.114/~imed/nusoap/Sermecoop/wsAnulacion.php/wmImed_SrvAnulacion
//gsoap ns1  service method-output-action:	wmImed_USCORESrvAnulacion_ http://10.0.0.114/~imed/nusoap/Sermecoop/wsAnulacionPortType/wmImed_USCORESrvAnulacionResponse
int ns1__wmImed_USCORESrvAnulacion_(
    struct ns1__wmImed_USCORESrvAnulacion* XML_USCOREINPUT,	///< Request parameter
    char*                              *wmImed_USCORESrvAnulacionResult	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

XML content can be retrieved from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

XML content can be stored to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback


@section ns1 Top-level root elements of schema "http://10.0.0.114/~imed/nusoap/Sermecoop"

*/

/* End of Anulacion_sermecoop.h */
