/* soapH.h
   Generated by gSOAP 2.8.0 from ServiciosSodexo.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap*, LONG64 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

#ifndef soap_write_LONG64
#define soap_write_LONG64(soap, data) ( soap_begin_send(soap) || soap_put_LONG64(soap, data, "long", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap*, const LONG64 *, const char*, const char*);

#ifndef soap_read_LONG64
#define soap_read_LONG64(soap, data) ( soap_begin_recv(soap) || !soap_get_LONG64(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#endif

#ifndef SOAP_TYPE___ns1__ConsultaSaldoYTrxDiaPorBeneficiario
#define SOAP_TYPE___ns1__ConsultaSaldoYTrxDiaPorBeneficiario (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__ConsultaSaldoYTrxDiaPorBeneficiario(struct soap*, struct __ns1__ConsultaSaldoYTrxDiaPorBeneficiario *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__ConsultaSaldoYTrxDiaPorBeneficiario(struct soap*, const struct __ns1__ConsultaSaldoYTrxDiaPorBeneficiario *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__ConsultaSaldoYTrxDiaPorBeneficiario(struct soap*, const char*, int, const struct __ns1__ConsultaSaldoYTrxDiaPorBeneficiario *, const char*);
SOAP_FMAC3 struct __ns1__ConsultaSaldoYTrxDiaPorBeneficiario * SOAP_FMAC4 soap_in___ns1__ConsultaSaldoYTrxDiaPorBeneficiario(struct soap*, const char*, struct __ns1__ConsultaSaldoYTrxDiaPorBeneficiario *, const char*);

#ifndef soap_write___ns1__ConsultaSaldoYTrxDiaPorBeneficiario
#define soap_write___ns1__ConsultaSaldoYTrxDiaPorBeneficiario(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__ConsultaSaldoYTrxDiaPorBeneficiario(soap, data), 0) || soap_put___ns1__ConsultaSaldoYTrxDiaPorBeneficiario(soap, data, "-ns1:ConsultaSaldoYTrxDiaPorBeneficiario", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__ConsultaSaldoYTrxDiaPorBeneficiario(struct soap*, const struct __ns1__ConsultaSaldoYTrxDiaPorBeneficiario *, const char*, const char*);

#ifndef soap_read___ns1__ConsultaSaldoYTrxDiaPorBeneficiario
#define soap_read___ns1__ConsultaSaldoYTrxDiaPorBeneficiario(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__ConsultaSaldoYTrxDiaPorBeneficiario(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__ConsultaSaldoYTrxDiaPorBeneficiario * SOAP_FMAC4 soap_get___ns1__ConsultaSaldoYTrxDiaPorBeneficiario(struct soap*, struct __ns1__ConsultaSaldoYTrxDiaPorBeneficiario *, const char*, const char*);

#ifndef SOAP_TYPE___ns1__ConsultaSaldoYTrxDiaPorAfiliado
#define SOAP_TYPE___ns1__ConsultaSaldoYTrxDiaPorAfiliado (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__ConsultaSaldoYTrxDiaPorAfiliado(struct soap*, struct __ns1__ConsultaSaldoYTrxDiaPorAfiliado *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__ConsultaSaldoYTrxDiaPorAfiliado(struct soap*, const struct __ns1__ConsultaSaldoYTrxDiaPorAfiliado *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__ConsultaSaldoYTrxDiaPorAfiliado(struct soap*, const char*, int, const struct __ns1__ConsultaSaldoYTrxDiaPorAfiliado *, const char*);
SOAP_FMAC3 struct __ns1__ConsultaSaldoYTrxDiaPorAfiliado * SOAP_FMAC4 soap_in___ns1__ConsultaSaldoYTrxDiaPorAfiliado(struct soap*, const char*, struct __ns1__ConsultaSaldoYTrxDiaPorAfiliado *, const char*);

#ifndef soap_write___ns1__ConsultaSaldoYTrxDiaPorAfiliado
#define soap_write___ns1__ConsultaSaldoYTrxDiaPorAfiliado(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__ConsultaSaldoYTrxDiaPorAfiliado(soap, data), 0) || soap_put___ns1__ConsultaSaldoYTrxDiaPorAfiliado(soap, data, "-ns1:ConsultaSaldoYTrxDiaPorAfiliado", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__ConsultaSaldoYTrxDiaPorAfiliado(struct soap*, const struct __ns1__ConsultaSaldoYTrxDiaPorAfiliado *, const char*, const char*);

#ifndef soap_read___ns1__ConsultaSaldoYTrxDiaPorAfiliado
#define soap_read___ns1__ConsultaSaldoYTrxDiaPorAfiliado(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__ConsultaSaldoYTrxDiaPorAfiliado(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__ConsultaSaldoYTrxDiaPorAfiliado * SOAP_FMAC4 soap_get___ns1__ConsultaSaldoYTrxDiaPorAfiliado(struct soap*, struct __ns1__ConsultaSaldoYTrxDiaPorAfiliado *, const char*, const char*);

#ifndef SOAP_TYPE___ns1__ActivacionTarjeta
#define SOAP_TYPE___ns1__ActivacionTarjeta (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__ActivacionTarjeta(struct soap*, struct __ns1__ActivacionTarjeta *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__ActivacionTarjeta(struct soap*, const struct __ns1__ActivacionTarjeta *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__ActivacionTarjeta(struct soap*, const char*, int, const struct __ns1__ActivacionTarjeta *, const char*);
SOAP_FMAC3 struct __ns1__ActivacionTarjeta * SOAP_FMAC4 soap_in___ns1__ActivacionTarjeta(struct soap*, const char*, struct __ns1__ActivacionTarjeta *, const char*);

#ifndef soap_write___ns1__ActivacionTarjeta
#define soap_write___ns1__ActivacionTarjeta(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__ActivacionTarjeta(soap, data), 0) || soap_put___ns1__ActivacionTarjeta(soap, data, "-ns1:ActivacionTarjeta", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__ActivacionTarjeta(struct soap*, const struct __ns1__ActivacionTarjeta *, const char*, const char*);

#ifndef soap_read___ns1__ActivacionTarjeta
#define soap_read___ns1__ActivacionTarjeta(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__ActivacionTarjeta(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__ActivacionTarjeta * SOAP_FMAC4 soap_get___ns1__ActivacionTarjeta(struct soap*, struct __ns1__ActivacionTarjeta *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse
#define SOAP_TYPE_ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse(struct soap*, struct ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse(struct soap*, const struct ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse(struct soap*, const char*, int, const struct ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse *, const char*);
SOAP_FMAC3 struct ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse * SOAP_FMAC4 soap_in_ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse(struct soap*, const char*, struct ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse *, const char*);

#ifndef soap_write_ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse
#define soap_write_ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse(soap, data), 0) || soap_put_ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse(soap, data, "ns1:ConsultaSaldoYTrxDiaPorBeneficiarioResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse(struct soap*, const struct ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse *, const char*, const char*);

#ifndef soap_read_ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse
#define soap_read_ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse * SOAP_FMAC4 soap_get_ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse(struct soap*, struct ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__outputWSSaldoTrxBenef
#define SOAP_TYPE_ns1__outputWSSaldoTrxBenef (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__outputWSSaldoTrxBenef(struct soap*, struct ns1__outputWSSaldoTrxBenef *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__outputWSSaldoTrxBenef(struct soap*, const struct ns1__outputWSSaldoTrxBenef *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__outputWSSaldoTrxBenef(struct soap*, const char*, int, const struct ns1__outputWSSaldoTrxBenef *, const char*);
SOAP_FMAC3 struct ns1__outputWSSaldoTrxBenef * SOAP_FMAC4 soap_in_ns1__outputWSSaldoTrxBenef(struct soap*, const char*, struct ns1__outputWSSaldoTrxBenef *, const char*);

#ifndef soap_write_ns1__outputWSSaldoTrxBenef
#define soap_write_ns1__outputWSSaldoTrxBenef(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__outputWSSaldoTrxBenef(soap, data), 0) || soap_put_ns1__outputWSSaldoTrxBenef(soap, data, "ns1:outputWSSaldoTrxBenef", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__outputWSSaldoTrxBenef(struct soap*, const struct ns1__outputWSSaldoTrxBenef *, const char*, const char*);

#ifndef soap_read_ns1__outputWSSaldoTrxBenef
#define soap_read_ns1__outputWSSaldoTrxBenef(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__outputWSSaldoTrxBenef(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__outputWSSaldoTrxBenef * SOAP_FMAC4 soap_get_ns1__outputWSSaldoTrxBenef(struct soap*, struct ns1__outputWSSaldoTrxBenef *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__rsspSaldoTrxBenef
#define SOAP_TYPE_ns1__rsspSaldoTrxBenef (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__rsspSaldoTrxBenef(struct soap*, struct ns1__rsspSaldoTrxBenef *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__rsspSaldoTrxBenef(struct soap*, const struct ns1__rsspSaldoTrxBenef *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__rsspSaldoTrxBenef(struct soap*, const char*, int, const struct ns1__rsspSaldoTrxBenef *, const char*);
SOAP_FMAC3 struct ns1__rsspSaldoTrxBenef * SOAP_FMAC4 soap_in_ns1__rsspSaldoTrxBenef(struct soap*, const char*, struct ns1__rsspSaldoTrxBenef *, const char*);

#ifndef soap_write_ns1__rsspSaldoTrxBenef
#define soap_write_ns1__rsspSaldoTrxBenef(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__rsspSaldoTrxBenef(soap, data), 0) || soap_put_ns1__rsspSaldoTrxBenef(soap, data, "ns1:rsspSaldoTrxBenef", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__rsspSaldoTrxBenef(struct soap*, const struct ns1__rsspSaldoTrxBenef *, const char*, const char*);

#ifndef soap_read_ns1__rsspSaldoTrxBenef
#define soap_read_ns1__rsspSaldoTrxBenef(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__rsspSaldoTrxBenef(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__rsspSaldoTrxBenef * SOAP_FMAC4 soap_get_ns1__rsspSaldoTrxBenef(struct soap*, struct ns1__rsspSaldoTrxBenef *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__ConsultaSaldoYTrxDiaPorBeneficiario
#define SOAP_TYPE_ns1__ConsultaSaldoYTrxDiaPorBeneficiario (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ConsultaSaldoYTrxDiaPorBeneficiario(struct soap*, struct ns1__ConsultaSaldoYTrxDiaPorBeneficiario *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ConsultaSaldoYTrxDiaPorBeneficiario(struct soap*, const struct ns1__ConsultaSaldoYTrxDiaPorBeneficiario *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ConsultaSaldoYTrxDiaPorBeneficiario(struct soap*, const char*, int, const struct ns1__ConsultaSaldoYTrxDiaPorBeneficiario *, const char*);
SOAP_FMAC3 struct ns1__ConsultaSaldoYTrxDiaPorBeneficiario * SOAP_FMAC4 soap_in_ns1__ConsultaSaldoYTrxDiaPorBeneficiario(struct soap*, const char*, struct ns1__ConsultaSaldoYTrxDiaPorBeneficiario *, const char*);

#ifndef soap_write_ns1__ConsultaSaldoYTrxDiaPorBeneficiario
#define soap_write_ns1__ConsultaSaldoYTrxDiaPorBeneficiario(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__ConsultaSaldoYTrxDiaPorBeneficiario(soap, data), 0) || soap_put_ns1__ConsultaSaldoYTrxDiaPorBeneficiario(soap, data, "ns1:ConsultaSaldoYTrxDiaPorBeneficiario", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ConsultaSaldoYTrxDiaPorBeneficiario(struct soap*, const struct ns1__ConsultaSaldoYTrxDiaPorBeneficiario *, const char*, const char*);

#ifndef soap_read_ns1__ConsultaSaldoYTrxDiaPorBeneficiario
#define soap_read_ns1__ConsultaSaldoYTrxDiaPorBeneficiario(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ConsultaSaldoYTrxDiaPorBeneficiario(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__ConsultaSaldoYTrxDiaPorBeneficiario * SOAP_FMAC4 soap_get_ns1__ConsultaSaldoYTrxDiaPorBeneficiario(struct soap*, struct ns1__ConsultaSaldoYTrxDiaPorBeneficiario *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse
#define SOAP_TYPE_ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse(struct soap*, struct ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse(struct soap*, const struct ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse(struct soap*, const char*, int, const struct ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse *, const char*);
SOAP_FMAC3 struct ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse * SOAP_FMAC4 soap_in_ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse(struct soap*, const char*, struct ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse *, const char*);

#ifndef soap_write_ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse
#define soap_write_ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse(soap, data), 0) || soap_put_ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse(soap, data, "ns1:ConsultaSaldoYTrxDiaPorAfiliadoResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse(struct soap*, const struct ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse *, const char*, const char*);

#ifndef soap_read_ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse
#define soap_read_ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse * SOAP_FMAC4 soap_get_ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse(struct soap*, struct ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__outputWSSaldoTrxAfiliad
#define SOAP_TYPE_ns1__outputWSSaldoTrxAfiliad (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__outputWSSaldoTrxAfiliad(struct soap*, struct ns1__outputWSSaldoTrxAfiliad *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__outputWSSaldoTrxAfiliad(struct soap*, const struct ns1__outputWSSaldoTrxAfiliad *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__outputWSSaldoTrxAfiliad(struct soap*, const char*, int, const struct ns1__outputWSSaldoTrxAfiliad *, const char*);
SOAP_FMAC3 struct ns1__outputWSSaldoTrxAfiliad * SOAP_FMAC4 soap_in_ns1__outputWSSaldoTrxAfiliad(struct soap*, const char*, struct ns1__outputWSSaldoTrxAfiliad *, const char*);

#ifndef soap_write_ns1__outputWSSaldoTrxAfiliad
#define soap_write_ns1__outputWSSaldoTrxAfiliad(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__outputWSSaldoTrxAfiliad(soap, data), 0) || soap_put_ns1__outputWSSaldoTrxAfiliad(soap, data, "ns1:outputWSSaldoTrxAfiliad", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__outputWSSaldoTrxAfiliad(struct soap*, const struct ns1__outputWSSaldoTrxAfiliad *, const char*, const char*);

#ifndef soap_read_ns1__outputWSSaldoTrxAfiliad
#define soap_read_ns1__outputWSSaldoTrxAfiliad(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__outputWSSaldoTrxAfiliad(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__outputWSSaldoTrxAfiliad * SOAP_FMAC4 soap_get_ns1__outputWSSaldoTrxAfiliad(struct soap*, struct ns1__outputWSSaldoTrxAfiliad *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__rsspSaldoTrxAfiliad
#define SOAP_TYPE_ns1__rsspSaldoTrxAfiliad (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__rsspSaldoTrxAfiliad(struct soap*, struct ns1__rsspSaldoTrxAfiliad *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__rsspSaldoTrxAfiliad(struct soap*, const struct ns1__rsspSaldoTrxAfiliad *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__rsspSaldoTrxAfiliad(struct soap*, const char*, int, const struct ns1__rsspSaldoTrxAfiliad *, const char*);
SOAP_FMAC3 struct ns1__rsspSaldoTrxAfiliad * SOAP_FMAC4 soap_in_ns1__rsspSaldoTrxAfiliad(struct soap*, const char*, struct ns1__rsspSaldoTrxAfiliad *, const char*);

#ifndef soap_write_ns1__rsspSaldoTrxAfiliad
#define soap_write_ns1__rsspSaldoTrxAfiliad(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__rsspSaldoTrxAfiliad(soap, data), 0) || soap_put_ns1__rsspSaldoTrxAfiliad(soap, data, "ns1:rsspSaldoTrxAfiliad", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__rsspSaldoTrxAfiliad(struct soap*, const struct ns1__rsspSaldoTrxAfiliad *, const char*, const char*);

#ifndef soap_read_ns1__rsspSaldoTrxAfiliad
#define soap_read_ns1__rsspSaldoTrxAfiliad(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__rsspSaldoTrxAfiliad(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__rsspSaldoTrxAfiliad * SOAP_FMAC4 soap_get_ns1__rsspSaldoTrxAfiliad(struct soap*, struct ns1__rsspSaldoTrxAfiliad *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__ConsultaSaldoYTrxDiaPorAfiliado
#define SOAP_TYPE_ns1__ConsultaSaldoYTrxDiaPorAfiliado (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ConsultaSaldoYTrxDiaPorAfiliado(struct soap*, struct ns1__ConsultaSaldoYTrxDiaPorAfiliado *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ConsultaSaldoYTrxDiaPorAfiliado(struct soap*, const struct ns1__ConsultaSaldoYTrxDiaPorAfiliado *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ConsultaSaldoYTrxDiaPorAfiliado(struct soap*, const char*, int, const struct ns1__ConsultaSaldoYTrxDiaPorAfiliado *, const char*);
SOAP_FMAC3 struct ns1__ConsultaSaldoYTrxDiaPorAfiliado * SOAP_FMAC4 soap_in_ns1__ConsultaSaldoYTrxDiaPorAfiliado(struct soap*, const char*, struct ns1__ConsultaSaldoYTrxDiaPorAfiliado *, const char*);

#ifndef soap_write_ns1__ConsultaSaldoYTrxDiaPorAfiliado
#define soap_write_ns1__ConsultaSaldoYTrxDiaPorAfiliado(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__ConsultaSaldoYTrxDiaPorAfiliado(soap, data), 0) || soap_put_ns1__ConsultaSaldoYTrxDiaPorAfiliado(soap, data, "ns1:ConsultaSaldoYTrxDiaPorAfiliado", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ConsultaSaldoYTrxDiaPorAfiliado(struct soap*, const struct ns1__ConsultaSaldoYTrxDiaPorAfiliado *, const char*, const char*);

#ifndef soap_read_ns1__ConsultaSaldoYTrxDiaPorAfiliado
#define soap_read_ns1__ConsultaSaldoYTrxDiaPorAfiliado(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ConsultaSaldoYTrxDiaPorAfiliado(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__ConsultaSaldoYTrxDiaPorAfiliado * SOAP_FMAC4 soap_get_ns1__ConsultaSaldoYTrxDiaPorAfiliado(struct soap*, struct ns1__ConsultaSaldoYTrxDiaPorAfiliado *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__WSInputSaldoTrx
#define SOAP_TYPE_ns1__WSInputSaldoTrx (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__WSInputSaldoTrx(struct soap*, struct ns1__WSInputSaldoTrx *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__WSInputSaldoTrx(struct soap*, const struct ns1__WSInputSaldoTrx *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__WSInputSaldoTrx(struct soap*, const char*, int, const struct ns1__WSInputSaldoTrx *, const char*);
SOAP_FMAC3 struct ns1__WSInputSaldoTrx * SOAP_FMAC4 soap_in_ns1__WSInputSaldoTrx(struct soap*, const char*, struct ns1__WSInputSaldoTrx *, const char*);

#ifndef soap_write_ns1__WSInputSaldoTrx
#define soap_write_ns1__WSInputSaldoTrx(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__WSInputSaldoTrx(soap, data), 0) || soap_put_ns1__WSInputSaldoTrx(soap, data, "ns1:WSInputSaldoTrx", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__WSInputSaldoTrx(struct soap*, const struct ns1__WSInputSaldoTrx *, const char*, const char*);

#ifndef soap_read_ns1__WSInputSaldoTrx
#define soap_read_ns1__WSInputSaldoTrx(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__WSInputSaldoTrx(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__WSInputSaldoTrx * SOAP_FMAC4 soap_get_ns1__WSInputSaldoTrx(struct soap*, struct ns1__WSInputSaldoTrx *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__ActivacionTarjetaResponse
#define SOAP_TYPE_ns1__ActivacionTarjetaResponse (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ActivacionTarjetaResponse(struct soap*, struct ns1__ActivacionTarjetaResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ActivacionTarjetaResponse(struct soap*, const struct ns1__ActivacionTarjetaResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ActivacionTarjetaResponse(struct soap*, const char*, int, const struct ns1__ActivacionTarjetaResponse *, const char*);
SOAP_FMAC3 struct ns1__ActivacionTarjetaResponse * SOAP_FMAC4 soap_in_ns1__ActivacionTarjetaResponse(struct soap*, const char*, struct ns1__ActivacionTarjetaResponse *, const char*);

#ifndef soap_write_ns1__ActivacionTarjetaResponse
#define soap_write_ns1__ActivacionTarjetaResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__ActivacionTarjetaResponse(soap, data), 0) || soap_put_ns1__ActivacionTarjetaResponse(soap, data, "ns1:ActivacionTarjetaResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ActivacionTarjetaResponse(struct soap*, const struct ns1__ActivacionTarjetaResponse *, const char*, const char*);

#ifndef soap_read_ns1__ActivacionTarjetaResponse
#define soap_read_ns1__ActivacionTarjetaResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ActivacionTarjetaResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__ActivacionTarjetaResponse * SOAP_FMAC4 soap_get_ns1__ActivacionTarjetaResponse(struct soap*, struct ns1__ActivacionTarjetaResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__listTrjOut
#define SOAP_TYPE_ns1__listTrjOut (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__listTrjOut(struct soap*, struct ns1__listTrjOut *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__listTrjOut(struct soap*, const struct ns1__listTrjOut *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__listTrjOut(struct soap*, const char*, int, const struct ns1__listTrjOut *, const char*);
SOAP_FMAC3 struct ns1__listTrjOut * SOAP_FMAC4 soap_in_ns1__listTrjOut(struct soap*, const char*, struct ns1__listTrjOut *, const char*);

#ifndef soap_write_ns1__listTrjOut
#define soap_write_ns1__listTrjOut(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__listTrjOut(soap, data), 0) || soap_put_ns1__listTrjOut(soap, data, "ns1:listTrjOut", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__listTrjOut(struct soap*, const struct ns1__listTrjOut *, const char*, const char*);

#ifndef soap_read_ns1__listTrjOut
#define soap_read_ns1__listTrjOut(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__listTrjOut(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__listTrjOut * SOAP_FMAC4 soap_get_ns1__listTrjOut(struct soap*, struct ns1__listTrjOut *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__outputWSActivacionTarjeta
#define SOAP_TYPE_ns1__outputWSActivacionTarjeta (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__outputWSActivacionTarjeta(struct soap*, struct ns1__outputWSActivacionTarjeta *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__outputWSActivacionTarjeta(struct soap*, const struct ns1__outputWSActivacionTarjeta *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__outputWSActivacionTarjeta(struct soap*, const char*, int, const struct ns1__outputWSActivacionTarjeta *, const char*);
SOAP_FMAC3 struct ns1__outputWSActivacionTarjeta * SOAP_FMAC4 soap_in_ns1__outputWSActivacionTarjeta(struct soap*, const char*, struct ns1__outputWSActivacionTarjeta *, const char*);

#ifndef soap_write_ns1__outputWSActivacionTarjeta
#define soap_write_ns1__outputWSActivacionTarjeta(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__outputWSActivacionTarjeta(soap, data), 0) || soap_put_ns1__outputWSActivacionTarjeta(soap, data, "ns1:outputWSActivacionTarjeta", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__outputWSActivacionTarjeta(struct soap*, const struct ns1__outputWSActivacionTarjeta *, const char*, const char*);

#ifndef soap_read_ns1__outputWSActivacionTarjeta
#define soap_read_ns1__outputWSActivacionTarjeta(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__outputWSActivacionTarjeta(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__outputWSActivacionTarjeta * SOAP_FMAC4 soap_get_ns1__outputWSActivacionTarjeta(struct soap*, struct ns1__outputWSActivacionTarjeta *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__ActivacionTarjeta
#define SOAP_TYPE_ns1__ActivacionTarjeta (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ActivacionTarjeta(struct soap*, struct ns1__ActivacionTarjeta *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ActivacionTarjeta(struct soap*, const struct ns1__ActivacionTarjeta *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ActivacionTarjeta(struct soap*, const char*, int, const struct ns1__ActivacionTarjeta *, const char*);
SOAP_FMAC3 struct ns1__ActivacionTarjeta * SOAP_FMAC4 soap_in_ns1__ActivacionTarjeta(struct soap*, const char*, struct ns1__ActivacionTarjeta *, const char*);

#ifndef soap_write_ns1__ActivacionTarjeta
#define soap_write_ns1__ActivacionTarjeta(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__ActivacionTarjeta(soap, data), 0) || soap_put_ns1__ActivacionTarjeta(soap, data, "ns1:ActivacionTarjeta", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ActivacionTarjeta(struct soap*, const struct ns1__ActivacionTarjeta *, const char*, const char*);

#ifndef soap_read_ns1__ActivacionTarjeta
#define soap_read_ns1__ActivacionTarjeta(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ActivacionTarjeta(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__ActivacionTarjeta * SOAP_FMAC4 soap_get_ns1__ActivacionTarjeta(struct soap*, struct ns1__ActivacionTarjeta *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__ListTarjetas
#define SOAP_TYPE_ns1__ListTarjetas (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ListTarjetas(struct soap*, struct ns1__ListTarjetas *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ListTarjetas(struct soap*, const struct ns1__ListTarjetas *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ListTarjetas(struct soap*, const char*, int, const struct ns1__ListTarjetas *, const char*);
SOAP_FMAC3 struct ns1__ListTarjetas * SOAP_FMAC4 soap_in_ns1__ListTarjetas(struct soap*, const char*, struct ns1__ListTarjetas *, const char*);

#ifndef soap_write_ns1__ListTarjetas
#define soap_write_ns1__ListTarjetas(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__ListTarjetas(soap, data), 0) || soap_put_ns1__ListTarjetas(soap, data, "ns1:ListTarjetas", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ListTarjetas(struct soap*, const struct ns1__ListTarjetas *, const char*, const char*);

#ifndef soap_read_ns1__ListTarjetas
#define soap_read_ns1__ListTarjetas(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__ListTarjetas(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__ListTarjetas * SOAP_FMAC4 soap_get_ns1__ListTarjetas(struct soap*, struct ns1__ListTarjetas *, const char*, const char*);

#ifndef SOAP_TYPE_ns1__WSInputActivacionTarjeta
#define SOAP_TYPE_ns1__WSInputActivacionTarjeta (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__WSInputActivacionTarjeta(struct soap*, struct ns1__WSInputActivacionTarjeta *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__WSInputActivacionTarjeta(struct soap*, const struct ns1__WSInputActivacionTarjeta *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__WSInputActivacionTarjeta(struct soap*, const char*, int, const struct ns1__WSInputActivacionTarjeta *, const char*);
SOAP_FMAC3 struct ns1__WSInputActivacionTarjeta * SOAP_FMAC4 soap_in_ns1__WSInputActivacionTarjeta(struct soap*, const char*, struct ns1__WSInputActivacionTarjeta *, const char*);

#ifndef soap_write_ns1__WSInputActivacionTarjeta
#define soap_write_ns1__WSInputActivacionTarjeta(soap, data) ( soap_begin_send(soap) || (soap_serialize_ns1__WSInputActivacionTarjeta(soap, data), 0) || soap_put_ns1__WSInputActivacionTarjeta(soap, data, "ns1:WSInputActivacionTarjeta", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__WSInputActivacionTarjeta(struct soap*, const struct ns1__WSInputActivacionTarjeta *, const char*, const char*);

#ifndef soap_read_ns1__WSInputActivacionTarjeta
#define soap_read_ns1__WSInputActivacionTarjeta(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__WSInputActivacionTarjeta(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__WSInputActivacionTarjeta * SOAP_FMAC4 soap_get_ns1__WSInputActivacionTarjeta(struct soap*, struct ns1__WSInputActivacionTarjeta *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse
#define SOAP_TYPE_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse(struct soap*, struct ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse(struct soap*, const char *, int, struct ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse *const*, const char *);
SOAP_FMAC3 struct ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse ** SOAP_FMAC4 soap_in_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse(struct soap*, const char*, struct ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse **, const char*);

#ifndef soap_write_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse
#define soap_write_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse(soap, data), 0) || soap_put_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse(soap, data, "ns1:ConsultaSaldoYTrxDiaPorBeneficiarioResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse(struct soap*, struct ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse
#define soap_read_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse ** SOAP_FMAC4 soap_get_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse(struct soap*, struct ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiario
#define SOAP_TYPE_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiario (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiario(struct soap*, struct ns1__ConsultaSaldoYTrxDiaPorBeneficiario *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiario(struct soap*, const char *, int, struct ns1__ConsultaSaldoYTrxDiaPorBeneficiario *const*, const char *);
SOAP_FMAC3 struct ns1__ConsultaSaldoYTrxDiaPorBeneficiario ** SOAP_FMAC4 soap_in_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiario(struct soap*, const char*, struct ns1__ConsultaSaldoYTrxDiaPorBeneficiario **, const char*);

#ifndef soap_write_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiario
#define soap_write_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiario(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiario(soap, data), 0) || soap_put_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiario(soap, data, "ns1:ConsultaSaldoYTrxDiaPorBeneficiario", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiario(struct soap*, struct ns1__ConsultaSaldoYTrxDiaPorBeneficiario *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiario
#define soap_read_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiario(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiario(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__ConsultaSaldoYTrxDiaPorBeneficiario ** SOAP_FMAC4 soap_get_PointerTons1__ConsultaSaldoYTrxDiaPorBeneficiario(struct soap*, struct ns1__ConsultaSaldoYTrxDiaPorBeneficiario **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliadoResponse
#define SOAP_TYPE_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliadoResponse (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliadoResponse(struct soap*, struct ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliadoResponse(struct soap*, const char *, int, struct ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse *const*, const char *);
SOAP_FMAC3 struct ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse ** SOAP_FMAC4 soap_in_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliadoResponse(struct soap*, const char*, struct ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse **, const char*);

#ifndef soap_write_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliadoResponse
#define soap_write_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliadoResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliadoResponse(soap, data), 0) || soap_put_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliadoResponse(soap, data, "ns1:ConsultaSaldoYTrxDiaPorAfiliadoResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliadoResponse(struct soap*, struct ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliadoResponse
#define soap_read_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliadoResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliadoResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse ** SOAP_FMAC4 soap_get_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliadoResponse(struct soap*, struct ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliado
#define SOAP_TYPE_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliado (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliado(struct soap*, struct ns1__ConsultaSaldoYTrxDiaPorAfiliado *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliado(struct soap*, const char *, int, struct ns1__ConsultaSaldoYTrxDiaPorAfiliado *const*, const char *);
SOAP_FMAC3 struct ns1__ConsultaSaldoYTrxDiaPorAfiliado ** SOAP_FMAC4 soap_in_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliado(struct soap*, const char*, struct ns1__ConsultaSaldoYTrxDiaPorAfiliado **, const char*);

#ifndef soap_write_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliado
#define soap_write_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliado(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliado(soap, data), 0) || soap_put_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliado(soap, data, "ns1:ConsultaSaldoYTrxDiaPorAfiliado", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliado(struct soap*, struct ns1__ConsultaSaldoYTrxDiaPorAfiliado *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliado
#define soap_read_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliado(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliado(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__ConsultaSaldoYTrxDiaPorAfiliado ** SOAP_FMAC4 soap_get_PointerTons1__ConsultaSaldoYTrxDiaPorAfiliado(struct soap*, struct ns1__ConsultaSaldoYTrxDiaPorAfiliado **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__ActivacionTarjetaResponse
#define SOAP_TYPE_PointerTons1__ActivacionTarjetaResponse (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ActivacionTarjetaResponse(struct soap*, struct ns1__ActivacionTarjetaResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ActivacionTarjetaResponse(struct soap*, const char *, int, struct ns1__ActivacionTarjetaResponse *const*, const char *);
SOAP_FMAC3 struct ns1__ActivacionTarjetaResponse ** SOAP_FMAC4 soap_in_PointerTons1__ActivacionTarjetaResponse(struct soap*, const char*, struct ns1__ActivacionTarjetaResponse **, const char*);

#ifndef soap_write_PointerTons1__ActivacionTarjetaResponse
#define soap_write_PointerTons1__ActivacionTarjetaResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__ActivacionTarjetaResponse(soap, data), 0) || soap_put_PointerTons1__ActivacionTarjetaResponse(soap, data, "ns1:ActivacionTarjetaResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ActivacionTarjetaResponse(struct soap*, struct ns1__ActivacionTarjetaResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__ActivacionTarjetaResponse
#define soap_read_PointerTons1__ActivacionTarjetaResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__ActivacionTarjetaResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__ActivacionTarjetaResponse ** SOAP_FMAC4 soap_get_PointerTons1__ActivacionTarjetaResponse(struct soap*, struct ns1__ActivacionTarjetaResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__ActivacionTarjeta
#define SOAP_TYPE_PointerTons1__ActivacionTarjeta (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ActivacionTarjeta(struct soap*, struct ns1__ActivacionTarjeta *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ActivacionTarjeta(struct soap*, const char *, int, struct ns1__ActivacionTarjeta *const*, const char *);
SOAP_FMAC3 struct ns1__ActivacionTarjeta ** SOAP_FMAC4 soap_in_PointerTons1__ActivacionTarjeta(struct soap*, const char*, struct ns1__ActivacionTarjeta **, const char*);

#ifndef soap_write_PointerTons1__ActivacionTarjeta
#define soap_write_PointerTons1__ActivacionTarjeta(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__ActivacionTarjeta(soap, data), 0) || soap_put_PointerTons1__ActivacionTarjeta(soap, data, "ns1:ActivacionTarjeta", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ActivacionTarjeta(struct soap*, struct ns1__ActivacionTarjeta *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__ActivacionTarjeta
#define soap_read_PointerTons1__ActivacionTarjeta(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__ActivacionTarjeta(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__ActivacionTarjeta ** SOAP_FMAC4 soap_get_PointerTons1__ActivacionTarjeta(struct soap*, struct ns1__ActivacionTarjeta **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__outputWSSaldoTrxBenef
#define SOAP_TYPE_PointerTons1__outputWSSaldoTrxBenef (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__outputWSSaldoTrxBenef(struct soap*, struct ns1__outputWSSaldoTrxBenef *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__outputWSSaldoTrxBenef(struct soap*, const char *, int, struct ns1__outputWSSaldoTrxBenef *const*, const char *);
SOAP_FMAC3 struct ns1__outputWSSaldoTrxBenef ** SOAP_FMAC4 soap_in_PointerTons1__outputWSSaldoTrxBenef(struct soap*, const char*, struct ns1__outputWSSaldoTrxBenef **, const char*);

#ifndef soap_write_PointerTons1__outputWSSaldoTrxBenef
#define soap_write_PointerTons1__outputWSSaldoTrxBenef(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__outputWSSaldoTrxBenef(soap, data), 0) || soap_put_PointerTons1__outputWSSaldoTrxBenef(soap, data, "ns1:outputWSSaldoTrxBenef", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__outputWSSaldoTrxBenef(struct soap*, struct ns1__outputWSSaldoTrxBenef *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__outputWSSaldoTrxBenef
#define soap_read_PointerTons1__outputWSSaldoTrxBenef(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__outputWSSaldoTrxBenef(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__outputWSSaldoTrxBenef ** SOAP_FMAC4 soap_get_PointerTons1__outputWSSaldoTrxBenef(struct soap*, struct ns1__outputWSSaldoTrxBenef **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__rsspSaldoTrxBenef
#define SOAP_TYPE_PointerTons1__rsspSaldoTrxBenef (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__rsspSaldoTrxBenef(struct soap*, struct ns1__rsspSaldoTrxBenef *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__rsspSaldoTrxBenef(struct soap*, const char *, int, struct ns1__rsspSaldoTrxBenef *const*, const char *);
SOAP_FMAC3 struct ns1__rsspSaldoTrxBenef ** SOAP_FMAC4 soap_in_PointerTons1__rsspSaldoTrxBenef(struct soap*, const char*, struct ns1__rsspSaldoTrxBenef **, const char*);

#ifndef soap_write_PointerTons1__rsspSaldoTrxBenef
#define soap_write_PointerTons1__rsspSaldoTrxBenef(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__rsspSaldoTrxBenef(soap, data), 0) || soap_put_PointerTons1__rsspSaldoTrxBenef(soap, data, "ns1:rsspSaldoTrxBenef", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__rsspSaldoTrxBenef(struct soap*, struct ns1__rsspSaldoTrxBenef *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__rsspSaldoTrxBenef
#define soap_read_PointerTons1__rsspSaldoTrxBenef(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__rsspSaldoTrxBenef(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__rsspSaldoTrxBenef ** SOAP_FMAC4 soap_get_PointerTons1__rsspSaldoTrxBenef(struct soap*, struct ns1__rsspSaldoTrxBenef **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__outputWSSaldoTrxAfiliad
#define SOAP_TYPE_PointerTons1__outputWSSaldoTrxAfiliad (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__outputWSSaldoTrxAfiliad(struct soap*, struct ns1__outputWSSaldoTrxAfiliad *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__outputWSSaldoTrxAfiliad(struct soap*, const char *, int, struct ns1__outputWSSaldoTrxAfiliad *const*, const char *);
SOAP_FMAC3 struct ns1__outputWSSaldoTrxAfiliad ** SOAP_FMAC4 soap_in_PointerTons1__outputWSSaldoTrxAfiliad(struct soap*, const char*, struct ns1__outputWSSaldoTrxAfiliad **, const char*);

#ifndef soap_write_PointerTons1__outputWSSaldoTrxAfiliad
#define soap_write_PointerTons1__outputWSSaldoTrxAfiliad(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__outputWSSaldoTrxAfiliad(soap, data), 0) || soap_put_PointerTons1__outputWSSaldoTrxAfiliad(soap, data, "ns1:outputWSSaldoTrxAfiliad", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__outputWSSaldoTrxAfiliad(struct soap*, struct ns1__outputWSSaldoTrxAfiliad *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__outputWSSaldoTrxAfiliad
#define soap_read_PointerTons1__outputWSSaldoTrxAfiliad(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__outputWSSaldoTrxAfiliad(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__outputWSSaldoTrxAfiliad ** SOAP_FMAC4 soap_get_PointerTons1__outputWSSaldoTrxAfiliad(struct soap*, struct ns1__outputWSSaldoTrxAfiliad **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__rsspSaldoTrxAfiliad
#define SOAP_TYPE_PointerTons1__rsspSaldoTrxAfiliad (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__rsspSaldoTrxAfiliad(struct soap*, struct ns1__rsspSaldoTrxAfiliad *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__rsspSaldoTrxAfiliad(struct soap*, const char *, int, struct ns1__rsspSaldoTrxAfiliad *const*, const char *);
SOAP_FMAC3 struct ns1__rsspSaldoTrxAfiliad ** SOAP_FMAC4 soap_in_PointerTons1__rsspSaldoTrxAfiliad(struct soap*, const char*, struct ns1__rsspSaldoTrxAfiliad **, const char*);

#ifndef soap_write_PointerTons1__rsspSaldoTrxAfiliad
#define soap_write_PointerTons1__rsspSaldoTrxAfiliad(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__rsspSaldoTrxAfiliad(soap, data), 0) || soap_put_PointerTons1__rsspSaldoTrxAfiliad(soap, data, "ns1:rsspSaldoTrxAfiliad", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__rsspSaldoTrxAfiliad(struct soap*, struct ns1__rsspSaldoTrxAfiliad *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__rsspSaldoTrxAfiliad
#define soap_read_PointerTons1__rsspSaldoTrxAfiliad(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__rsspSaldoTrxAfiliad(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__rsspSaldoTrxAfiliad ** SOAP_FMAC4 soap_get_PointerTons1__rsspSaldoTrxAfiliad(struct soap*, struct ns1__rsspSaldoTrxAfiliad **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__WSInputSaldoTrx
#define SOAP_TYPE_PointerTons1__WSInputSaldoTrx (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__WSInputSaldoTrx(struct soap*, struct ns1__WSInputSaldoTrx *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__WSInputSaldoTrx(struct soap*, const char *, int, struct ns1__WSInputSaldoTrx *const*, const char *);
SOAP_FMAC3 struct ns1__WSInputSaldoTrx ** SOAP_FMAC4 soap_in_PointerTons1__WSInputSaldoTrx(struct soap*, const char*, struct ns1__WSInputSaldoTrx **, const char*);

#ifndef soap_write_PointerTons1__WSInputSaldoTrx
#define soap_write_PointerTons1__WSInputSaldoTrx(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__WSInputSaldoTrx(soap, data), 0) || soap_put_PointerTons1__WSInputSaldoTrx(soap, data, "ns1:WSInputSaldoTrx", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__WSInputSaldoTrx(struct soap*, struct ns1__WSInputSaldoTrx *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__WSInputSaldoTrx
#define soap_read_PointerTons1__WSInputSaldoTrx(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__WSInputSaldoTrx(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__WSInputSaldoTrx ** SOAP_FMAC4 soap_get_PointerTons1__WSInputSaldoTrx(struct soap*, struct ns1__WSInputSaldoTrx **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__outputWSActivacionTarjeta
#define SOAP_TYPE_PointerTons1__outputWSActivacionTarjeta (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__outputWSActivacionTarjeta(struct soap*, struct ns1__outputWSActivacionTarjeta *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__outputWSActivacionTarjeta(struct soap*, const char *, int, struct ns1__outputWSActivacionTarjeta *const*, const char *);
SOAP_FMAC3 struct ns1__outputWSActivacionTarjeta ** SOAP_FMAC4 soap_in_PointerTons1__outputWSActivacionTarjeta(struct soap*, const char*, struct ns1__outputWSActivacionTarjeta **, const char*);

#ifndef soap_write_PointerTons1__outputWSActivacionTarjeta
#define soap_write_PointerTons1__outputWSActivacionTarjeta(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__outputWSActivacionTarjeta(soap, data), 0) || soap_put_PointerTons1__outputWSActivacionTarjeta(soap, data, "ns1:outputWSActivacionTarjeta", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__outputWSActivacionTarjeta(struct soap*, struct ns1__outputWSActivacionTarjeta *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__outputWSActivacionTarjeta
#define soap_read_PointerTons1__outputWSActivacionTarjeta(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__outputWSActivacionTarjeta(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__outputWSActivacionTarjeta ** SOAP_FMAC4 soap_get_PointerTons1__outputWSActivacionTarjeta(struct soap*, struct ns1__outputWSActivacionTarjeta **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__listTrjOut
#define SOAP_TYPE_PointerTons1__listTrjOut (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__listTrjOut(struct soap*, struct ns1__listTrjOut *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__listTrjOut(struct soap*, const char *, int, struct ns1__listTrjOut *const*, const char *);
SOAP_FMAC3 struct ns1__listTrjOut ** SOAP_FMAC4 soap_in_PointerTons1__listTrjOut(struct soap*, const char*, struct ns1__listTrjOut **, const char*);

#ifndef soap_write_PointerTons1__listTrjOut
#define soap_write_PointerTons1__listTrjOut(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__listTrjOut(soap, data), 0) || soap_put_PointerTons1__listTrjOut(soap, data, "ns1:listTrjOut", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__listTrjOut(struct soap*, struct ns1__listTrjOut *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__listTrjOut
#define soap_read_PointerTons1__listTrjOut(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__listTrjOut(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__listTrjOut ** SOAP_FMAC4 soap_get_PointerTons1__listTrjOut(struct soap*, struct ns1__listTrjOut **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__WSInputActivacionTarjeta
#define SOAP_TYPE_PointerTons1__WSInputActivacionTarjeta (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__WSInputActivacionTarjeta(struct soap*, struct ns1__WSInputActivacionTarjeta *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__WSInputActivacionTarjeta(struct soap*, const char *, int, struct ns1__WSInputActivacionTarjeta *const*, const char *);
SOAP_FMAC3 struct ns1__WSInputActivacionTarjeta ** SOAP_FMAC4 soap_in_PointerTons1__WSInputActivacionTarjeta(struct soap*, const char*, struct ns1__WSInputActivacionTarjeta **, const char*);

#ifndef soap_write_PointerTons1__WSInputActivacionTarjeta
#define soap_write_PointerTons1__WSInputActivacionTarjeta(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__WSInputActivacionTarjeta(soap, data), 0) || soap_put_PointerTons1__WSInputActivacionTarjeta(soap, data, "ns1:WSInputActivacionTarjeta", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__WSInputActivacionTarjeta(struct soap*, struct ns1__WSInputActivacionTarjeta *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__WSInputActivacionTarjeta
#define soap_read_PointerTons1__WSInputActivacionTarjeta(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__WSInputActivacionTarjeta(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__WSInputActivacionTarjeta ** SOAP_FMAC4 soap_get_PointerTons1__WSInputActivacionTarjeta(struct soap*, struct ns1__WSInputActivacionTarjeta **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__ListTarjetas
#define SOAP_TYPE_PointerTons1__ListTarjetas (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ListTarjetas(struct soap*, struct ns1__ListTarjetas *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ListTarjetas(struct soap*, const char *, int, struct ns1__ListTarjetas *const*, const char *);
SOAP_FMAC3 struct ns1__ListTarjetas ** SOAP_FMAC4 soap_in_PointerTons1__ListTarjetas(struct soap*, const char*, struct ns1__ListTarjetas **, const char*);

#ifndef soap_write_PointerTons1__ListTarjetas
#define soap_write_PointerTons1__ListTarjetas(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__ListTarjetas(soap, data), 0) || soap_put_PointerTons1__ListTarjetas(soap, data, "ns1:ListTarjetas", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ListTarjetas(struct soap*, struct ns1__ListTarjetas *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__ListTarjetas
#define soap_read_PointerTons1__ListTarjetas(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__ListTarjetas(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ns1__ListTarjetas ** SOAP_FMAC4 soap_get_PointerTons1__ListTarjetas(struct soap*, struct ns1__ListTarjetas **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
