/* soapStub.h
   Generated by gSOAP 2.8.0 from ServiciosSodexo.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_ns1__WSInputActivacionTarjeta
#define SOAP_TYPE_ns1__WSInputActivacionTarjeta (7)
/* ns1:WSInputActivacionTarjeta */
struct ns1__WSInputActivacionTarjeta
{
	int sTipoId;	/* required element of type xsd:int */
	char *sValorId;	/* required element of type xsd:string */
	int sServicio;	/* required element of type xsd:int */
	char *sCliente;	/* required element of type xsd:string */
	int __sizesTarjetas;	/* sequence of elements <sTarjetas> */
	struct ns1__ListTarjetas *sTarjetas;	/* required element of type ns1:ListTarjetas */
};
#endif

#ifndef SOAP_TYPE_ns1__ActivacionTarjeta
#define SOAP_TYPE_ns1__ActivacionTarjeta (10)
/* ns1:ActivacionTarjeta */
struct ns1__ActivacionTarjeta
{
	struct ns1__WSInputActivacionTarjeta *arg0;	/* optional element of type ns1:WSInputActivacionTarjeta */
};
#endif

#ifndef SOAP_TYPE_ns1__ListTarjetas
#define SOAP_TYPE_ns1__ListTarjetas (8)
/* ns1:ListTarjetas */
struct ns1__ListTarjetas
{
	char *Tarjeta;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__outputWSActivacionTarjeta
#define SOAP_TYPE_ns1__outputWSActivacionTarjeta (12)
/* ns1:outputWSActivacionTarjeta */
struct ns1__outputWSActivacionTarjeta
{
	int __sizelistaTrjOut;	/* sequence of elements <listaTrjOut> */
	struct ns1__listTrjOut *listaTrjOut;	/* optional element of type ns1:listTrjOut */
	char *SGlosaStatus;	/* optional element of type xsd:string */
	int SStatusMsg;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__ActivacionTarjetaResponse
#define SOAP_TYPE_ns1__ActivacionTarjetaResponse (15)
/* ns1:ActivacionTarjetaResponse */
struct ns1__ActivacionTarjetaResponse
{
	struct ns1__outputWSActivacionTarjeta *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:outputWSActivacionTarjeta */
};
#endif

#ifndef SOAP_TYPE_ns1__listTrjOut
#define SOAP_TYPE_ns1__listTrjOut (13)
/* ns1:listTrjOut */
struct ns1__listTrjOut
{
	char *SStatusTarjeta;	/* optional element of type xsd:string */
	char *STarjeta;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__WSInputSaldoTrx
#define SOAP_TYPE_ns1__WSInputSaldoTrx (17)
/* ns1:WSInputSaldoTrx */
struct ns1__WSInputSaldoTrx
{
	int S_USCORETipo_USCOREID;	/* required element of type xsd:int */
	char *S_USCOREValor_USCOREID;	/* required element of type xsd:string */
	int S_USCOREServicio;	/* required element of type xsd:int */
	char *S_USCORECliente;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__ConsultaSaldoYTrxDiaPorAfiliado
#define SOAP_TYPE_ns1__ConsultaSaldoYTrxDiaPorAfiliado (18)
/* ns1:ConsultaSaldoYTrxDiaPorAfiliado */
struct ns1__ConsultaSaldoYTrxDiaPorAfiliado
{
	struct ns1__WSInputSaldoTrx *arg0;	/* optional element of type ns1:WSInputSaldoTrx */
};
#endif

#ifndef SOAP_TYPE_ns1__rsspSaldoTrxAfiliad
#define SOAP_TYPE_ns1__rsspSaldoTrxAfiliad (20)
/* ns1:rsspSaldoTrxAfiliad */
struct ns1__rsspSaldoTrxAfiliad
{
	char *SFecha;	/* optional element of type xsd:string */
	char *SIdConsumo;	/* optional element of type xsd:string */
	LONG64 SMonto;	/* required element of type xsd:long */
	char *SRutBenef;	/* optional element of type xsd:string */
	int SStatusTrx;	/* required element of type xsd:int */
	char *STarjeta;	/* optional element of type xsd:string */
	int STipo;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__outputWSSaldoTrxAfiliad
#define SOAP_TYPE_ns1__outputWSSaldoTrxAfiliad (22)
/* ns1:outputWSSaldoTrxAfiliad */
struct ns1__outputWSSaldoTrxAfiliad
{
	char *SGlosaStatus;	/* optional element of type xsd:string */
	int SStatus;	/* required element of type xsd:int */
	int __sizetrxsAfiliado;	/* sequence of elements <trxsAfiliado> */
	struct ns1__rsspSaldoTrxAfiliad *trxsAfiliado;	/* optional element of type ns1:rsspSaldoTrxAfiliad */
};
#endif

#ifndef SOAP_TYPE_ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse
#define SOAP_TYPE_ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse (24)
/* ns1:ConsultaSaldoYTrxDiaPorAfiliadoResponse */
struct ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse
{
	struct ns1__outputWSSaldoTrxAfiliad *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:outputWSSaldoTrxAfiliad */
};
#endif

#ifndef SOAP_TYPE_ns1__ConsultaSaldoYTrxDiaPorBeneficiario
#define SOAP_TYPE_ns1__ConsultaSaldoYTrxDiaPorBeneficiario (26)
/* ns1:ConsultaSaldoYTrxDiaPorBeneficiario */
struct ns1__ConsultaSaldoYTrxDiaPorBeneficiario
{
	struct ns1__WSInputSaldoTrx *arg0;	/* optional element of type ns1:WSInputSaldoTrx */
};
#endif

#ifndef SOAP_TYPE_ns1__rsspSaldoTrxBenef
#define SOAP_TYPE_ns1__rsspSaldoTrxBenef (27)
/* ns1:rsspSaldoTrxBenef */
struct ns1__rsspSaldoTrxBenef
{
	char *SFecha;	/* optional element of type xsd:string */
	char *SIdConsumo;	/* optional element of type xsd:string */
	LONG64 SMonto;	/* required element of type xsd:long */
	char *STarjeta;	/* optional element of type xsd:string */
	int STipo;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__outputWSSaldoTrxBenef
#define SOAP_TYPE_ns1__outputWSSaldoTrxBenef (28)
/* ns1:outputWSSaldoTrxBenef */
struct ns1__outputWSSaldoTrxBenef
{
	char *SGlosaStatus;	/* optional element of type xsd:string */
	int SSaldoDisp;	/* required element of type xsd:int */
	int SSaldoVenc;	/* required element of type xsd:int */
	int SStatus;	/* required element of type xsd:int */
	int __sizetrxsBeneficiario;	/* sequence of elements <trxsBeneficiario> */
	struct ns1__rsspSaldoTrxBenef *trxsBeneficiario;	/* optional element of type ns1:rsspSaldoTrxBenef */
};
#endif

#ifndef SOAP_TYPE_ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse
#define SOAP_TYPE_ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse (30)
/* ns1:ConsultaSaldoYTrxDiaPorBeneficiarioResponse */
struct ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse
{
	struct ns1__outputWSSaldoTrxBenef *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:outputWSSaldoTrxBenef */
};
#endif

#ifndef SOAP_TYPE___ns1__ActivacionTarjeta
#define SOAP_TYPE___ns1__ActivacionTarjeta (35)
/* Operation wrapper: */
struct __ns1__ActivacionTarjeta
{
	struct ns1__ActivacionTarjeta *ns1__ActivacionTarjeta;	/* optional element of type ns1:ActivacionTarjeta */
};
#endif

#ifndef SOAP_TYPE___ns1__ConsultaSaldoYTrxDiaPorAfiliado
#define SOAP_TYPE___ns1__ConsultaSaldoYTrxDiaPorAfiliado (39)
/* Operation wrapper: */
struct __ns1__ConsultaSaldoYTrxDiaPorAfiliado
{
	struct ns1__ConsultaSaldoYTrxDiaPorAfiliado *ns1__ConsultaSaldoYTrxDiaPorAfiliado;	/* optional element of type ns1:ConsultaSaldoYTrxDiaPorAfiliado */
};
#endif

#ifndef SOAP_TYPE___ns1__ConsultaSaldoYTrxDiaPorBeneficiario
#define SOAP_TYPE___ns1__ConsultaSaldoYTrxDiaPorBeneficiario (43)
/* Operation wrapper: */
struct __ns1__ConsultaSaldoYTrxDiaPorBeneficiario
{
	struct ns1__ConsultaSaldoYTrxDiaPorBeneficiario *ns1__ConsultaSaldoYTrxDiaPorBeneficiario;	/* optional element of type ns1:ConsultaSaldoYTrxDiaPorBeneficiario */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (44)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (45)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (47)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (50)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (51)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 __ns1__ActivacionTarjeta(struct soap*, struct ns1__ActivacionTarjeta *ns1__ActivacionTarjeta, struct ns1__ActivacionTarjetaResponse *ns1__ActivacionTarjetaResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns1__ConsultaSaldoYTrxDiaPorAfiliado(struct soap*, struct ns1__ConsultaSaldoYTrxDiaPorAfiliado *ns1__ConsultaSaldoYTrxDiaPorAfiliado, struct ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse *ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns1__ConsultaSaldoYTrxDiaPorBeneficiario(struct soap*, struct ns1__ConsultaSaldoYTrxDiaPorBeneficiario *ns1__ConsultaSaldoYTrxDiaPorBeneficiario, struct ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse *ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__ActivacionTarjeta(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__ConsultaSaldoYTrxDiaPorAfiliado(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__ConsultaSaldoYTrxDiaPorBeneficiario(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ActivacionTarjeta(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__ActivacionTarjeta *ns1__ActivacionTarjeta, struct ns1__ActivacionTarjetaResponse *ns1__ActivacionTarjetaResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ConsultaSaldoYTrxDiaPorAfiliado(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__ConsultaSaldoYTrxDiaPorAfiliado *ns1__ConsultaSaldoYTrxDiaPorAfiliado, struct ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse *ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ConsultaSaldoYTrxDiaPorBeneficiario(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__ConsultaSaldoYTrxDiaPorBeneficiario *ns1__ConsultaSaldoYTrxDiaPorBeneficiario, struct ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse *ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
