/* soapServer.c
   Generated by gSOAP 2.8.0 from ServiciosSodexo.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.0 2010-10-05 22:18:47 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif

	do
	{
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			soap->error = SOAP_EOF;
			return soap_send_fault(soap);
		}
#endif

		soap_begin(soap);

#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif

		if (soap_begin_recv(soap))
		{	if (soap->error < SOAP_STOP)
			{
#ifdef WITH_FASTCGI
				soap_send_fault(soap);
#else 
				return soap_send_fault(soap);
#endif
			}
			soap_closesock(soap);

			continue;
		}

		if (soap_envelope_begin_in(soap)
		 || soap_recv_header(soap)
		 || soap_body_begin_in(soap)
		 || soap_serve_request(soap)
		 || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:ActivacionTarjeta"))
		return soap_serve___ns1__ActivacionTarjeta(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:ConsultaSaldoYTrxDiaPorAfiliado"))
		return soap_serve___ns1__ConsultaSaldoYTrxDiaPorAfiliado(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:ConsultaSaldoYTrxDiaPorBeneficiario"))
		return soap_serve___ns1__ConsultaSaldoYTrxDiaPorBeneficiario(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__ActivacionTarjeta(struct soap *soap)
{	struct __ns1__ActivacionTarjeta soap_tmp___ns1__ActivacionTarjeta;
	struct ns1__ActivacionTarjetaResponse ns1__ActivacionTarjetaResponse;
	soap_default_ns1__ActivacionTarjetaResponse(soap, &ns1__ActivacionTarjetaResponse);
	soap_default___ns1__ActivacionTarjeta(soap, &soap_tmp___ns1__ActivacionTarjeta);
	soap->encodingStyle = "";
	if (!soap_get___ns1__ActivacionTarjeta(soap, &soap_tmp___ns1__ActivacionTarjeta, "-ns1:ActivacionTarjeta", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__ActivacionTarjeta(soap, soap_tmp___ns1__ActivacionTarjeta.ns1__ActivacionTarjeta, &ns1__ActivacionTarjetaResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__ActivacionTarjetaResponse(soap, &ns1__ActivacionTarjetaResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__ActivacionTarjetaResponse(soap, &ns1__ActivacionTarjetaResponse, "ns1:ActivacionTarjetaResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__ActivacionTarjetaResponse(soap, &ns1__ActivacionTarjetaResponse, "ns1:ActivacionTarjetaResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__ConsultaSaldoYTrxDiaPorAfiliado(struct soap *soap)
{	struct __ns1__ConsultaSaldoYTrxDiaPorAfiliado soap_tmp___ns1__ConsultaSaldoYTrxDiaPorAfiliado;
	struct ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse;
	soap_default_ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse(soap, &ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse);
	soap_default___ns1__ConsultaSaldoYTrxDiaPorAfiliado(soap, &soap_tmp___ns1__ConsultaSaldoYTrxDiaPorAfiliado);
	soap->encodingStyle = "";
	if (!soap_get___ns1__ConsultaSaldoYTrxDiaPorAfiliado(soap, &soap_tmp___ns1__ConsultaSaldoYTrxDiaPorAfiliado, "-ns1:ConsultaSaldoYTrxDiaPorAfiliado", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__ConsultaSaldoYTrxDiaPorAfiliado(soap, soap_tmp___ns1__ConsultaSaldoYTrxDiaPorAfiliado.ns1__ConsultaSaldoYTrxDiaPorAfiliado, &ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse(soap, &ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse(soap, &ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse, "ns1:ConsultaSaldoYTrxDiaPorAfiliadoResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse(soap, &ns1__ConsultaSaldoYTrxDiaPorAfiliadoResponse, "ns1:ConsultaSaldoYTrxDiaPorAfiliadoResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__ConsultaSaldoYTrxDiaPorBeneficiario(struct soap *soap)
{	struct __ns1__ConsultaSaldoYTrxDiaPorBeneficiario soap_tmp___ns1__ConsultaSaldoYTrxDiaPorBeneficiario;
	struct ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse;
	soap_default_ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse(soap, &ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse);
	soap_default___ns1__ConsultaSaldoYTrxDiaPorBeneficiario(soap, &soap_tmp___ns1__ConsultaSaldoYTrxDiaPorBeneficiario);
	soap->encodingStyle = "";
	if (!soap_get___ns1__ConsultaSaldoYTrxDiaPorBeneficiario(soap, &soap_tmp___ns1__ConsultaSaldoYTrxDiaPorBeneficiario, "-ns1:ConsultaSaldoYTrxDiaPorBeneficiario", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__ConsultaSaldoYTrxDiaPorBeneficiario(soap, soap_tmp___ns1__ConsultaSaldoYTrxDiaPorBeneficiario.ns1__ConsultaSaldoYTrxDiaPorBeneficiario, &ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse(soap, &ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse(soap, &ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse, "ns1:ConsultaSaldoYTrxDiaPorBeneficiarioResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse(soap, &ns1__ConsultaSaldoYTrxDiaPorBeneficiarioResponse, "ns1:ConsultaSaldoYTrxDiaPorBeneficiarioResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
