
SQL*Plus: Release 11.2.0.3.0 Production on Wed Sep 25 11:58:28 2013

Copyright (c) 1982, 2011, Oracle.  All rights reserved.


Connected to:
Oracle Database 10g Enterprise Edition Release 10.2.0.5.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options

SQL> SQL> PROCEDURE CONENVBONIS
 Argument Name			Type			In/Out Default?
 ------------------------------ ----------------------- ------ --------
 SRV_MESSAGE			VARCHAR2		IN/OUT
 IN_NEXTCODFINANCIADOR		NUMBER			IN
 IN_VEXTHOMNUMEROCONVENIO	VARCHAR2		IN
 IN_VEXTHOMLUGARCONVENIO	VARCHAR2		IN
 IN_VEXTSUCVENTA		VARCHAR2		IN
 IN_VEXTRUTCONVENIO		VARCHAR2		IN
 IN_VEXTRUTASOCIADO		VARCHAR2		IN
 IN_VEXTNOMPRESTADOR		VARCHAR2		IN
 IN_VEXTRUTTRATANTE		VARCHAR2		IN
 IN_VEXTESPECIALIDAD		VARCHAR2		IN
 IN_VEXTRUTBENEFICIARIO 	VARCHAR2		IN
 IN_VEXTRUTCOTIZANTE		VARCHAR2		IN
 IN_VEXTRUTACOMPANANTE		VARCHAR2		IN
 IN_VEXTRUTEMISOR		VARCHAR2		IN
 IN_VEXTRUTCAJERO		VARCHAR2		IN
 IN_VEXTCODIGODIAGNOSTICO	VARCHAR2		IN
 IN_VEXTDESCUENTOXPLANILLA	VARCHAR2		IN
 IN_NEXTMONTOEXCEDENTE		NUMBER			IN
 IN_VEXTFECHAEMISION		VARCHAR2		IN
 IN_NEXTNIVELCONVENIO		NUMBER			IN
 IN_NEXTFOLIOFINANCIADOR	NUMBER			IN
 IN_NEXTMONTOVALORTOTAL 	NUMBER			IN
 IN_NEXTMONTOAPORTETOTAL	NUMBER			IN
 IN_NEXTMONTOCOPAGOTOTAL	NUMBER			IN
 IN_NEXTNUMOPERACION		NUMBER			IN
 IN_NEXTCORRPRESTACION		NUMBER			IN
 IN_NEXTTIPOSOLICITUD		NUMBER			IN
 IN_VEXTFECHAINICIO		VARCHAR2		IN
 IN_VEXTURGENCIA		VARCHAR2		IN
 IN_VEXTPLAN			VARCHAR2		IN
 IN_VEXTLISTA1			VARCHAR2		IN
 IN_VEXTLISTA2			VARCHAR2		IN
 IN_VEXTLISTA3			VARCHAR2		IN
 OUT_VEXTCODERROR		VARCHAR2		OUT
 OUT_VEXTMENSAJEERROR		VARCHAR2		OUT

SQL> Disconnected from Oracle Database 10g Enterprise Edition Release 10.2.0.5.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options
