
SQL*Plus: Release 11.2.0.3.0 Production on Wed Sep 25 11:58:28 2013

Copyright (c) 1982, 2011, Oracle.  All rights reserved.


Connected to:
Oracle Database 10g Enterprise Edition Release 10.2.0.5.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options

SQL> SQL> PROCEDURE CONVALIDACAT
 Argument Name			Type			In/Out Default?
 ------------------------------ ----------------------- ------ --------
 SRV_MESSAGE			VARCHAR2		IN/OUT
 IN_NEXTCODFINANCIADOR		NUMBER			IN
 IN_VEXTRUTCONVENIO		VARCHAR2		IN
 IN_VEXTRUTTRATANTE		VARCHAR2		IN
 IN_VEXTRUTSOLICITANTE		VARCHAR2		IN
 IN_VEXTRUTBENEFICIARIO 	VARCHAR2		IN
 IN_VEXTRUTCOTIZANTE		VARCHAR2		IN
 IN_VEXTCODIGOHOMOLOGO		VARCHAR2		IN
 IN_VEXTITEM			VARCHAR2		IN
 IN_VEXTCODIGODIAGNOSTICO	VARCHAR2		IN
 IN_VEXTCODMODALIDAD		VARCHAR2		IN
 IN_VEXTCODTIPATENCION		VARCHAR2		IN
 IN_VEXTFECHANACIMIENTO 	VARCHAR2		IN
 IN_VEXTCODSEXO 		VARCHAR2		IN
 IN_VEXTFECHAINICIO		VARCHAR2		IN
 IN_VEXTFECHATERMINO		VARCHAR2		IN
 IN_NEXTFRECPRESTDIA		NUMBER			IN
 IN_VEXTLISTAPRESTACA		VARCHAR2		IN
 IN_VEXTLISTAPRESTACB		VARCHAR2		IN
 IN_VEXTLISTAPRESTACC		VARCHAR2		IN
 IN_VEXTLISTAPRESTACD		VARCHAR2		IN
 IN_VEXTLISTAPRESTACE		VARCHAR2		IN
 IN_VEXTLISTAPRESTACF		VARCHAR2		IN
 IN_VEXTINDVIDEO		VARCHAR2		IN
 IN_VEXTINDBILATERAL		VARCHAR2		IN
 IN_VEXTRECARGOFUERAHORA	VARCHAR2		IN
 IN_VEXTINDREEMBOLSO		VARCHAR2		IN
 IN_VEXTINDPROGRAMA		VARCHAR2		IN
 IN_VEXTCODAPLICACION		VARCHAR2		IN
 IN_VEXTCODREGION		VARCHAR2		IN
 IN_VEXTCODSUCUR		VARCHAR2		IN
 IN_VEXTTIPOPRESTADOR		VARCHAR2		IN
 IN_VEXTCODESPECIALIDADES	VARCHAR2		IN
 IN_VEXTCODPROFESIONES		VARCHAR2		IN
 IN_VEXTANOSANTIGUEDAD		VARCHAR2		IN
 OUT_VEXTRESPUESTACAT		VARCHAR2		OUT
 OUT_VEXTMENSAJECAT		VARCHAR2		OUT

SQL> Disconnected from Oracle Database 10g Enterprise Edition Release 10.2.0.5.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options
