#! /bin/bash
# Source function library.
. /etc/init.d/functions

PATH1="."
MODULO="Pxml_Receta"
case "$1" in 
  start)
	if [ -x $PATH1/Pxml_Receta ]; then
		#Con parametro timeoutbd
		./Pxml_Receta scgi=1 proceso=PXML_RECETA portdb=9000 log=1 prefijo_log=RME timeoutbd=10 >/dev/null&
		echo "./Pxml_Receta scgi=1 proceso=PXML_RECETA portdb=9000 log=1 prefijo_log=RME timeoutbd=10 "
		echo Inicializa $MODULO
	fi
	;;
  stop)
	PID=`ps -fea|grep $MODULO|awk {'print $2'}`
	kill -USR1 $PID &>/dev/null
	echo Detiene Proceso $MODULO
	killproc $PATH1/$MODULO >/dev/null
	;;
  restart|reload)
	$0 stop 
	$0 start
	echo Proceso $MODULO Reiniciado
	;;
  borralog)
        #rm *.LOG
        rm *_APP.LOG
        rm *_XXX.LOG
        rm *.ERR
        rm *.log
        echo Borra Logs $MODULO
        ;;
	
	
  *) echo start | stop
  
esac

