
SQL*Plus: Release 11.2.0.3.0 Production on Tue Aug 19 12:09:47 2014

Copyright (c) 1982, 2011, Oracle.  All rights reserved.


Connected to:
Oracle Database 10g Release 10.2.0.4.0 - 64bit Production

SQL> SQL> PROCEDURE FNDVALORVARI
 Argument Name			Type			In/Out Default?
 ------------------------------ ----------------------- ------ --------
 SRV_MESSAGE			VARCHAR2		IN/OUT
 IN_EXTCODFINANCIADOR		NUMBER			IN
 IN_EXTHOMNUMEROCONVENIO	VARCHAR2		IN
 IN_EXTHOMLUGARCONVENIO 	VARCHAR2		IN
 IN_EXTSUCVENTA 		VARCHAR2		IN
 IN_EXTRUTCONVENIO		VARCHAR2		IN
 IN_EXTRUTTRATANTE		VARCHAR2		IN
 IN_EXTESPECIALIDAD		VARCHAR2		IN
 IN_EXTRUTSOLICITANTE		VARCHAR2		IN
 IN_EXTRUTBENEFICIARIO		VARCHAR2		IN
 IN_EXTTRATAMIENTO		VARCHAR2		IN
 IN_EXTCODIGODIAGNOSTICO	VARCHAR2		IN
 IN_EXTNIVELCONVENIO		NUMBER			IN
 IN_EXTURGENCIA 		VARCHAR2		IN
 IN_EXTLISTA1			VARCHAR2		IN
 IN_EXTLISTA2			VARCHAR2		IN
 IN_EXTLISTA3			VARCHAR2		IN
 IN_EXTLISTA4			VARCHAR2		IN
 IN_EXTLISTA5			VARCHAR2		IN
 IN_EXTLISTA6			VARCHAR2		IN
 IN_EXTLISTA7			VARCHAR2		IN
 IN_EXTNUMPRESTACIONES		NUMBER			IN
 OUT_EXTCODERROR		VARCHAR2		OUT
 OUT_EXTMENSAJEERROR		VARCHAR2		OUT
 OUT_EXTPLAN			VARCHAR2		OUT
 OUT_EXTGLOSA1			VARCHAR2		OUT
 OUT_EXTGLOSA2			VARCHAR2		OUT
 OUT_EXTGLOSA3			VARCHAR2		OUT
 OUT_EXTGLOSA4			VARCHAR2		OUT
 OUT_EXTGLOSA5			VARCHAR2		OUT
 OUT_EXTVALORPRESTACION 	TABLE OF NUMBER(12)	OUT
 OUT_EXTAPORTEFINANCIADOR	TABLE OF NUMBER(12)	OUT
 OUT_EXTCOPAGO			TABLE OF NUMBER(12)	OUT
 OUT_EXTINTERNOISA		TABLE OF VARCHAR2(15)	OUT
 OUT_EXTTIPOBONIF1		TABLE OF NUMBER(1)	OUT
 OUT_EXTCOPAGO1 		TABLE OF NUMBER(12)	OUT
 OUT_EXTTIPOBONIF2		TABLE OF NUMBER(1)	OUT
 OUT_EXTCOPAGO2 		TABLE OF NUMBER(12)	OUT
 OUT_EXTTIPOBONIF3		TABLE OF NUMBER(1)	OUT
 OUT_EXTCOPAGO3 		TABLE OF NUMBER(12)	OUT
 OUT_EXTTIPOBONIF4		TABLE OF NUMBER(1)	OUT
 OUT_EXTCOPAGO4 		TABLE OF NUMBER(12)	OUT
 OUT_EXTTIPOBONIF5		TABLE OF NUMBER(1)	OUT
 OUT_EXTCOPAGO5 		TABLE OF NUMBER(12)	OUT

SQL> 
no rows selected

SQL> Disconnected from Oracle Database 10g Release 10.2.0.4.0 - 64bit Production
