/* Multicaja.h
   Generated by wsdl2h 2.8.14 from https://200.111.44.187:10005/imed/ImedWebService?wsdl and typemap.dat
   2014-12-29 17:13:58 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2000-2013 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Usage Notes

NOTE:

 - Run soapcpp2 on Multicaja.h to generate the SOAP/XML processing logic.
   Use soapcpp2 -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 -j to generate improved proxy and server classes.
 - Use wsdl2h -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Use wsdl2h -d to enable DOM support for xsd:anyType.
 - Use wsdl2h -g to auto-generate readers and writers for root elements.
 - Use wsdl2h -b to auto-generate bi-directional operations (duplex ops).
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

WARNING:

   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

LICENSE:

@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following two licenses:
GPL or Genivia's license for commercial use.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://www.multicaja.cl/imed/                                            *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


// STL vector containers (use option -s to remove STL dependency)
#import "stlvector.h"

/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "http://www.multicaja.cl/imed/"
ns2 = ""

*/

#define SOAP_NAMESPACE_OF_ns2	""
//gsoap ns2   schema namespace:	
//gsoap ns2   schema form:	unqualified

#define SOAP_NAMESPACE_OF_ns1	"http://www.multicaja.cl/imed/"
//gsoap ns1   schema namespace:	http://www.multicaja.cl/imed/
//gsoap ns1   schema form:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/



//  Forward declaration of class ns1__transaction.
class ns1__transaction;

//  Forward declaration of class ns1__WebItem.
class ns1__WebItem;

//  Forward declaration of class ns1__transactionResponse.
class ns1__transactionResponse;

//  Forward declaration of class ns1__TransactionResult.
class ns1__TransactionResult;

//  Forward declaration of class ns1__echoTest.
class ns1__echoTest;

//  Forward declaration of class ns1__echoTestResponse.
class ns1__echoTestResponse;

/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *                                                                            *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://www.multicaja.cl/imed/                                            *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *                                                                            *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://www.multicaja.cl/imed/                                            *
 *                                                                            *
\******************************************************************************/


/// "http://www.multicaja.cl/imed/":transaction is a complexType.
/// class ns1__transaction operations:
/// - soap_new_ns1__transaction(soap*) allocate
/// - soap_new_ns1__transaction(soap*, int num) allocate array
/// - soap_new_req_ns1__transaction(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__transaction(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__transaction(soap*, ns1__transaction*) deserialize from a stream
/// - int soap_write_ns1__transaction(soap, ns1__transaction*) serialize to a stream
class ns1__transaction
{ public:
/// Vector of ns1__WebItem* with length 0..unbounded
    std::vector<ns1__WebItem*          > item                           0;
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://www.multicaja.cl/imed/":WebItem is a complexType.
/// class ns1__WebItem operations:
/// - soap_new_ns1__WebItem(soap*) allocate
/// - soap_new_ns1__WebItem(soap*, int num) allocate array
/// - soap_new_req_ns1__WebItem(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__WebItem(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__WebItem(soap*, ns1__WebItem*) deserialize from a stream
/// - int soap_write_ns1__WebItem(soap, ns1__WebItem*) serialize to a stream
class ns1__WebItem
{ public:
/// Element name of type xs:string.
    std::string*                         name                           0;	///< Optional element.
/// Element value of type xs:string.
    std::string*                         value                          0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://www.multicaja.cl/imed/":transactionResponse is a complexType.
/// class ns1__transactionResponse operations:
/// - soap_new_ns1__transactionResponse(soap*) allocate
/// - soap_new_ns1__transactionResponse(soap*, int num) allocate array
/// - soap_new_req_ns1__transactionResponse(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__transactionResponse(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__transactionResponse(soap*, ns1__transactionResponse*) deserialize from a stream
/// - int soap_write_ns1__transactionResponse(soap, ns1__transactionResponse*) serialize to a stream
class ns1__transactionResponse
{ public:
/// Element return of type "http://www.multicaja.cl/imed/":TransactionResult.
    ns1__TransactionResult*              return_                        0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://www.multicaja.cl/imed/":TransactionResult is a complexType.
/// class ns1__TransactionResult operations:
/// - soap_new_ns1__TransactionResult(soap*) allocate
/// - soap_new_ns1__TransactionResult(soap*, int num) allocate array
/// - soap_new_req_ns1__TransactionResult(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__TransactionResult(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__TransactionResult(soap*, ns1__TransactionResult*) deserialize from a stream
/// - int soap_write_ns1__TransactionResult(soap, ns1__TransactionResult*) serialize to a stream
class ns1__TransactionResult
{ public:
/// Vector of ns1__WebItem* with length 0..unbounded
    std::vector<ns1__WebItem*          > item                           0;
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://www.multicaja.cl/imed/":echoTest is a complexType.
/// class ns1__echoTest operations:
/// - soap_new_ns1__echoTest(soap*) allocate
/// - soap_new_ns1__echoTest(soap*, int num) allocate array
/// - soap_new_req_ns1__echoTest(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__echoTest(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__echoTest(soap*, ns1__echoTest*) deserialize from a stream
/// - int soap_write_ns1__echoTest(soap, ns1__echoTest*) serialize to a stream
class ns1__echoTest
{ public:
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://www.multicaja.cl/imed/":echoTestResponse is a complexType.
/// class ns1__echoTestResponse operations:
/// - soap_new_ns1__echoTestResponse(soap*) allocate
/// - soap_new_ns1__echoTestResponse(soap*, int num) allocate array
/// - soap_new_req_ns1__echoTestResponse(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__echoTestResponse(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__echoTestResponse(soap*, ns1__echoTestResponse*) deserialize from a stream
/// - int soap_write_ns1__echoTestResponse(soap, ns1__echoTestResponse*) serialize to a stream
class ns1__echoTestResponse
{ public:
/// Element return of type xs:dateTime.
    time_t*                              return_                        0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *                                                                            *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *                                                                            *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://www.multicaja.cl/imed/                                            *
 *                                                                            *
\******************************************************************************/


/// Top-level root element "http://www.multicaja.cl/imed/":echoTest of type "http://www.multicaja.cl/imed/":echoTest.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://www.multicaja.cl/imed/":echoTestResponse of type "http://www.multicaja.cl/imed/":echoTestResponse.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://www.multicaja.cl/imed/":transaction of type "http://www.multicaja.cl/imed/":transaction.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://www.multicaja.cl/imed/":transactionResponse of type "http://www.multicaja.cl/imed/":transactionResponse.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://www.multicaja.cl/imed/                                            *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns1  service name:	ImedWebPortBinding 
//gsoap ns1  service type:	ImedWeb 
//gsoap ns1  service port:	https://200.111.44.187:10005/imed/ImedWebService 
//gsoap ns1  service namespace:	http://www.multicaja.cl/imed/ 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage ImedWebService Definitions

@section ImedWebService_bindings Service Bindings

  - @ref ImedWebPortBinding

@section ImedWebService_more More Information

  - @ref page_notes "Usage Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page ImedWebPortBinding Binding "ImedWebPortBinding"

@section ImedWebPortBinding_operations Operations of Binding  "ImedWebPortBinding"

  - @ref __ns1__transaction

  - @ref __ns1__echoTest

@section ImedWebPortBinding_ports Endpoints of Binding  "ImedWebPortBinding"

  - https://200.111.44.187:10005/imed/ImedWebService

Note: use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   ImedWebPortBinding                                                       *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__transaction                                                       *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__transaction" of service binding "ImedWebPortBinding"

/**

Operation details:

  - SOAP document/literal style messaging

  - Addressing input action: "http://www.multicaja.cl/imed/ImedWeb/transactionRequest"

  - Addressing output action: "http://www.multicaja.cl/imed/ImedWeb/transactionResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__transaction(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    ns1__transaction*                   ns1__transaction_,
    // output parameters:
    ns1__transactionResponse*           ns1__transactionResponse_
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__transaction(
    struct soap *soap,
    // input parameters:
    ns1__transaction*                   ns1__transaction_,
    // output parameters:
    ns1__transactionResponse*           ns1__transactionResponse_
  );
@endcode

C++ proxy class (defined in soapImedWebPortBindingProxy.h):
@code
  class ImedWebPortBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapImedWebPortBindingService.h):
@code
  class ImedWebPortBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	transaction SOAP
//gsoap ns1  service method-style:	transaction document
//gsoap ns1  service method-encoding:	transaction literal
//gsoap ns1  service method-input-action:	transaction http://www.multicaja.cl/imed/ImedWeb/transactionRequest
//gsoap ns1  service method-output-action:	transaction http://www.multicaja.cl/imed/ImedWeb/transactionResponse
int __ns1__transaction(
    ns1__transaction*                   ns1__transaction_,	///< Input parameter
    ns1__transactionResponse*           ns1__transactionResponse_	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__echoTest                                                          *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__echoTest" of service binding "ImedWebPortBinding"

/**

Operation details:

  - SOAP document/literal style messaging

  - Addressing input action: "http://www.multicaja.cl/imed/ImedWeb/echoTestRequest"

  - Addressing output action: "http://www.multicaja.cl/imed/ImedWeb/echoTestResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__echoTest(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    ns1__echoTest*                      ns1__echoTest_,
    // output parameters:
    ns1__echoTestResponse*              ns1__echoTestResponse_
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__echoTest(
    struct soap *soap,
    // input parameters:
    ns1__echoTest*                      ns1__echoTest_,
    // output parameters:
    ns1__echoTestResponse*              ns1__echoTestResponse_
  );
@endcode

C++ proxy class (defined in soapImedWebPortBindingProxy.h):
@code
  class ImedWebPortBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapImedWebPortBindingService.h):
@code
  class ImedWebPortBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	echoTest SOAP
//gsoap ns1  service method-style:	echoTest document
//gsoap ns1  service method-encoding:	echoTest literal
//gsoap ns1  service method-input-action:	echoTest http://www.multicaja.cl/imed/ImedWeb/echoTestRequest
//gsoap ns1  service method-output-action:	echoTest http://www.multicaja.cl/imed/ImedWeb/echoTestResponse
int __ns1__echoTest(
    ns1__echoTest*                      ns1__echoTest_,	///< Input parameter
    ns1__echoTestResponse*              ns1__echoTestResponse_	///< Output parameter
);

/**

@page ImedWebPortBinding Binding "ImedWebPortBinding"

@section ImedWebPortBinding_policy_enablers Policy Enablers of Binding  "ImedWebPortBinding"

Based on policies, this service imports

  - WS-Policy reminders and enablers:
    - WS-Addressing 1.0 (2005/08, accepts 2004/08):
	@code
	#import "wsa5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-Addressing (2004/08):
	@code
	#import "wsa.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-ReliableMessaging 1.0:
	@code
	#import "wsrm5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-ReliableMessaging 1.1:
	@code
	#import "wsrm.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.0 (accepts 1.1):
	@code
	#import "wsse.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.1 (accepts 1.0):
	@code
	#import "wsse11.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - HTTP Digest Authentication:
	@code
	#include "plugin/httpda.h"
	soap_register_plugin(soap, soap_http_da); // register the HTTP DA plugin in your code
	// See the user guide gsoap/doc/httpda/html/index.html
	@endcode
*/


/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

Data can be read in XML and deserialized from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

Data can be serialized in XML and written to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback

The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


@section ns2 Top-level root elements of schema ""

@section ns1 Top-level root elements of schema "http://www.multicaja.cl/imed/"

  - <ns1:echoTest> (use wsdl2h option -g to auto-generate)

  - <ns1:echoTestResponse> (use wsdl2h option -g to auto-generate)

  - <ns1:transaction> (use wsdl2h option -g to auto-generate)

  - <ns1:transactionResponse> (use wsdl2h option -g to auto-generate)

*/

/* End of Multicaja.h */
