/* soapH.h
   Generated by gSOAP 2.8.14 from Multicaja.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin(soap), soap_serialize_byte(soap, data), soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin(soap), soap_serialize_int(soap, data), soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_time
#define SOAP_TYPE_time (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_time(struct soap*, time_t *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_time(struct soap*, const char*, int, const time_t *, const char*);
SOAP_FMAC3 time_t * SOAP_FMAC4 soap_in_time(struct soap*, const char*, time_t *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_time(struct soap*, const time_t *, const char*, const char*);

#ifndef soap_write_time
#define soap_write_time(soap, data) ( soap_begin(soap), soap_serialize_time(soap, data), soap_begin_send(soap) || soap_put_time(soap, data, "dateTime", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 time_t * SOAP_FMAC4 soap_get_time(struct soap*, time_t *, const char*, const char*);

#ifndef soap_read_time
#define soap_read_time(soap, data) ( soap_begin_recv(soap) || !soap_get_time(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);

#ifndef soap_write_std__string
#define soap_write_std__string(soap, data) ( soap_begin(soap), soap_serialize_std__string(soap, data), soap_begin_send(soap) || soap_put_std__string(soap, data, "string", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);

#ifndef soap_read_std__string
#define soap_read_std__string(soap, data) ( soap_begin_recv(soap) || !soap_get_std__string(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 std::string * SOAP_FMAC2 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);

inline std::string * soap_new_std__string(struct soap *soap, int n = -1) { return soap_instantiate_std__string(soap, n, NULL, NULL, NULL); }

inline std::string * soap_new_req_std__string(struct soap *soap) { std::string *_p = soap_instantiate_std__string(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_std__string(soap, _p); } return _p; }

inline std::string * soap_new_set_std__string(struct soap *soap) { std::string *_p = soap_instantiate_std__string(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_std__string(soap, _p); } return _p; }

inline void soap_delete_std__string(struct soap *soap, std::string *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__echoTestResponse
#define SOAP_TYPE_ns1__echoTestResponse (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__echoTestResponse(struct soap*, const char*, int, const ns1__echoTestResponse *, const char*);
SOAP_FMAC3 ns1__echoTestResponse * SOAP_FMAC4 soap_in_ns1__echoTestResponse(struct soap*, const char*, ns1__echoTestResponse *, const char*);

#ifndef soap_write_ns1__echoTestResponse
#define soap_write_ns1__echoTestResponse(soap, data) ( soap_begin(soap), (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:echoTestResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__echoTestResponse * SOAP_FMAC4 soap_get_ns1__echoTestResponse(struct soap*, ns1__echoTestResponse *, const char*, const char*);

#ifndef soap_read_ns1__echoTestResponse
#define soap_read_ns1__echoTestResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__echoTestResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 ns1__echoTestResponse * SOAP_FMAC2 soap_instantiate_ns1__echoTestResponse(struct soap*, int, const char*, const char*, size_t*);

inline ns1__echoTestResponse * soap_new_ns1__echoTestResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns1__echoTestResponse(soap, n, NULL, NULL, NULL); }

inline ns1__echoTestResponse * soap_new_req_ns1__echoTestResponse(struct soap *soap) { ns1__echoTestResponse *_p = soap_instantiate_ns1__echoTestResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__echoTestResponse * soap_new_set_ns1__echoTestResponse(struct soap *soap, time_t *return_) { ns1__echoTestResponse *_p = soap_instantiate_ns1__echoTestResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__echoTestResponse::return_ = return_; } return _p; }

inline void soap_delete_ns1__echoTestResponse(struct soap *soap, ns1__echoTestResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__echoTestResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__echoTest
#define SOAP_TYPE_ns1__echoTest (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__echoTest(struct soap*, const char*, int, const ns1__echoTest *, const char*);
SOAP_FMAC3 ns1__echoTest * SOAP_FMAC4 soap_in_ns1__echoTest(struct soap*, const char*, ns1__echoTest *, const char*);

#ifndef soap_write_ns1__echoTest
#define soap_write_ns1__echoTest(soap, data) ( soap_begin(soap), (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:echoTest", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__echoTest * SOAP_FMAC4 soap_get_ns1__echoTest(struct soap*, ns1__echoTest *, const char*, const char*);

#ifndef soap_read_ns1__echoTest
#define soap_read_ns1__echoTest(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__echoTest(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 ns1__echoTest * SOAP_FMAC2 soap_instantiate_ns1__echoTest(struct soap*, int, const char*, const char*, size_t*);

inline ns1__echoTest * soap_new_ns1__echoTest(struct soap *soap, int n = -1) { return soap_instantiate_ns1__echoTest(soap, n, NULL, NULL, NULL); }

inline ns1__echoTest * soap_new_req_ns1__echoTest(struct soap *soap) { ns1__echoTest *_p = soap_instantiate_ns1__echoTest(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__echoTest * soap_new_set_ns1__echoTest(struct soap *soap) { ns1__echoTest *_p = soap_instantiate_ns1__echoTest(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline void soap_delete_ns1__echoTest(struct soap *soap, ns1__echoTest *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__echoTest(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__TransactionResult
#define SOAP_TYPE_ns1__TransactionResult (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__TransactionResult(struct soap*, const char*, int, const ns1__TransactionResult *, const char*);
SOAP_FMAC3 ns1__TransactionResult * SOAP_FMAC4 soap_in_ns1__TransactionResult(struct soap*, const char*, ns1__TransactionResult *, const char*);

#ifndef soap_write_ns1__TransactionResult
#define soap_write_ns1__TransactionResult(soap, data) ( soap_begin(soap), (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:TransactionResult", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__TransactionResult * SOAP_FMAC4 soap_get_ns1__TransactionResult(struct soap*, ns1__TransactionResult *, const char*, const char*);

#ifndef soap_read_ns1__TransactionResult
#define soap_read_ns1__TransactionResult(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__TransactionResult(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 ns1__TransactionResult * SOAP_FMAC2 soap_instantiate_ns1__TransactionResult(struct soap*, int, const char*, const char*, size_t*);

inline ns1__TransactionResult * soap_new_ns1__TransactionResult(struct soap *soap, int n = -1) { return soap_instantiate_ns1__TransactionResult(soap, n, NULL, NULL, NULL); }

inline ns1__TransactionResult * soap_new_req_ns1__TransactionResult(struct soap *soap) { ns1__TransactionResult *_p = soap_instantiate_ns1__TransactionResult(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__TransactionResult * soap_new_set_ns1__TransactionResult(struct soap *soap, std::vector<ns1__WebItem * >& item) { ns1__TransactionResult *_p = soap_instantiate_ns1__TransactionResult(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__TransactionResult::item = item; } return _p; }

inline void soap_delete_ns1__TransactionResult(struct soap *soap, ns1__TransactionResult *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__TransactionResult(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__transactionResponse
#define SOAP_TYPE_ns1__transactionResponse (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__transactionResponse(struct soap*, const char*, int, const ns1__transactionResponse *, const char*);
SOAP_FMAC3 ns1__transactionResponse * SOAP_FMAC4 soap_in_ns1__transactionResponse(struct soap*, const char*, ns1__transactionResponse *, const char*);

#ifndef soap_write_ns1__transactionResponse
#define soap_write_ns1__transactionResponse(soap, data) ( soap_begin(soap), (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:transactionResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__transactionResponse * SOAP_FMAC4 soap_get_ns1__transactionResponse(struct soap*, ns1__transactionResponse *, const char*, const char*);

#ifndef soap_read_ns1__transactionResponse
#define soap_read_ns1__transactionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__transactionResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 ns1__transactionResponse * SOAP_FMAC2 soap_instantiate_ns1__transactionResponse(struct soap*, int, const char*, const char*, size_t*);

inline ns1__transactionResponse * soap_new_ns1__transactionResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns1__transactionResponse(soap, n, NULL, NULL, NULL); }

inline ns1__transactionResponse * soap_new_req_ns1__transactionResponse(struct soap *soap) { ns1__transactionResponse *_p = soap_instantiate_ns1__transactionResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__transactionResponse * soap_new_set_ns1__transactionResponse(struct soap *soap, ns1__TransactionResult *return_) { ns1__transactionResponse *_p = soap_instantiate_ns1__transactionResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__transactionResponse::return_ = return_; } return _p; }

inline void soap_delete_ns1__transactionResponse(struct soap *soap, ns1__transactionResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__transactionResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__WebItem
#define SOAP_TYPE_ns1__WebItem (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__WebItem(struct soap*, const char*, int, const ns1__WebItem *, const char*);
SOAP_FMAC3 ns1__WebItem * SOAP_FMAC4 soap_in_ns1__WebItem(struct soap*, const char*, ns1__WebItem *, const char*);

#ifndef soap_write_ns1__WebItem
#define soap_write_ns1__WebItem(soap, data) ( soap_begin(soap), (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:WebItem", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__WebItem * SOAP_FMAC4 soap_get_ns1__WebItem(struct soap*, ns1__WebItem *, const char*, const char*);

#ifndef soap_read_ns1__WebItem
#define soap_read_ns1__WebItem(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__WebItem(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 ns1__WebItem * SOAP_FMAC2 soap_instantiate_ns1__WebItem(struct soap*, int, const char*, const char*, size_t*);

inline ns1__WebItem * soap_new_ns1__WebItem(struct soap *soap, int n = -1) { return soap_instantiate_ns1__WebItem(soap, n, NULL, NULL, NULL); }

inline ns1__WebItem * soap_new_req_ns1__WebItem(struct soap *soap) { ns1__WebItem *_p = soap_instantiate_ns1__WebItem(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__WebItem * soap_new_set_ns1__WebItem(struct soap *soap, std::string *name, std::string *value) { ns1__WebItem *_p = soap_instantiate_ns1__WebItem(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__WebItem::name = name; _p->ns1__WebItem::value = value; } return _p; }

inline void soap_delete_ns1__WebItem(struct soap *soap, ns1__WebItem *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__WebItem(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__transaction
#define SOAP_TYPE_ns1__transaction (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__transaction(struct soap*, const char*, int, const ns1__transaction *, const char*);
SOAP_FMAC3 ns1__transaction * SOAP_FMAC4 soap_in_ns1__transaction(struct soap*, const char*, ns1__transaction *, const char*);

#ifndef soap_write_ns1__transaction
#define soap_write_ns1__transaction(soap, data) ( soap_begin(soap), (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:transaction", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__transaction * SOAP_FMAC4 soap_get_ns1__transaction(struct soap*, ns1__transaction *, const char*, const char*);

#ifndef soap_read_ns1__transaction
#define soap_read_ns1__transaction(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__transaction(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 ns1__transaction * SOAP_FMAC2 soap_instantiate_ns1__transaction(struct soap*, int, const char*, const char*, size_t*);

inline ns1__transaction * soap_new_ns1__transaction(struct soap *soap, int n = -1) { return soap_instantiate_ns1__transaction(soap, n, NULL, NULL, NULL); }

inline ns1__transaction * soap_new_req_ns1__transaction(struct soap *soap) { ns1__transaction *_p = soap_instantiate_ns1__transaction(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__transaction * soap_new_set_ns1__transaction(struct soap *soap, std::vector<ns1__WebItem * >& item) { ns1__transaction *_p = soap_instantiate_ns1__transaction(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__transaction::item = item; } return _p; }

inline void soap_delete_ns1__transaction(struct soap *soap, ns1__transaction *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__transaction(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Fault(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Fault * soap_new_SOAP_ENV__Fault(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Fault * soap_new_req_SOAP_ENV__Fault(struct soap *soap) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); } return _p; }

inline struct SOAP_ENV__Fault * soap_new_set_SOAP_ENV__Fault(struct soap *soap, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); _p->faultcode = faultcode; _p->faultstring = faultstring; _p->faultactor = faultactor; _p->detail = detail; _p->SOAP_ENV__Code = SOAP_ENV__Code; _p->SOAP_ENV__Reason = SOAP_ENV__Reason; _p->SOAP_ENV__Node = SOAP_ENV__Node; _p->SOAP_ENV__Role = SOAP_ENV__Role; _p->SOAP_ENV__Detail = SOAP_ENV__Detail; } return _p; }

inline void soap_delete_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Reason(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Reason * soap_new_SOAP_ENV__Reason(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Reason * soap_new_req_SOAP_ENV__Reason(struct soap *soap) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); } return _p; }

inline struct SOAP_ENV__Reason * soap_new_set_SOAP_ENV__Reason(struct soap *soap, char *SOAP_ENV__Text) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); _p->SOAP_ENV__Text = SOAP_ENV__Text; } return _p; }

inline void soap_delete_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Detail(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Detail * soap_new_SOAP_ENV__Detail(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Detail * soap_new_req_SOAP_ENV__Detail(struct soap *soap, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__type = __type; _p->fault = fault; } return _p; }

inline struct SOAP_ENV__Detail * soap_new_set_SOAP_ENV__Detail(struct soap *soap, char *__any, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__any = __any; _p->__type = __type; _p->fault = fault; } return _p; }

inline void soap_delete_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Code(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Code * soap_new_SOAP_ENV__Code(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Code * soap_new_req_SOAP_ENV__Code(struct soap *soap) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); } return _p; }

inline struct SOAP_ENV__Code * soap_new_set_SOAP_ENV__Code(struct soap *soap, char *SOAP_ENV__Value, struct SOAP_ENV__Code *SOAP_ENV__Subcode) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); _p->SOAP_ENV__Value = SOAP_ENV__Value; _p->SOAP_ENV__Subcode = SOAP_ENV__Subcode; } return _p; }

inline void soap_delete_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Header(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Header * soap_new_SOAP_ENV__Header(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Header * soap_new_req_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline struct SOAP_ENV__Header * soap_new_set_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline void soap_delete_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns1__echoTest
#define SOAP_TYPE___ns1__echoTest (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__echoTest(struct soap*, struct __ns1__echoTest *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__echoTest(struct soap*, const struct __ns1__echoTest *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__echoTest(struct soap*, const char*, int, const struct __ns1__echoTest *, const char*);
SOAP_FMAC3 struct __ns1__echoTest * SOAP_FMAC4 soap_in___ns1__echoTest(struct soap*, const char*, struct __ns1__echoTest *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__echoTest(struct soap*, const struct __ns1__echoTest *, const char*, const char*);

#ifndef soap_write___ns1__echoTest
#define soap_write___ns1__echoTest(soap, data) ( soap_begin(soap), soap_serialize___ns1__echoTest(soap, data), soap_begin_send(soap) || soap_put___ns1__echoTest(soap, data, "-ns1:echoTest", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__echoTest * SOAP_FMAC4 soap_get___ns1__echoTest(struct soap*, struct __ns1__echoTest *, const char*, const char*);

#ifndef soap_read___ns1__echoTest
#define soap_read___ns1__echoTest(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__echoTest(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct __ns1__echoTest * SOAP_FMAC2 soap_instantiate___ns1__echoTest(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__echoTest * soap_new___ns1__echoTest(struct soap *soap, int n = -1) { return soap_instantiate___ns1__echoTest(soap, n, NULL, NULL, NULL); }

inline struct __ns1__echoTest * soap_new_req___ns1__echoTest(struct soap *soap) { struct __ns1__echoTest *_p = soap_instantiate___ns1__echoTest(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__echoTest(soap, _p); } return _p; }

inline struct __ns1__echoTest * soap_new_set___ns1__echoTest(struct soap *soap, ns1__echoTest *ns1__echoTest_) { struct __ns1__echoTest *_p = soap_instantiate___ns1__echoTest(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__echoTest(soap, _p); _p->ns1__echoTest_ = ns1__echoTest_; } return _p; }

inline void soap_delete___ns1__echoTest(struct soap *soap, struct __ns1__echoTest *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__echoTest(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__transaction
#define SOAP_TYPE___ns1__transaction (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__transaction(struct soap*, struct __ns1__transaction *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__transaction(struct soap*, const struct __ns1__transaction *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__transaction(struct soap*, const char*, int, const struct __ns1__transaction *, const char*);
SOAP_FMAC3 struct __ns1__transaction * SOAP_FMAC4 soap_in___ns1__transaction(struct soap*, const char*, struct __ns1__transaction *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__transaction(struct soap*, const struct __ns1__transaction *, const char*, const char*);

#ifndef soap_write___ns1__transaction
#define soap_write___ns1__transaction(soap, data) ( soap_begin(soap), soap_serialize___ns1__transaction(soap, data), soap_begin_send(soap) || soap_put___ns1__transaction(soap, data, "-ns1:transaction", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__transaction * SOAP_FMAC4 soap_get___ns1__transaction(struct soap*, struct __ns1__transaction *, const char*, const char*);

#ifndef soap_read___ns1__transaction
#define soap_read___ns1__transaction(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__transaction(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct __ns1__transaction * SOAP_FMAC2 soap_instantiate___ns1__transaction(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__transaction * soap_new___ns1__transaction(struct soap *soap, int n = -1) { return soap_instantiate___ns1__transaction(soap, n, NULL, NULL, NULL); }

inline struct __ns1__transaction * soap_new_req___ns1__transaction(struct soap *soap) { struct __ns1__transaction *_p = soap_instantiate___ns1__transaction(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__transaction(soap, _p); } return _p; }

inline struct __ns1__transaction * soap_new_set___ns1__transaction(struct soap *soap, ns1__transaction *ns1__transaction_) { struct __ns1__transaction *_p = soap_instantiate___ns1__transaction(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__transaction(soap, _p); _p->ns1__transaction_ = ns1__transaction_; } return _p; }

inline void soap_delete___ns1__transaction(struct soap *soap, struct __ns1__transaction *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__transaction(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin(soap), soap_serialize_PointerToSOAP_ENV__Reason(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin(soap), soap_serialize_PointerToSOAP_ENV__Detail(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin(soap), soap_serialize_PointerToSOAP_ENV__Code(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef SOAP_TYPE_PointerTons1__echoTestResponse
#define SOAP_TYPE_PointerTons1__echoTestResponse (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__echoTestResponse(struct soap*, ns1__echoTestResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__echoTestResponse(struct soap*, const char *, int, ns1__echoTestResponse *const*, const char *);
SOAP_FMAC3 ns1__echoTestResponse ** SOAP_FMAC4 soap_in_PointerTons1__echoTestResponse(struct soap*, const char*, ns1__echoTestResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__echoTestResponse(struct soap*, ns1__echoTestResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__echoTestResponse
#define soap_write_PointerTons1__echoTestResponse(soap, data) ( soap_begin(soap), soap_serialize_PointerTons1__echoTestResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__echoTestResponse(soap, data, "ns1:echoTestResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__echoTestResponse ** SOAP_FMAC4 soap_get_PointerTons1__echoTestResponse(struct soap*, ns1__echoTestResponse **, const char*, const char*);

#ifndef soap_read_PointerTons1__echoTestResponse
#define soap_read_PointerTons1__echoTestResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__echoTestResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__echoTest
#define SOAP_TYPE_PointerTons1__echoTest (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__echoTest(struct soap*, ns1__echoTest *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__echoTest(struct soap*, const char *, int, ns1__echoTest *const*, const char *);
SOAP_FMAC3 ns1__echoTest ** SOAP_FMAC4 soap_in_PointerTons1__echoTest(struct soap*, const char*, ns1__echoTest **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__echoTest(struct soap*, ns1__echoTest *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__echoTest
#define soap_write_PointerTons1__echoTest(soap, data) ( soap_begin(soap), soap_serialize_PointerTons1__echoTest(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__echoTest(soap, data, "ns1:echoTest", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__echoTest ** SOAP_FMAC4 soap_get_PointerTons1__echoTest(struct soap*, ns1__echoTest **, const char*, const char*);

#ifndef soap_read_PointerTons1__echoTest
#define soap_read_PointerTons1__echoTest(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__echoTest(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__transactionResponse
#define SOAP_TYPE_PointerTons1__transactionResponse (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__transactionResponse(struct soap*, ns1__transactionResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__transactionResponse(struct soap*, const char *, int, ns1__transactionResponse *const*, const char *);
SOAP_FMAC3 ns1__transactionResponse ** SOAP_FMAC4 soap_in_PointerTons1__transactionResponse(struct soap*, const char*, ns1__transactionResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__transactionResponse(struct soap*, ns1__transactionResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__transactionResponse
#define soap_write_PointerTons1__transactionResponse(soap, data) ( soap_begin(soap), soap_serialize_PointerTons1__transactionResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__transactionResponse(soap, data, "ns1:transactionResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__transactionResponse ** SOAP_FMAC4 soap_get_PointerTons1__transactionResponse(struct soap*, ns1__transactionResponse **, const char*, const char*);

#ifndef soap_read_PointerTons1__transactionResponse
#define soap_read_PointerTons1__transactionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__transactionResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__transaction
#define SOAP_TYPE_PointerTons1__transaction (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__transaction(struct soap*, ns1__transaction *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__transaction(struct soap*, const char *, int, ns1__transaction *const*, const char *);
SOAP_FMAC3 ns1__transaction ** SOAP_FMAC4 soap_in_PointerTons1__transaction(struct soap*, const char*, ns1__transaction **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__transaction(struct soap*, ns1__transaction *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__transaction
#define soap_write_PointerTons1__transaction(soap, data) ( soap_begin(soap), soap_serialize_PointerTons1__transaction(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__transaction(soap, data, "ns1:transaction", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__transaction ** SOAP_FMAC4 soap_get_PointerTons1__transaction(struct soap*, ns1__transaction **, const char*, const char*);

#ifndef soap_read_PointerTons1__transaction
#define soap_read_PointerTons1__transaction(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__transaction(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTotime
#define SOAP_TYPE_PointerTotime (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotime(struct soap*, time_t *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotime(struct soap*, const char *, int, time_t *const*, const char *);
SOAP_FMAC3 time_t ** SOAP_FMAC4 soap_in_PointerTotime(struct soap*, const char*, time_t **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotime(struct soap*, time_t *const*, const char*, const char*);

#ifndef soap_write_PointerTotime
#define soap_write_PointerTotime(soap, data) ( soap_begin(soap), soap_serialize_PointerTotime(soap, data), soap_begin_send(soap) || soap_put_PointerTotime(soap, data, "dateTime", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 time_t ** SOAP_FMAC4 soap_get_PointerTotime(struct soap*, time_t **, const char*, const char*);

#ifndef soap_read_PointerTotime
#define soap_read_PointerTotime(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTotime(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__TransactionResult
#define SOAP_TYPE_PointerTons1__TransactionResult (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__TransactionResult(struct soap*, ns1__TransactionResult *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__TransactionResult(struct soap*, const char *, int, ns1__TransactionResult *const*, const char *);
SOAP_FMAC3 ns1__TransactionResult ** SOAP_FMAC4 soap_in_PointerTons1__TransactionResult(struct soap*, const char*, ns1__TransactionResult **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__TransactionResult(struct soap*, ns1__TransactionResult *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__TransactionResult
#define soap_write_PointerTons1__TransactionResult(soap, data) ( soap_begin(soap), soap_serialize_PointerTons1__TransactionResult(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__TransactionResult(soap, data, "ns1:TransactionResult", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__TransactionResult ** SOAP_FMAC4 soap_get_PointerTons1__TransactionResult(struct soap*, ns1__TransactionResult **, const char*, const char*);

#ifndef soap_read_PointerTons1__TransactionResult
#define soap_read_PointerTons1__TransactionResult(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__TransactionResult(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTostd__string
#define SOAP_TYPE_PointerTostd__string (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__string(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__string(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTostd__string(struct soap*, const char*, std::string **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__string(struct soap*, std::string *const*, const char*, const char*);

#ifndef soap_write_PointerTostd__string
#define soap_write_PointerTostd__string(soap, data) ( soap_begin(soap), soap_serialize_PointerTostd__string(soap, data), soap_begin_send(soap) || soap_put_PointerTostd__string(soap, data, "string", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTostd__string(struct soap*, std::string **, const char*, const char*);

#ifndef soap_read_PointerTostd__string
#define soap_read_PointerTostd__string(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTostd__string(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__WebItem
#define SOAP_TYPE_PointerTons1__WebItem (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__WebItem(struct soap*, ns1__WebItem *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__WebItem(struct soap*, const char *, int, ns1__WebItem *const*, const char *);
SOAP_FMAC3 ns1__WebItem ** SOAP_FMAC4 soap_in_PointerTons1__WebItem(struct soap*, const char*, ns1__WebItem **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__WebItem(struct soap*, ns1__WebItem *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__WebItem
#define soap_write_PointerTons1__WebItem(soap, data) ( soap_begin(soap), soap_serialize_PointerTons1__WebItem(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__WebItem(soap, data, "ns1:WebItem", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__WebItem ** SOAP_FMAC4 soap_get_PointerTons1__WebItem(struct soap*, ns1__WebItem **, const char*, const char*);

#ifndef soap_read_PointerTons1__WebItem
#define soap_read_PointerTons1__WebItem(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__WebItem(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin(soap), soap_serialize__QName(soap, data), soap_begin_send(soap) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin(soap), soap_serialize_string(soap, data), soap_begin_send(soap) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTons1__WebItem
#define SOAP_TYPE_std__vectorTemplateOfPointerTons1__WebItem (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTons1__WebItem(struct soap*, std::vector<ns1__WebItem * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTons1__WebItem(struct soap*, const std::vector<ns1__WebItem * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTons1__WebItem(struct soap*, const char*, int, const std::vector<ns1__WebItem * >*, const char*);
SOAP_FMAC3 std::vector<ns1__WebItem * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTons1__WebItem(struct soap*, const char*, std::vector<ns1__WebItem * >*, const char*);
SOAP_FMAC1 std::vector<ns1__WebItem * > * SOAP_FMAC2 soap_instantiate_std__vectorTemplateOfPointerTons1__WebItem(struct soap*, int, const char*, const char*, size_t*);

inline std::vector<ns1__WebItem * > * soap_new_std__vectorTemplateOfPointerTons1__WebItem(struct soap *soap, int n = -1) { return soap_instantiate_std__vectorTemplateOfPointerTons1__WebItem(soap, n, NULL, NULL, NULL); }

inline void soap_delete_std__vectorTemplateOfPointerTons1__WebItem(struct soap *soap, std::vector<ns1__WebItem * >*p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTons1__WebItem(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

/* End of soapH.h */
