
SQL*Plus: Release 11.2.0.3.0 Production on Thu Aug 8 18:07:06 2013

Copyright (c) 1982, 2011, Oracle.  All rights reserved.


Connected to:
Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit Production

SQL> SQL> PROCEDURE VIDENVBONIS
 Argument Name			Type			In/Out Default?
 ------------------------------ ----------------------- ------ --------
 SRV_MESSAGE			VARCHAR2		IN/OUT
 IN_EXTCODFINANCIADOR		NUMBER			IN
 IN_EXTHOMNUMEROCONVENIO	VARCHAR2		IN
 IN_EXTHOMLUGARCONVENIO 	VARCHAR2		IN
 IN_EXTSUCVENTA 		VARCHAR2		IN
 INEXTRUTCONVENIO		VARCHAR2		IN
 INEXTRUTASOCIADO		VARCHAR2		IN
 IN_EXTNOMPRESTADOR		VARCHAR2		IN
 INEXTRUTTRATANTE		VARCHAR2		IN
 IN_EXTESPECIALIDAD		VARCHAR2		IN
 INEXTRUTBENEFICIARIO		VARCHAR2		IN
 INEXTRUTCOTIZANTE		VARCHAR2		IN
 INEXTRUTACOMPANANTE		VARCHAR2		IN
 INEXTRUTEMISOR 		VARCHAR2		IN
 INEXTRUTCAJERO 		VARCHAR2		IN
 IN_EXTCODIGODIAGNOSTICO	VARCHAR2		IN
 IN_EXTDESCUENTOXPLANILLA	VARCHAR2		IN
 IN_EXTMONTOEXCEDENTE		NUMBER			IN
 IN_EXTFECHAEMISION		DATE			IN
 IN_EXTNIVELCONVENIO		NUMBER			IN
 IN_EXTFOLIOFINANCIADOR 	NUMBER			IN
 IN_EXTMONTOVALORTOTAL		NUMBER			IN
 IN_EXTMONTOAPORTETOTAL 	NUMBER			IN
 IN_EXTMONTOCOPAGOTOTAL 	NUMBER			IN
 IN_EXTNUMOPERACION		NUMBER			IN
 IN_EXTCORRPRESTACION		NUMBER			IN
 IN_EXTTIPOSOLICITUD		NUMBER			IN
 IN_EXTFECHAINICIO		DATE			IN
 IN_EXTURGENCIA 		VARCHAR2		IN
 IN_EXTPLAN			VARCHAR2		IN
 IN_EXTLISTA1			VARCHAR2		IN
 IN_EXTLISTA2			VARCHAR2		IN
 IN_EXTLISTA3			VARCHAR2		IN
 OUT_EXTCODERROR		VARCHAR2		OUT
 OUT_EXTMENSAJEERROR		VARCHAR2		OUT

SQL> Disconnected from Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit Production
